### ISSUE TITLE
Create contributing guidelines

### ISSUE THREAD

**Issue by marko-radosavljevic** [Together-Java/TJ-Bot#1]
Create CONTRIBUTING.md with contributing guidelines.

<br />

Things we would like to achieve with our guidelines:
 - Beginner friendly and easy to follow
 - Clear and precise instructions
 - Streamlined process

Assigning this to myself, but please comment if there is anything I should take into consideration before creating a PR.
All ideas and suggestions are welcome! ^^

**Comment by illuminator3** [comment]
it'd probably also be good to include a short summary of that in the README.md so that people instantly see it when going to the github page
