### ISSUE TITLE
Explore possibilities to lock the test-bot to a single channel

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#101]
Ideally, the test-bot (running `develop`) would only accept commands from a single dedicated test channel. This is about exploring possibilities to do so, while not disrupting the regular code flow and introduce huge branchings like `if (isDevBot) { ... } else { ... }` all over in the logic.

Maybe we also have find satisfying idea to have both bots co-existing in the same server without annoying people and having a good UX at the same time, e.g. prefixing each command with `test`, example `/ping` vs `/test-ping`

**Comment by Tais993** [comment]
Add an argument when starting the program?
This argument gets parsed to classes that need it (so CommandHandler, which parses it to the ReloadCommand)
The ReloadCommand then adds the test prefix?

Preferably I'd say test locally or somewhere else, and push to Master when it's finished.

**Comment by Zabuzard** [comment]
Obsolete due to #106 which decided that, for now, we will go with a single bot per guild.

The `develop` bot might be re-introduced on a second guild.
