### ISSUE TITLE
Title for transfer questions generated by ai

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#1011]
When we want to transfer a question we have to give it a suitable title, manually

We can ask chatgpt to generate a suitable title for the question.

Additional Context:
Method `createTitle` is responsible for generating modal title in `TransferQuestionCommand.java`

**Comment by vishv843** [comment]
Hi I wanna work on this

**Comment by ankitsmt211** [comment]
Sure thing, welcome to the project 😊
