### ISSUE TITLE
GitHub Reference feature wrong package

### ISSUE THREAD

**Issue by SquidXTV** [Together-Java/TJ-Bot#1019]
# About

The GitHub reference feature is located in `command.github` but should be in `features.github` instead like any other feature.

**Comment by Jayanta-karmakar** [comment]
heyy.. i wanna work on this

**Comment by marko-radosavljevic** [comment]
Welcome to the project @Jayanta-karmakar! :heart: :relaxed:

**Comment by Jayanta-karmakar** [comment]
Hey @marko-radosavljevic  

Thanks for your welcome. I am excited to be part of the project and looking forward to contributing 💻
