### ISSUE TITLE
/tags should be emphemeral

### ISSUE THREAD

**Issue by KoblizekXD** [Together-Java/TJ-Bot#1026]
**Describe the bug**
`/tags` command should be emphemeral, instead of flooding the channel, it could stay visible only to the sender, so they don't have to switch to bot/commands related channel

**Expected behavior**
`/tags` command should become emphemeral

**To Reproduce**  
1. execute `/tags` command

**Screenshots**
I believe the problem is self explanatory, so no screenshot is needed

**Additional context**
None

**Comment by ankitsmt211** [comment]
duplicate issue #958 
PR already in progress #983
