### ISSUE TITLE
[FEATURE] Auto thread feature for help channels

### ISSUE THREAD

**Issue by mertkug** [Together-Java/TJ-Bot#104]
So the idea is bot creating auto thread from user messages, so that helpers and users can follow easily,  and there should be also close thread option for helpers.
Also original messages should be stay so that helper can look original message and click the thread , and help to people who has issue.

Prototype of feature : 

![firefox_mFqsZ1l3D6](https://user-images.githubusercontent.com/56736947/132996631-935e9d40-a1f2-41aa-acd2-256c73f4a53a.png)

Also for close thread prototype : 

![firefox_wFzsuw0Zq3](https://user-images.githubusercontent.com/56736947/132996659-32ab3157-aa6c-4c18-84a6-9b980c50011d.png)

Also issuer/helper should be able to check thread as fixed,  so that other helpers look , see its fixed and dont bother

![firefox_tTDN7W7bAc](https://user-images.githubusercontent.com/56736947/132996907-dbd37b28-1730-45fa-9959-d245177cb4be.png)

**Comment by Tais993** [comment]
JDA doesn't support threads, in JDA 5 support will be there.

**Comment by illuminator3** [comment]
Like Tijs said, we already talked about this in the past and came to the conclusion that they don't perfectly fit our needs. We may add them in the future, but they are currently lacking a lot of things.
