### ISSUE TITLE
Usage of 1 bot instead of 2

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#106]
*Commands = slash-commands and context-menus*

**Is your feature request related to a problem? Please describe.**
2 bots mean that some things have to be disabled, things like open-channel-info and a lot more in the feature needs to check or it's the test bot or not.
I feel like this makes things more complicated, without a reason.

**Describe the solution you'd like**

### Solution 1

Almost every bot developer tests things within their test guild / their guild.
Then releases it when testing finished without errors.
99% of the things can be properly tested within a private guild, and this also saves us from having duplicated commands

Yes there are exceptions, premium guild features can't be tested privately, and this is the only down-side.
Regardless, imho the "developer" branch should be bug-less, code that gets PR'd should be tested before-hand.
We can't test everything on the developer branch, this will make PR and commit history a mess.

The one exception where the testing did go wrong, doesn't really matter.
That one command doesn't work then, everything else still works.

### Solution 2

By creating a **public** testing guild with the test bot, none of the code needs to be modified.
While still allowing advanced testing by other users.

This solve the issue of having a duplicated bot run twice within the same server, by separating the duplicated bots to other environments so they won't interfere with each other.. 

**Describe alternatives you've considered**
Messing with adding a prefix to all commands, adding checks on places so the code doesn't run when it's the test bot.

**Comment by marko-radosavljevic** [comment]
> Regardless, imho the "developer" branch should be bug-less

That's the issue, it's impossible to have bug-less code, and that's the idea behind having a staging area, so we don't have a bot that constantly breaks.

**Comment by Tais993** [comment]
> > Regardless, imho the "developer" branch should be bug-less
> 
> That's the issue, it's impossible to have bug-less code, and that's the idea behind having a staging area, so we don't have a bot that constantly breaks.

See quote below

> The one exception where the testing did go wrong, doesn't really matter.
> That one command doesn't work then, everything else still works.

(imo) Ccomplicating the rest because bugs *can* happen, isn't the solution.

Like I mentioned, have the same bot twice in 1 server makes a lot complicated.
Having the the same bot in 2 different servers makes it a lot easier.

Alternatively we could create a public test-guild.
Doesn't require changes to the code, while still allowing more advanced testing by others.
*Will add this to my main post*

**Comment by Zabuzard** [comment]
I get the argument with two bots making things complex.

The only issue I see is, what if a bug actually causes the whole system to break and go down. Having it on a single bot (even if its different guilds), will cause the server to go offline for everyone entirely.

That, plus the fact that we have beginners working on our code base, who can fairly easily get code pushed without a proper testing-stage, can lead to such issues.

Anyways, this is pure speculation on my end, I am okay with going with a single bot first and see if it works out fine.

**Comment by Tais993** [comment]
> what if a bug actually causes the whole system to break and go down

This is extremely unlikely to happen, either something goes extremely wrong wrong with JDA, or something happens on start-up.
And start-up will be noticed instantly, so will be fixed really fast.

> That, plus the fact that we have beginners working on our code base, who can fairly easily get code pushed without a proper testing-stage, can lead to such issues.
This is why I suggested the having an alternative Discord with the developer branch bot.
Everyone can join this Discord and everyone can test for bugs.
We should also check for bugs ourselves, things we can think of, I don't mean advanced testing.

**Comment by Zabuzard** [comment]
Okay. Then lets remove the `develop` bot from our guild, possibly create a second guild for testing and invite it there.

For now, we will go with a single bot on our guild, which uses the stable `master` branch.
