### ISSUE TITLE
Timeout Exception

### ISSUE THREAD

**Issue by ankitsmt211** [Together-Java/TJ-Bot#1072]
**Describe the bug**

For over months now, this issue has been flooding logs. We haven't been able to trace it down so far.

![image](https://github.com/Together-Java/TJ-Bot/assets/61616007/1b93bfd5-d565-4629-9cfa-19cc52e68b61)

**Comment by tj-wazei** [comment]
Happening since October 2022??

**Comment by ankitsmt211** [comment]
fixed in release V4.9.3, more information here https://github.com/Together-Java/TJ-Bot/releases/tag/v.4.9.3
