### ISSUE TITLE
Make the github embed have more accurate colors

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#1074]
## Issue
Right now the embed is either red/green to show active status, but it doesn't show the exact state.

## Solution
Add more colors to the embed, for example, purple for merged prs and closed as done issues, grey for closed as not planned issues ... 

### Additional Context
First embed is for marked as completed issue and second is for open pr
![image](https://github.com/Together-Java/TJ-Bot/assets/73871477/7fd4e6c9-317f-4b49-8049-91cc76392690)

For merged pr
![image](https://github.com/Together-Java/TJ-Bot/assets/73871477/984e71b3-e6a3-4298-8444-1f3471b01e2d)

**Comment by Suleman70** [comment]
Can i be assigned to this?

**Comment by Taz03** [comment]
Implemented in #1075
