### ISSUE TITLE
Pinned threads should not be archived in questions

### ISSUE THREAD

**Issue by ankitsmt211** [Together-Java/TJ-Bot#1084]
**Describe the bug**

Pinned messages/threads is a means to provide information in context of channel, but with current setup all threads are archived in questions regardless of state thus making this feature useless

**Expected behavior**

Bot should ignore pinned threads when archive routine is triggered
**To Reproduce**

1. Tweak archive routine time from 12 hours to few minutes for testing on local setup
2. Run local instance of bot
3. create a thread in questions
4. pin the thread
5. wait for it to be archived

**Additional context**

* `HelpThreadAutoArchiver#shouldBeArchived` method should skip threads which are pinned

* `HelpThreadAutoArchiver#shouldBeArchived` should be moved before calling auto archive flow on each thread, it should skip threads using `shouldBeArchived` method
    
![image](https://github.com/Together-Java/TJ-Bot/assets/61616007/875ceae2-72ca-42a7-b669-74b583af1eb6)

https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadAutoArchiver.java

**Comment by JayBhensdadia** [comment]
I've created a pull request to address issue #1084. Since there hasn't been much activity on this issue, I decided to work on a solution. It would be great if you could review it and let me know if there are any changes or adjustments needed. I'm open to any feedback or suggestions to improve it. Thanks!
