### ISSUE TITLE
Note command lacks safety checks in onSlashCommand like BanCommand

### ISSUE THREAD

**Issue by SimonVerhoeven** [Together-Java/TJ-Bot#1085]
**Describe the bug**
Note command lacks safety checks in onSlashCommand like BanCommand

**Expected behavior**
For the checks to be present

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by ankitsmt211** [comment]
shouldn't we use discord's inbuilt `required` arguement instead? It would educate the user and stop the command from execution.

**Comment by SimonVerhoeven** [comment]
In the AddOption they're already marked as required true to educate the user, but the handling (onSlashCommand) was inconsistent.
