### ISSUE TITLE
Make use of getFirst/getLast

### ISSUE THREAD

**Issue by SimonVerhoeven** [Together-Java/TJ-Bot#1091]
**Is your feature request related to a problem? Please describe.**

Not a problem, but there are some occurrences such as `.get(scheduleHours.size() - 1)` which could be replaced with getLast().

**Describe the solution you'd like**

To make use of the new convenience methods.

**Additional context**

similiarly, get(0) will be replaced by getFirst()

**Comment by nefelhhh** [comment]
hi can I take on this?
