### ISSUE TITLE
ChatGPT Auto-Answer should not be posted when attachment

### ISSUE THREAD

**Issue by SquidXTV** [Together-Java/TJ-Bot#1121]
# About
Currently the chatgpt response checks for images and links before posting a response. This is used to prevent bad answers because of missing context. 

It is currently missing the check for attachments in general, like PDFs or similar.

**Comment by firasrg** [comment]
From the information I have, this issue is quite similar to #918. The new check on attachment(s), should apply to all kinds of files like PDF, text or others ..
