### ISSUE TITLE
Command `/jshell version` result is broken visually.

### ISSUE THREAD

**Issue by Alathreon** [Together-Java/TJ-Bot#1147]
**Describe the bug**

When using `/jshell version`, it results into something like this. The backsticks are not supposed to be visible.
![image](https://github.com/user-attachments/assets/5d4a3133-a011-4270-914b-a4760dd120e3)

**Expected behavior**

The backsticks shouldn't be here.

**To Reproduce**

Enter the command `/jshell version`.

**Screenshots**

**Additional context**

**Comment by Andrew1031** [comment]
Hi, I'd like to work on this, but when I run "/jshell version" I get this error because I don't have the jshell parameter set

![image](https://github.com/user-attachments/assets/deced703-bbf8-4067-9e2c-17afea15a990)

What should I put for the jshell rest API URL?

![image](https://github.com/user-attachments/assets/d551733c-07a3-4b53-836b-3b67640bde0f)

**Comment by Alathreon** [comment]
Hello, you need to setup https://github.com/Together-Java/JShellPlaygroundBackend locally in order to make it work locally.
And once the backend works, edit the base url by the url you are using for the backend.

**Comment by Andrew1031** [comment]
> Hello, you need to setup https://github.com/Together-Java/JShellPlaygroundBackend locally in order to make it work locally. And once the backend works, edit the base url by the url you are using for the backend.

I think have both JShellAPI and JShellWrapper running but I am getting this error. I am using localhost:8080 as my rest URL

![image](https://github.com/user-attachments/assets/27a664eb-27e6-4e78-9d65-138f10707273)

![image](https://github.com/user-attachments/assets/befbe1af-2c13-456a-a615-30f38d701eb6)

![image](https://github.com/user-attachments/assets/707b15f4-f1fd-4266-ac85-004d355ab28a)

**Comment by Alathreon** [comment]
`curl --request POST --url http://localhost:8080/jshell/single-eval --data '2+2'`
Can you try to run this and tell me if it works ?
Also, I think it should be `http://localhost:8080/jshell`.

**Comment by Andrew1031** [comment]
> `curl --request POST --url http://localhost:8080/jshell/single-eval --data '2+2'` Can you try to run this and tell me if it works ? Also, I think it should be `http://localhost:8080/jshell`.

Nope, didn't work:

![image](https://github.com/user-attachments/assets/868f4abf-8c3d-45e3-aab6-c2dc1b4bf3c9)

Also changed to localhost:8080/jshell and it gave a new error 

![image](https://github.com/user-attachments/assets/ac6c5e47-45dd-4b2c-9a80-e6eae62d20f4)


![image](https://github.com/user-attachments/assets/94e25e9f-a3ed-4409-b1a6-90c5d5fd8c31)

**Comment by Alathreon** [comment]
Ah, maybe `http://localhost:8080/jshell/` with a slash at the end, hopefully it will work.
Sorry, I don't have the exact url under my hand currently, if it doesn't work, I'll get it tomorrow.

**Comment by Andrew1031** [comment]
Thanks! The slash at the end fixed it

![image](https://github.com/user-attachments/assets/c2d7b16c-431d-41f3-8c69-67826b039a87)
