### ISSUE TITLE
`Command` Interface missing a `getUser()` method

### ISSUE THREAD

**Issue by java-coding-prodigy** [Together-Java/TJ-Bot#115]
The `Command` Interface does not have a `getUser()` method, to return the user which ran the command, which it should.
Most likely I am wrong and we don't need this at all, but just in case we do need it, we can create that method.

**Comment by Tais993** [comment]
A command doesn't contain "users"
First of all, we can't store Discord entities so no, ID could happen.
But then it should be "getLatestUserUsedIdLong"
Which still makes no sense.

You don't indivually use commands anywhere besides the CommandHandler, and the CommandHandler receives the event, so you can just do SlashCommandEvent#getUser

You need to give an example use-case

**Comment by java-coding-prodigy** [comment]
Oh I get it now, I thought that a command was something like a `MessageEvent` which is given by a user, but now I realize that the command can be used to do something in other messages.

**Comment by Tais993** [comment]
Totally not, a Command is a Command, it's to *run* the command.
That's  why there's methods to run SlashCommandEvents, ButtonClickEvents and SelectionMenuEvents
If it was a event it would be called something like "CommandEvent"

**Comment by Zabuzard** [comment]
Sounds like this ticket is obsolete and can be closed? (@Tais993 )

**Comment by java-coding-prodigy** [comment]
Yes we could close it.
