### ISSUE TITLE
Unable to Comment on create Pull Requests directly from IntelliJ

### ISSUE THREAD

**Issue by java-coding-prodigy** [Together-Java/TJ-Bot#129]
One is unable to Comment or create Pull Requests directly from IntelliJ because one does not have enough permissions to do so.

While creating a pull-request, this message shows
![image](https://user-images.githubusercontent.com/85149944/133588020-ce91af30-c7f5-4c9f-abf4-107ea4f37495.png)

Meanwhile while, trying to comment on a pull-request or commit.
![image](https://user-images.githubusercontent.com/85149944/133588125-59d5abd3-8831-46dc-967a-39b8aff0daf5.png)

Solving this issue would make it more feasible for us to.

**Comment by illuminator3** [comment]
We won't work on this, since you shouldn't be using IJ to do those things in the first place. I recommend using a tool like GitKraken or doing it directly on GitHub.
