### ISSUE TITLE
Add pull-request template

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#131]
**Is your feature request related to a problem? Please describe.**

Currently, people aren't reading the contributing guide-lines.
By adding certain things in the PR template, a higher chance they'll actually read them.

**Describe the solution you'd like**

Addition of a PR template

**Describe alternatives you've considered**

People to read the contributing guidelines etc, but everyone can forgot that so not a good solution.

**Comment by Zabuzard** [comment]
Merged
