### ISSUE TITLE
TOS and privacy policy

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#139]
**Is your feature request related to a problem? Please describe.**
No privacy policy / TOS

**Describe the solution you'd like**
Creation of privacy policy and TOS 
This also needs to be added to the bot on the [developer portal](https://discord.com/developers/)
This should also be added to the bot's about me section (description in the developer portal

**Comment by Zabuzard** [comment]
I do not think we need or should create one. Discord covers all of that stuff already itself and people explicitly agree to it when joining a server.

Legally its definitely not needed in this case at all. I also dont see a good reason to provide one regardless. And the consequences of providing one that is outdated or legally not fully correct could actually be harmful.

**Comment by Zabuzard** [comment]
Regarding ToS, what terms are you thinking about?

And are we talking about people using our GitHub code for their own bot projects (cause that is covered by the license already) or about using our bot as an user in our server? In which case everything is covered by our server rules already...

**Comment by Zabuzard** [comment]
The problem I see is that you can be held legally responsible if you do it wrong and formalize the text incorrect.

If you find a good template somewhere, we can use it. But if you neither can propose a safe and correct text, nor find any lawyer or something, I would rather not write something than doing it wrong and getting Doppey (as the owner of this organization) or our server into possible legal trouble or getting our server banned by Discord or anything.

At that point it would be Doppeys decision honestly. But maybe you can find some nice template for such a privacy notice.

**Comment by borgrel** [comment]
We dont need to store any user information? or message content
We process events and discard them?

As long as User Id, Member name, etc is never written to the log, we are never storing User content?
So we just need to add Unit Tests for the .log file to make sure User Id etc never appears there and nobody forgets the rule (or never knew about it)

Even if you wish to add persistence (as mentioned in #155) to reconnect to existing bot messages you will only store User ID, message ID and Possibly timestamp and it will be deleted after a short time period. As long as you don't store the member name or message content your not storing any person-ably identifiable information and as long as its getting deleted with a short roll over the data cant even be used for telemetry or heuristics or demographics

**Comment by Zabuzard** [comment]
Fair. Then we will write something.

**Comment by Zabuzard** [comment]
Done and linked in the settings:

![discord settings](https://i.imgur.com/pqXBWI4.png=
