### ISSUE TITLE
Add string-external component ID storage

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#155]
### What is this?

The component ID system that will be introduced by #154 (see `ComponentIDs`, used by `SlashCommandAdapter` and the fairly complex documentation in `SlashCommand`) is quite hard to use for users and has hard and inpractical limitations (mostly the 100 character limit). Also, our Jackson CSV representation seems to mess up some stuff like `;`.

In short, our system tries to store information relevant to a button/selection-menu event inside the component ID (a plain string that is send to JDA), but that has a lot of limitations.

It would be better to store the actual information inside the application (for example a `Map` or the `Database`) and send around an identifier in the component ID instead, for example a `UUID`-string.

### Overview

**The advantages are clear**, the UUID-string itself will never go beyond 100 characters and is easy to handle for everyone. We can store as much and complex information as we want, since it will be held within the application only and not send over JDA and the wire.

**The disadvantages are small** and easy to counter: If the information is stored in-memory, it will be lost upon restart. So buttons that have been created on older instances are stale and the bot can not work with the ID anymore. An easy way to counter that is to (optionally?) additionally offer a persisted memory such as the database to commands.

### User impact

For the end-user, the API will likely be very similar and not change much at all. Unfortunately, we also will not get rid of the problems with the old API - namely that users could just bypass the system, provide their own component ID and break the systems internal routing by that.

There is no way to make this "type-safe" at "compile-time", unfortunately.

**Comment by Tais993** [comment]
Component ids exist to store state, if you want to store data this should be done based on message or something like that.

100 chars are by far enough to store state, the permission required to press the button, the role's ID it gives when pressed and such.


I can write multiple sentences with 100 chars, this issue looks like it's going the wrong way for me
^ 100 chars

Instead we should make an util that helps with storing information based on message.

And this way button information SHOULD be stored within a database.
If we want to ignore a component we SHOULD disable (Component#asDisabled + overriding the old components in the message) instead of just ignoring the component.

**Comment by Zabuzard** [comment]
> 
> 
> > to delete all entries that have not been used for longer than two months
> 
> Note, when we remove the entries we should disable the buttons on the message. So store message ID at all times

The part with the message ID sounds good but I am afraid this is very difficult to implement. And impossible without changing the user interface, sadly.

This would require the user to provide the message id, so `generateComponentId(event.getId(), ...)` or `generateComponentId(event, ...)` and I can not get rid of the _annoyance_ to add this extra parameter, since `SlashCommandAdapter` can not infer the event automatically.

But the bigger problem is locating the `id` back to disable the buttons. There is no general purpose `jda.getEventById(id)`. You would have to also store the text channel id and whether its a text channel or private channel. By that you can locate the message back and then iterate its components to disable the component that expired.

Possible but not perfect.

I think, for a first iteration, I will go with having the buttons enabled still but popping an ephemeral message like _"sorry, this event has expired"_ but put a `// TODO` there to think about some good solutions for another iteration.

**Comment by Tais993** [comment]
People should be able to extend and or implement ListenerAdapter/EventListener.

They should be able to do whatever they want, we should just provide utilities, we shouldn't force them into our system.

**Comment by Zabuzard** [comment]
> 
> 
> > > `generateComponentId(Message, String... args)`? Allows us to handle all of that in the backend
> > 
> > 
> > This is not possible, that is my point. We do not provide a button-creator-facade. Users create the buttons with the JDA methods and we can not interject them to decorate the arguments with automatic event-knowledge.
> 
> It is possible, and by far the best solution
> 
> > Creating such a system would mean to facade most of the JDA API and to make the command system much more involved than it is right now (for example by forcing extension of a class for decoration).
> 
> No? Just adding a message argument is enough
> 
> > Either we make the user-API more ugly by demanding them to give us the necessary detail or we dont go with extra details.
> 
> Resulting in removal of our interface, and people forced into a limited system. Sounds like a bad design choice
> 
> > The best decision is likely to force each user to call the generator with the `event` as argument, then we can extract whatever we need from it. But that will change the user API and imo that is not acceptable right now. There is a better point in time to do this API change.
> 
> No, we should make changes early, not wait till we've lots commands resulting in us having to spend a lot of time refactoring
> 
> > Anyways, I feel like this problem can not be resolved easily now, but I still do see a lot of value in just adding the persistent storage. The details of what exactly is stored and how we react to expiration of IDs can easily be adjusted later on. I am putting that to a second iteration.
> 
> Still disagree, the system is fine, but forcing people to use something that limits them goes beyond my head.

This whole discussions seems pointless without you seeing my actual code. Its basically you saying "oh no, please dont do it like that" and me saying "dont worry, thats not how im doing it". Your concerns have been heard and im not implementing anything that goes against them.

**Comment by Zabuzard** [comment]
> 
> 
> > You are misunderstanding my vision. It is not required to extend `SlashCommandAdapter`. It will still be easy to do everything, including component IDs, yourself by just extending `SlashCommand`.
> > However, we always already required that people have to be added to `CommandSystem` if they want to benefit from the system itself. This will of course remain the same.
> 
> I'm talking about:
> 
> > We already require a very certain and strict format for component IDs and throw "heavy errors" if anyone does not follow it. So nothing changes regarding that. Basically, people are more or less always forced to use our API to create their IDs.
> 
> You're saying here that not using SlashCommandAdapter#generateComponentId causes heavy errors, and that people are forced to use it.
> 
> Or were talking about a different API and different component IDs
> 
> But if you throw heavy errors, custom IDs aren't possible (iirc, events that throw don't get ran again on other EventListeners

It is not necessary to use `SlashCommandAdapter#generateComponentId` from the abstract class. For people who just want to implement `SlashCommand` but still want to be part of our `CommandSystem`, they can use `ComponentIdGenerator#generate`, which `SlashCommandAdapter` uses under the hood and already pre-fills to make life easier for users.

It is obviously necessary to use either if one wants to be part of `CommandSystem`, since this will lookup the DB for a UUID. So the UUID has to be put into the DB eventually (which `ComponentIdGenerator#generate` does (and by that also `SlashCommandAdapter#generateComponentId`).

That said, no one is forcing people to be part of `CommandSystem`. They can just opt-out and add themselves as regular JDA-listener and do whatever they want - we are not closing doors to that. In fact, I am actually encouraging that if one wants to create a command which has needs that `CommandSystem` can not fulfill yet. In parallel, someone else can then work on enhancing `CommandSystem` and afterwards migrating back the global listener, once the system can serve the special needs.
