### ISSUE TITLE
Add log severity highlighting to Logviewer

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#186]
The logs in the logviewer are hard to read because they all just have the same background color:

![plain logs](https://user-images.githubusercontent.com/13614011/137103838-02b02db8-cb4d-44cb-8073-a21a9a04004b.png)

It would help massively if the logviewer could attach some CSS-classes based on the **log severity** and then style them with the CSS accordingly. This also enables users to style them manually easily with plugins such as **Stylish** or **Greasemonkey/Tampermonkey**.

It could then for example look like:

![colored logs](https://user-images.githubusercontent.com/13614011/137104565-1d214565-d283-4d1e-a264-5e7e886f6f09.png)

**Comment by krankkkk** [comment]
Do you want it in the Streamed or the File View?
