### ISSUE TITLE
Consolidate Configuration and Administative Commands

### ISSUE THREAD

**Issue by borgrel** [Together-Java/TJ-Bot#193]
**Is your feature request related to a problem? Please describe.**
As mentioned here: [comment](https://github.com/Together-Java/TJ-Bot/pull/135#issuecomment-922266902)
It will be confusing and needlessly complicated for new users if slash commands contained the configuration options and administrative commands required to make the basic commands customisable for each guild as subcommands.

If we don't provide an existing framework that bundles all of these commands into a single one, then every command will end up looking like this: [pull request](https://github.com/Together-Java/TJ-Bot/pull/135#issue-1000014806)
And instead of 20 commands there will be a huge list and less than half of them will be applicable to the general users, scaring them off after they just keep getting errors when they try use the command system.

**Describe the solution you'd like**
All of these modification commands should be accessed via a single root slash command.
Examples:
`/modify tag create [id]`
`/modify tag raw [id]`
`/modify free add [channel]`
`/modify free status [channel]`
`/modify tex backgroundColour [colour]`

So we need a single slashCommandAdapter that is instantiated before all other commands and gets passed to the other commands when they are instantiated (or provides a static access point) that allows other commands to add sub commands with a consumer to run private code internal to each command adapter.

**Comment by Zabuzard** [comment]
I am not sure I get the motivation behind this. You are basically suggessting to have all commands as subcommands of a single super command instead of having each command its own command.

Or are you talking about subcommand-groups?

**Comment by Zabuzard** [comment]
I am still not sure I get the actual problem. Have you checked the actual **tag-system** proposal? It consists of multiple commands:

* `/tags`
* `/tag <id>`
* `/tag-manage <subcommand> <options>`

So the commands that are used often are extracted into their own commands already.

I do get the direction your request is going though. As in, imagine we have like 100 commands and then its just a jungle to navigate and it should probably be grouped on a higher level by the system into "categories" or something for better navigation.

Unfortunately Discord is pretty bad in providing auto-completion when you type "out of order". So if you for example have a nested command like `/foo bar baz`, you can not just type `baz` and get it suggessted... 😞

So I am not sure if having categories would actually lead to a better UX on the long run. Nor am I convinced that we will end up with a jungle of commands in the first place 🤔
