### ISSUE TITLE
propogating the onReady event

### ISSUE THREAD

**Issue by borgrel** [Together-Java/TJ-Bot#194]
**Is your feature request related to a problem? Please describe.**
Some features will require access to more than slash commands.
(for example, free command requires 'onGuildMessageRecieved' access to monitor channels and automatically mark them as busy when messages arrive)

**Describe the solution you'd like**
The 'onReady' event (which the Bot already handles) needs to be propagated to all commands so that the commands that need more than slash commands have access to the JDA so that can register new listeners for themselves. This will also give commands a required bot just started point for logging successful startup or initial state etc.

**Describe alternatives you've considered**
Passing the JDA via the Commands enum.
Creating Differant types of Adapters for Listeners other than `onSlashCommand` while this will probably eventually happen, it will not be soon and commands would still potentially require the `onReady` event for logging and other things.

**Comment by Zabuzard** [comment]
> Some features will require access to more than slash commands.
Agreed. The idea for now is: create your command and if `CommandSystem` does not serve your needs, do not use it for now and just go "global listener". Once you are done, we can review your exact needs, adjust `CommandSystem` and then migrate your command back into it.

> The 'onReady' event (which the Bot already handles) needs to be propagated to all commands
No problem, can do.

> so that the commands that need more than slash commands have access to the JDA so that can register new listeners for themselves
Not like this. Please add your command in `Application#main` where also `CommandSystem` is added as global listener instead.

> Creating Differant types of Adapters for Listeners other than onSlashCommand while this will probably eventually happen, it will not be soon and commands would still potentially require the onReady event for logging and other things.
Exactly, that is what will happen eventually. Until then, add yourself in `Application#main` as global listener and all good.

**Comment by borgrel** [comment]
> so that the commands that need more than slash commands have access to the JDA so that can register new listeners for themselves
Not like this. Please add your command in Application#main where also CommandSystem is added as global listener instead.

The free command requires both slash commands and other listeners. If it gets instantiated in Application#main then it will not be in Commands#createSlashCommands which means it will need to rewrite all of the Guild#updateCommands logic to get the slash commands registered in the guild.

Or the instance will need to be some horrible singleton or similar to have the instance available to add to the Commands#createSlashCommands  list.

Or the slashCommands will need to be one class and the other listeners will need to be another class leading to the same horrendous singleton problem to make the instance created in Application#main accessible to the instance created in Commands since Application and Commands do not communicate

Or it needs to be passed via CommandSystem meaning modification of Application, Commands, Command System and ReloadCommand requiring the modification of countless constructors and program flow.

All of these options are far more dangerous 'hacks' than late registering a listener inside the onReady event which already has reason to be propagated to all commands

**Comment by Zabuzard** [comment]
> 
> 
> > so that the commands that need more than slash commands have access to the JDA so that can register new listeners for themselves
> > Not like this. Please add your command in Application#main where also CommandSystem is added as global listener instead.
> 
> The free command requires both slash commands and other listeners. If it gets instantiated in Application#main then it will not be in Commands#createSlashCommands which means it will need to rewrite all of the Guild#updateCommands logic to get the slash commands registered in the guild.
> 
> Or the instance will need to be some horrible singleton or similar to have the instance available to add to the Commands#createSlashCommands list.
> 
> Or the slashCommands will need to be one class and the other listeners will need to be another class leading to the same horrendous singleton problem to make the instance created in Application#main accessible to the instance created in Commands since Application and Commands do not communicate
> 
> Or it needs to be passed via CommandSystem meaning modification of Application, Commands, Command System and ReloadCommand requiring the modification of countless constructors and program flow.
> 
> All of these options are far more dangerous 'hacks' than late registering a listener inside the onReady event which already has reason to be propagated to all commands

I get you. I am not saying to not provide `onReady`. I am more trying to find immediate solutions to unblock you until this feature has been pushed.
