### ISSUE TITLE
Create user documentation

### ISSUE THREAD

**Issue by marko-radosavljevic** [Together-Java/TJ-Bot#20]
**Is your feature request related to a problem? Please describe.**

I think we should have clear, informative and user-friendly documentation.

**Describe the solution you'd like**

I would like to create a new repo, under our organization, just for user docs.

The idea is to have a place where you can easily edit the docs, push, and static website gets generated and deployed to github pages. Also tooling that will help maintain it, for example checking if any link is broken. 

**Describe alternatives you've considered**

Alternatives:
- No docs at all - the worst option in my opinion.
-  Github .md files - hard to navigate, and not very user-friendly. 

**Additional context**

I  quickly reviewed multiple solutions for this issue, ranked from best to worst:
  - [mdBook](https://rust-lang.github.io/mdBook/) - free and open-soruce, generates website from .md files, flexible theming support, easy deployment.
  - [Docsify](https://docsify.js.org/#/quickstart) - free and open-source, doesn't generate from .md, theming support, easy deployment.
  - [GitBook](https://docs.gitbook.com/) - not free and open-source
  - [Archbee](https://www.archbee.io/) - not free and open-source

**Comment by Zabuzard** [comment]
We can also create a dedicated branch for Github Pages, no need for an extra repo imo.

I use that often to deploy Javadoc:

- branch: https://github.com/Zabuzard/FastCDC4J/tree/gh-pages
- online at: https://zabuzard.github.io/FastCDC4J

**Comment by marko-radosavljevic** [comment]
Would I be able to have github actions, pipeline, and other automation on that branch? This would be kinda a whole project, I have to build it and everything.

Also, if it's a separate repo, it's easier to work with and a bit cleaner, because there is no other unrelated things in there. I guess other benefit would be separate permissions and settings, that would enable more granular control. And probably easier for people to find the docs and contribute to, because it would have it's own readme and contributing, and much more visibility.

I think new repo is a better and cleaner solution overall.

**Comment by Zabuzard** [comment]
Thinking about it, maybe the Wiki is good enough, already available and easy to use for everyone?
https://github.com/Together-Java/TJ-Bot/wiki

**Comment by marko-radosavljevic** [comment]
Yup, I think this idea is near, but definitely overkill for our use-case, especially at this stage. Closing this.
