### ISSUE TITLE
Create bot tutorial doesnt know bot's current permissions

### ISSUE THREAD

**Issue by borgrel** [Together-Java/TJ-Bot#202]
**Is your feature request related to a problem? Please describe.**
https://github.com/Together-Java/TJ-Bot/wiki/Create-Discord-server-and-bot has a description of how to configure the OAuth for the bot
> 5.2. select the desired Bot permissions, e.g. Send Messages, Read Message History, Add Reactions, Use Slash Commands

But it doesn't tell you what permissions the bot actually needs to function, nor does it point to a URL that is tracking the permissions the bot uses at its current state of implementation.

**Describe the solution you'd like**
We need a way to show new users (and current contributors) what permissions are required (and possibly what features are linked to those permissions

**Comment by Zabuzard** [comment]
The required bot permissions are shown:
![permissions](https://user-images.githubusercontent.com/13614011/137686307-6d671619-3075-446f-b0f6-3183052af016.png)

When the tutorial was written, that was all thats needed. And afaik its still all needed as of today (might change soon though).

**Comment by borgrel** [comment]
well kick command and stuff are currently in pull requests so yes it should change soon. (should commands check if the bot has the permissions it needs on instantiation?)

also, the tutorial may have shown which permissions it needs but what it says is "select the permissions `for example`" so nobody actually knows that those are the permissions needed.

and that is static and nobody will remember to change it when the bot changes which permissions it need and changing the example picture every time seems like serious overkill. we just need a link to a file that dynamically tracks what permissions are currently used (and for what)

**Comment by Zabuzard** [comment]
Id suggest that the bot checks all permissions it needs in the code and callsback if its missing any permissions right during startup (similar to as it reports back during `reload` if it fails). The list of permissions might be read from file or within the code in some utility class whatever. And then the wiki might refer to that.

Comments on such a proposal?
