### ISSUE TITLE
DBot does not have a style

### ISSUE THREAD

**Issue by borgrel** [Together-Java/TJ-Bot#204]
**Is your feature request related to a problem? Please describe.**
Each command will have to generate their own EmbedBuilders (and other entities)
Leading to inconsistency in the output given to users

**Describe the solution you'd like**
We need a way for commands (and other bot code?) to request the output generating entities supplied by the API from a common source so that they stay consistent in look and feel.

**Comment by Zabuzard** [comment]
Can you elaborate on this suggesstion? I do not see the problem yet. And why you think that we need a common L&F.

Not every command wants to report back with embeds and commands may also want to use different colors in embeds, if they choose to use embeds. Apart from the color, there is not really much to configure. See #135 for some code examples of using embeds.

**Comment by Zabuzard** [comment]
> 
> 
> https://raw.githubusercontent.com/DV8FromTheWorld/JDA/assets/assets/docs/embeds/01-Overview.png
> 
> (On phone, can't display images)
> 
> Footer text with a link to this repo and who ran this command, default timestamp, color?
> 
> No-one is gonna spend a lot of time reading other people their code just to get an embed style.

Again, we already have an embed builder that provides a setting for this. You give it the user who ran the command, a color you want, ... and it puts the timestamp there and everything. See #135 .
