### ISSUE TITLE
bug. this cast is unsafe. i explained this to you already and you just silently ignored it.

### ISSUE THREAD

**Issue by RealYusufIsmail** [Together-Java/TJ-Bot#209]
bug. this cast is unsafe. i explained this to you already and you just silently ignored it.

casting a long into an int will overflow and silently ignore the issue. instead, you have to check before you cast whether the long is in the range of int. and if not, throw an error message actively.

_Originally posted by @Zabuzard in https://github.com/Together-Java/TJ-Bot/pull/196#r731556495_

I will fix this issue today or tomorrow

**Comment by Zabuzard** [comment]
But not in a new issue. Fix it in the original PR. Closing this.
