### ISSUE TITLE
Poll test

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#21]
Test

/polls "Foo" "Bar" "Baz"

**Comment by Zabuzard** [comment]
Weird, doesnt seem to work.

Alternative, generated manually at: https://app.gh-polls.com/

[![](https://api.gh-polls.com/poll/01FEY4X5E9W0MS8SV37812VYZN/foo)](https://api.gh-polls.com/poll/01FEY4X5E9W0MS8SV37812VYZN/foo/vote)
[![](https://api.gh-polls.com/poll/01FEY4X5E9W0MS8SV37812VYZN/bar)](https://api.gh-polls.com/poll/01FEY4X5E9W0MS8SV37812VYZN/bar/vote)
[![](https://api.gh-polls.com/poll/01FEY4X5E9W0MS8SV37812VYZN/baz)](https://api.gh-polls.com/poll/01FEY4X5E9W0MS8SV37812VYZN/baz/vote)

**Comment by Zabuzard** [comment]
Lmao, I can vote as often as I want...

**Comment by d3vel0per** [comment]
May be because of this: https://github.com/evenchange4/gh-polls-bot/issues/26#issuecomment-701514560

**Comment by Zabuzard** [comment]
Another test

/polls "Foo" "Bar" "Baz"

**Comment by Zabuzard** [comment]
All of the bots and apps dont seem to work. GitHub API likely changed.
