### ISSUE TITLE
Abuse of Objects#requireNonNull

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#211]
**Is your feature request related to a problem? Please describe.**
Abuse of `Objects#requireNonNull` causing unreadable code making it a lot harder to debug simple things

`Objects#requireNonNull` has been created with the intention of parameter validation.
Not variable validation (with a reason, called readability and debuggability).

**Describe the solution you'd like**
Removal of ALL `Objects#requireNonNull` only exception is method references OR replace with `Objects#requireNonNull(T, String)`

**Describe alternatives you've considered**
Buying new glasses, but too expensive
Having a harder time debugging and reading code

**Additional context**
To elaborate on this issue.

When we ignore a "possible null" warning, we can get a NPE.
In this NPE they tell us **what** null is.

If we make usage of `Objects#requireNonNull`
We get a *NPE*, correct, the thing that we want gone.
And the NPE **doesn't** tell us **what** null is.

So, what to do instead?
We make usage of `Objects#requireNonNull(T, String)` instead
By providing the variables name as a message, we instantly know what's null

While I still think it's ugly having all these NotNull methods, they make code really unreadable.
At minimum, this improves debugging *a lot*, you instantly know what's null, so you don't even have to debug.

The best improvement would be to actually add if statements checking or variables are null, this keeps the code a lot more readable.

The best solution is the simplest one, just letting the NPE trigger.
- instantly tells you what's null
- no added code making it harder to read

This clearly is the best of both combined.
The only thing is warnings, those will be there a lot

Honestly, why do code smell checkers accept Objects#requireNonNull? It's the biggest smell ever, it's only use-full when it's a method reference.

**Comment by Zabuzard** [comment]
Very fruitful discussion, should now lead into creation of a concrete GH issue with the planned action.

Hence, closing this discussion for now.
