### ISSUE TITLE
Add unit tests for the tex command

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#214]
We recently merged command unit testing utilities.

That being done, we should now add unit tests for the `tex` command to increase our test coverage.

The `tex` command is not particularly well suited for testing, since the API returns an image that we can not really validate. However, we can still validate that we get valid or invalid responses for good or bad inputs accordingly, which is better than nothing.

**Comment by Zabuzard** [comment]
This is actually still relevant, and a "good first issue", it should be kept open.

**Comment by DennisvPutten** [comment]
@Tais993 Hey! Can you assign me? :)

**Comment by Tais993** [comment]
Assigned! Good luck

**Comment by DennisvPutten** [comment]
@Tais993 Haven't been able to get the project working yet. Posted the error message several times in the bot channel, but no one knows. I keep trying solutions. Sorry it takes so long.

**Comment by Tais993** [comment]
What's your username in Discord?

**Comment by DennisvPutten** [comment]
Denniss#3454

**Comment by Zabuzard** [comment]
@DennisvPutten any news on this? Still need help? Can you repost in `tj_bot_help` please?

**Comment by Heatmanofurioso** [comment]
Note from a discussion in #397 

We should ensure that we add unit  tests to ensure that the various regular expressions get tested.
Such as matching `$`, but not matching escaped dollar signs `\$`

No need for it to be integration tests, so they should be in a separate class from the unit tests

**Comment by Zabuzard** [comment]
Due to no response, I changed the assignees. @IslamSakrak Feel free to start :)

**Comment by Zabuzard** [comment]
Tested it during the original PR that shipped it.
