### ISSUE TITLE
Community moderation tools

### ISSUE THREAD

**Issue by java-coding-prodigy** [Together-Java/TJ-Bot#216]
**Is your feature request related to a problem? Please describe.**
A system for the warn, mute and ban commands.

**Describe the solution you'd like**
We could make the commands so anyone can mute/warn/ban, but a moderator will have the option to either approve or disapprove the warn. For some common reasons, we could also display a message to the user saying what they did, why they shouldn't have done so, etc.

**Comment by Zabuzard** [comment]
The planned UX on this is not really fleshed out and sorta conflicts the current setup with Staff Helpers. As of now, there is no real benefit and the discussion did not reveal anything else. Closing for now.
