### ISSUE TITLE
Add a report command

### ISSUE THREAD

**Issue by RealYusufIsmail** [Together-Java/TJ-Bot#219]
If a user wants to report something they can do `/report @user-to-report reason`. Then the mods can check it and then they will decide if they should take further cation. To view the reports they can do `/report page-number(optional)` and they will get the reports. In one page there will be 10 reports and the mods can press a next button to move on to the next page.

**Comment by Zabuzard** [comment]
@RealYusufIsmail Could you please stop the "moderation" of issues and PRs. This issue is relevant and should not be closed. Reopening.

**Comment by Taz03** [comment]
@DevSerendipity whats the progress on this one?
