### ISSUE TITLE
Display tags in alphabetical order. 

### ISSUE THREAD

**Issue by java-coding-prodigy** [Together-Java/TJ-Bot#240]
**Is your feature request related to a problem? Please describe.**
The `/tags` command currently displays tags in an order that is not alphabetical, maybe random, maybe based on date added.
This makes it difficult for users to find a tag.
**Describe the solution you'd like**
We display the tags in an alphabetical order.

**Additional context**
![image](https://user-images.githubusercontent.com/85149944/139620442-84ee3a46-ce06-41c8-a04a-c578869326d7.png)

**Comment by Zabuzard** [comment]
What about having a proper list instead? Like with bullet points. One command per line.
Or at least having proper spacing. Its much harder to read a text like
```java
abc, d, e, fg, h, ij
```
than something like
```java
abc, d, e
 fg, h, ij
```

**Comment by java-coding-prodigy** [comment]
Is this alright? 
![image](https://user-images.githubusercontent.com/85149944/139820897-56996211-ca60-4b7a-89bf-870db451575e.png)

**Comment by Zabuzard** [comment]
Yeah but whats the limit? What if there are 100 tags, when does it break, when does it reach "message length" limits or similar? Please try it out. Hence the idea with aligned table columns.

**Comment by Zabuzard** [comment]
Waiting for someone to figure out when Discord starts complaining about messages like:
```java
* foobar
* foobar
* foobar
* foobar
...
```
how many entries can we display until hitting the line limit when repeating this exact pattern?

**Comment by IslamSakrak** [comment]
I am working on this right now, currently implemented the bullet points

**Comment by IslamSakrak** [comment]
Trough investigating more about the issue, there is a limit of 295 lines, and a description limit of 4096 characters

Containing

* foobar [each foobar numbar] (0-295)

**Comment by Zabuzard** [comment]
> Trough investigating more about the issue, there is a limit of 295 lines, and a description limit of 4096 characters
> 
> Containing
> 
>     * foobar [0-295]

Also, we learned that we get an exception when trying to exceed the limit. Its not even send and then cut by Discord or anything. Good learnings.

**Comment by Zabuzard** [comment]
@borgrel suggested that we can also just attach multiple embeds to the message. each containing up to 200 tags. that way the limit shouldnt be an issue for us anymore.

**Comment by Tais993** [comment]
> Trough investigating more about the issue, there is a limit of 295 lines, and a description limit of 4096 characters

There is no line limit, there only is a character limit like I mentioned in the Discord.

**Comment by IslamSakrak** [comment]
- I will just get tagSystem.getAllIds() add them to a list and output it 
so that would solve the new lines

- I can look into sorted() or some other method to sort them alphabetically

- create an if block before it crosses 200 to do get some warning in (il have to look more into logger to do that) 

- I can see to get the character max from jda using this  
` https://www.tabnine.com/code/java/methods/net.dv8tion.jda.core.EmbedBuilder/length`
  
- I can measure the size of our message by getting the content raw and checking the size 

- Cutting could be showed but we could add a button, that would send another embed with the rest of the tags

This is just the raw outline of the plan

**Comment by Zabuzard** [comment]
Sounds good. But seriously, you can just skip the complex part at the end and split it into two issues. Prefer shipping small things. Otherwise this good feature might be delayed for many weeks until the more complex (but not that important) part is finished... That would just be unecessary.
