### ISSUE TITLE
VC activity command UX - Add application name

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#242]
The vc activity command text is lacking the name of the actual activity started. This is kind of confusing for others since they do not know what they will join in when clicking.

The command should mention the name of the activity and not just an id.

![akvKddi](https://user-images.githubusercontent.com/13614011/140027173-611ef6f9-e09f-4ee9-ab87-2868050b7dc1.png)

**Comment by ReyhanPatria** [comment]
Hi! I'm relatively new to contributing, I think is issue would be a great issue with a bit more code involved. I'd like to work on this if you'd assign it to me, thanks!

**Comment by Tais993** [comment]
Forgot to assign myself when I started working on it, so I finished it already.
If you want to, you can still implement it and I'll close my PR

**Comment by ReyhanPatria** [comment]
Ah I see, it's quite alright, no need to double unnecessary work if it's already done.

**Comment by Tais993** [comment]
So, you want this commands purpose to be like it starts a public event?

Currently, it's purpose is to just start an event, for the author.
So if the author wants to share it, they may share it.

Instead, you want it to be like a public event started, where everyone should join?

**Comment by Zabuzard** [comment]
> 
> 
> So, you want this commands purpose to be like it starts a public event?
> 
> Currently, it's purpose is to just start an event, for the author. So if the author wants to share it, they may share it.
> 
> Instead, you want it to be like a public event started, where everyone should join?

At least I thought thats the purpose of the command, yeah. Might be wrong but isnt that like the biggest use case?

**Comment by Tais993** [comment]
I never looked at it in that way no, I'd say we ask for other people their opinions on what to do.

**Comment by Zabuzard** [comment]
I am going to split this into two issues to not block ur PR anymore

**Comment by Zabuzard** [comment]
Opened #247
