### ISSUE TITLE
Introduce the AFK command (from Dyno)

### ISSUE THREAD

**Issue by java-coding-prodigy** [Together-Java/TJ-Bot#258]
**Is your feature request related to a problem? Please describe.**
Dyno's AFK command sets a users AFK status and whenever they get pinged Dyno would interject saying the user is afk

**Describe the solution you'd like**
We create an AFK command similar to them.

**Comment by Zabuzard** [comment]
Please describe this feature in more detail. Is it for voice chat or what?

And why do we want AFK in the first place? I have never seen us using such a feature. It is also not on the list of commands to migrate, is it?

**Comment by java-coding-prodigy** [comment]
It is one of Dyno's command, it is not used here at all but we could use it sometimes.

**Comment by Zabuzard** [comment]
> 
> 
> It is one of Dyno's command, it is not used here at all but we could use it sometimes. you can read [this](https://wiki.dyno.gg/en/modules/afk)

Interesting. I do not feel it is useful for us though. Maybe discuss in tj_suggesstions first. In any case, not really a "migrate existing commands" task, since this is mostly representing the commands we actually use.
