### ISSUE TITLE
Change normal message to embed

### ISSUE THREAD

**Issue by RealYusufIsmail** [Together-Java/TJ-Bot#264]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Instead of having the errors being sent as a normal message sending them as an embed would be better because it would be easer to read and have more customisation.
**Describe alternatives you've considered**
Replacing all the empirical normal messages with embeds

**Comment by Zabuzard** [comment]
I do see an advantage in having plain messages for error messages and other ephemeral stuff: It is easier for the user to differentiate the final success message from the error messages on first glance, due to the different style.

**Comment by Tais993** [comment]
Show examples of why it's look better.

I do agree with Zabuzard, there's plenty of times not using embeds is nicer.

If it's a long message, in general an embed would be nicer though, but that's not the case for most (if not any) errors
