### ISSUE TITLE
JDA optionals

### ISSUE THREAD

**Issue by borgrel** [Together-Java/TJ-Bot#266]
**Is your feature request related to a problem? Please describe.**
Almost all of the JDA methods have some form of return null.

Every single contributor is manually mapping those nulls to Optionals in their own way in their specific code. leading to a lot of duplication and inconsistent design.

**Describe the solution you'd like**
We need a Util library what wraps those methods and replaces them with with optionals as the return values.

**Comment by Zabuzard** [comment]
Duplicate of #211 ?

**Comment by borgrel** [comment]
Dont think so?

that one is about throwing exceptions and making the exceptions thrown more meaningful and cinsistant

this is about streamlining method calls and making functional style more relevant for rest actions

while optionals would slot easily into the call chain before the requiresXXX methods.
The requires calls would break the functionality of optionals

**Comment by Zabuzard** [comment]
The solution we came up with in #211 is to add a helper/wrapper for `JDA`, `Event` and similar to offer `requirerUser` and similar methods instead of returning `null`.

The suggesstion of this is to do the same, but offer `Optional`, right?
