### ISSUE TITLE
How to host the bot (VPS)?

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#27]
In order to have a running bot, we need some sort of server where it can run on.

The server must be stable and accessibly by at least all moderators. All moderators (maybe also Staff Helpers) have to be able to trigger deployments on the server. Maybe even with test environments.
For that, we need some sort of CI/CD as well (more about that in a different issue).

Anyways, we have to decide the details of where to host our bot and who is going to pay for it (if its not free) and how to setup the access permissions.

Hetzner has been mentioned as VPS provided and afaik @Doppeey wanted to pay (?):

![Hetzner plans](https://user-images.githubusercontent.com/13614011/132258245-d749fe0c-3a4f-4b99-b76a-0c4ac037b20d.png)

**Comment by AzatothTheAwakened** [comment]
> The server must be stable and accessibly by at least all moderators
Hetzner does a great job at this by providing a management out of the vps, you can add other Hetzneraccounts as admins etc so that the sole server management is not just reliant on one person.

**Comment by Zabuzard** [comment]
Hetzner VPS integration is currently ongoing (@I-Al-Istannen). Closing this decision poll.
