### ISSUE TITLE
Slash Commands are not replicable

### ISSUE THREAD

**Issue by borgrel** [Together-Java/TJ-Bot#275]
**Is your feature request related to a problem? Please describe.**
People ask for help and helpers show them tags which explain what they need to know. These same people then go and use the same commands to help other people.

This is how all bots work in all platforms. People see it being used and then they duplicate it.

Unfortunately when u use the command `/tag mooc` all that is shown to the user is `george used /tag`. So they will be unable to repeat the action for the benefit of others.

**Describe the solution you'd like**
Hopefully we can make the command show the sub commands too, not just the top most value.
Otherwise we need to include the tag in the embed footer perhaps.

---
**Proposal**

We add an explaining string to the footer, like:
```
illuminator3 * used /tag id:foo * Today at 7:21 PM
```
Maybe there is also a better location for this, feel free to experiment with the UX and propose slight changes.

For now, it will be enough to only add this to the `/tag` command, i.e. `TagCommand.java`. Other commands are not that user-facing. Maybe also `/tex`.

If possible, we could invest into a solution that targets all "user facing commands that respond with embeds", maybe by having a specific embed generator class/method that they will use (there is already `MessageUtils#generateEmbed`). But I am unsure whether this can be made abstract enough so that everyone will actually also use it.

**Comment by illuminator3** [comment]
You can hover over the blue part.
![image](https://user-images.githubusercontent.com/48388251/142914859-23a3fccc-e7b1-48f9-bb99-928fcd0af992.png)

**Comment by Tais993** [comment]
While the full command is visisble, I think we should still display the tag's name in the title.

**Comment by Zabuzard** [comment]
Maybe in the footer. `"illuminator3 * used /tag id:foo * Today at 7:21 PM`?

@borgrel Does that sound good? Can convert this to a "good first issue" then.

**Comment by borgrel** [comment]
that should work, we will just have to try and see if ppl notice it or ask 'how did u do that'

**Comment by IslamSakrak** [comment]
Currently working on this issue, could I be assigned to it?

**Comment by Zabuzard** [comment]
> Currently working on this issue, could I be assigned to it?

Sure, enjoy! :)
