### ISSUE TITLE
Remove title from mod audit log

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#279]
The mod audit log messages have a **title**, but it interrupts the read-flow, since its displayed in between the author and the message. As in, it reads as _"John Message Deletion deleted messages from Bob"_ instead of _"John deleted messages from Bob"_.

![example](https://i.imgur.com/k6siJM4.png)

To increase UX, I would simply **remove the title all together**. Alternatively, we could also move the title part into the **footer**, up to be decided by who implements this.

**Comment by AdrianAcostaPR** [comment]
Hello @Zabuzard - I'd like to be assigned and work on this issue and give it a try if no one is currently working on it. 

Thanks!

**Comment by Zabuzard** [comment]
> Hello @Zabuzard - I'd like to be assigned and work on this issue and give it a try if no one is currently working on it.
> 
> Thanks!

Sure thing, enjoy! 😄

**Comment by Zabuzard** [comment]
@AdrianAcostaPR Are you still working on it? :)

**Comment by AdrianAcostaPR** [comment]
Hey @Zabuzard - unfortunately I've been bombarded with work from my job (programming as well).  I haven't really been able to get to this.  If you want I can go ahead and unassigned myself so someone can take over.  Please accept my sincerest apologies for any inconvenience this may cause.

**Comment by Zabuzard** [comment]
> Hey @Zabuzard - unfortunately I've been bombarded with work from my job (programming as well). I haven't really been able to get to this. If you want I can go ahead and unassigned myself so someone can take over. Please accept my sincerest apologies for any inconvenience this may cause.

No worries, all fine. Just keep us up-2-date, then planning is easier, thanks :)
