### ISSUE TITLE
Mod audit doens't log who issued moderation command

### ISSUE THREAD

**Issue by marko-radosavljevic** [Together-Java/TJ-Bot#280]
**Is your feature request related to a problem? Please describe.**

After using moderation commands of our bot, audit doesn't log who issued the command.
![image](https://user-images.githubusercontent.com/30927961/143237922-47693153-27c5-4521-8d00-1199c3856c88.png)

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/30927961/143239147-980f530d-eabc-4b96-9a74-ce255d3745af.png)
Or some other way to indicate who issued the command. :relaxed:

**Comment by Zabuzard** [comment]
Note that this is only "easy" to do if it came from our own bot actually. Right now we read the information from the audit log, but Discords audit log has no additional information.

So the way I see this feature being implemented is:
* have a database table that lists all sanctions done with our bot, with timestamp (will likely be introduced by a `/audit` command anyways (not sure if we have a GH issue for that already))
* lookup the ban in the audit log with the timestamp in that table (probably have to give it some variance of +-5 seconds or similar to find a match)
* decorate the message written to the channel with the information gathered from the database

**Comment by Zabuzard** [comment]
Blocked by the missing audit database table, which also blocks the work on temporary bans and the mute command right now.

**Comment by Zabuzard** [comment]
Created an issue for it, blocked by #297
