### ISSUE TITLE
Log tag changes

### ISSUE THREAD

**Issue by marko-radosavljevic** [Together-Java/TJ-Bot#281]
**Is your feature request related to a problem? Please describe.**

Managing tags (creating, editing, deleting) is done on the discord. It's not under version control, and we do not know who issued tag managing command.

And since a lot of people have permission to manage tags, it would be nice to be able to audit the changes, and revert in case tag gets accidentally deleted or similar. 

**Describe the solution you'd like**

Every `/tag-manage` to be logged in `#mod_audit_log`, so we can know who edited the tag, when, and what are the changes being made.

**Comment by MaiTheLord** [comment]
I'll start working on that

**Comment by Zabuzard** [comment]
> I'll start working on that

Awesome, enjoy! If you have any questions, feel free to ask either here or in the Discord server 😃

**Comment by Zabuzard** [comment]
Design-wise, I would maybe create a separate class that offers a method to write arbitrary messages into the log channel. And then let the tag manage command class take an instance of that class and use the method there, whenever the tags are changed.

Not sure whether the existing mod routine class would be much of a help here honestly, it has a completely different purpose and flow. But I still feel like all mod-log actions should be near to it, at least in the same package. Hence why I would just create some `ModAuditLogWriter` class or similar there and give it a method log `public void logMessage(String message)` which others can then use.

**Comment by MaiTheLord** [comment]
should the bot log the action instantly, or wait for the routine?

**Comment by MaiTheLord** [comment]
do we need to log it when someone uses `/tag-manage raw`?

**Comment by MaiTheLord** [comment]
also, does it need to show the content of the tag when using `create` etc' and/or the old content when using `edit` etc'?

**Comment by Zabuzard** [comment]
> Should the bot log the action instantly, or wait for the routine?

Yeah, just dont connect this code to the routine at all. Imo they dont have anything to do with each other.

> do we need to log it when someone uses /tag-manage raw?

No. Just the once that actually change something: create, edit, delete, ...

> also, does it need to show the content of the tag when using create etc' and/or the old content when using edit etc'?

Yeah, this is actually crucial to be able to "revert" accidental changes. It has to log the state **before** and **after** the change. I would suggest to just attach them as "file" to the embed, like a `before.md` and `after.md` file or similar.

**Comment by MaiTheLord** [comment]
> I would suggest to just attach them as "file" to the embed, like a `before.md` and `after.md` file or similar.

the thing is, when I attach the file to the embed it puts the file before the embed. I think that sending the files in different messages is the way to go.

**Comment by Zabuzard** [comment]
> The thing is, when I attach the file to the embed it puts the file before the embed. I think that sending the files in different messages is the way to go.

If you say so - your feature, your design 👍 If you need feedback, show some screenshots 👌

**Comment by java-coding-prodigy** [comment]
https://github.com/Together-Java/TJ-Bot/issues/281#issuecomment-985415973
you could have 2 other embeds, one for before and one for after. Embeds are always in order luckily.

**Comment by MaiTheLord** [comment]
Good to know, but I can't see how is that better than sending different messages.

**Comment by MaiTheLord** [comment]
What do you think?
![image](https://user-images.githubusercontent.com/63251610/144595520-10ca78e2-7e20-4117-acc8-d0d1067088cb.png)

**Comment by Zabuzard** [comment]
As long as it clears that it belongs together, I do not care that much.

Be aware though that ideally you create a solution that cant be "interrupted" by other concurrent logs. So if you write independent messages, another log could be written in between, concurrently. Which would be super confusing, I guess.

So if there is a solution that has the stuff grouped together ("status message", content before, content after) and does not look shit, I would prefer that.

**Comment by MaiTheLord** [comment]
So I've researched a bit more about putting the attachments after the embed and there's no proper way to do it. the only way I can think of to make sure nothing interrupts it between the messages is to use some kind of lock, but then (obviously) we have to instruct developers to always use it when sending messages in the `#mod_audit_log` channel.

**Comment by marko-radosavljevic** [comment]
Would ask @Tais993, our JDA expert, for opinion and tips on this. ^^

**Comment by Tais993** [comment]
I saw him asking for help in the JDA Discord :p, and he's unfortunatelly correct.

There's no way of putting the attachment before the embed, so an unfortunate situation.

I'd honestly make a second channel for logging tag changes, easiest solution?

Otherwise you'll have to lock or accept that a message comes in between, unfortunately.

**Comment by MaiTheLord** [comment]
> I'd honestly make a second channel for logging tag changes, easiest solution?

@Zabuzard, @marko-radosavljevic, what's your opinion?

**Comment by Zabuzard** [comment]
Could you show how it looks like if you put the attachments together with the message? I am not sure I understand why you think it looks "bad".

However, I definitely want to avoid introducing locks or similar, such a setup would be far too fragile in my opinion. In such a case I would probably rather accept the risk of the message being interrupted, but change the title of the attachments so that its clear to which event they belong to.

**Comment by MaiTheLord** [comment]
I would obviously make it `synchronize`d if we would use the multiple message approach.
this is what it looks like on a single message, I assume you can see whats the problem with it.
![image](https://user-images.githubusercontent.com/63251610/144660111-e5744b72-1d76-4acb-ba28-ace36a9744c4.png)

**Comment by Zabuzard** [comment]
In my opinion that is okay, really. It is just a log after all and also doesnt happen often. The channel is also restricted to a small audience.

Discord also cuts down the size of those files if they are really large, right? Is it possible to disable the text preview maybe? (also make sure u name those "files" with `.md` to get the syntax highlighting)

**Comment by MaiTheLord** [comment]
> Discord also cuts down the size of those files if they are really large, right?

yes, it cuts the vertical size of the file preview, but the horizontal size expands as much as it can.


> Is it possible to disable the text preview maybe?

I am pretty sure that's impossible. we can make them show as a spoiler but it won't change the size of the preview.
![image](https://user-images.githubusercontent.com/63251610/144709505-29b0dafc-dff3-486b-a13c-1a5ab4018f3e.png)
I think I prefer it to send as different messages, maybe with a spoiler

**Comment by Zabuzard** [comment]
>  I think I prefer it to send as different messages, maybe with a spoiler

@marko-radosavljevic your opinion on this?

I think the spoilers are actually worse.

I am voting for **same message, no spoilers** - I do not care if its above or below or whatever, as long as its clear that its one message containing of 3 things that belong together.

**Comment by marko-radosavljevic** [comment]
Yup, same with me, it's not something we would use extensively, doesn't need to have a perfect UX.

Like Zabu said, above or below, doesn't matter. It's important that it is consistent, so we can always read it the same way, without getting confused and having to track down before and after. And it should be accurate, so we can depend on it. Everything else is just cosmetics. So yeah, I'm also voting for same message, no spoilers. :relaxed:

Thanks :heart:

**Comment by MaiTheLord** [comment]
no problem, as you wish :)

**Comment by Zabuzard** [comment]
Development on this is still ongoing and we want it (@MaiTheLord )
