### ISSUE TITLE
Fix YouTube Together not working in the VC-activity command

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#283]
**Describe the bug**
Picking the YouTube Together choice causes a error in the client on desktop.
"Invalid choice"

**Expected behavior**
The choice to be accepted

**Solution**
See the issue [here](https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/commands/basic/VcActivityCommand.java#L48)
It has a trailing space, which didn't cause issue before (that's why it was never noticed.
But the (desktop) Discord client changed something which does cause issues now

Thus the trailing space must be removed, resulting in `YouTube Together`

**Comment by NAMANIND** [comment]
> @Tais993 Hello 👋🏻, please assign this work to me this would be my first pr and first open source contribution.

**Comment by illuminator3** [comment]
> > @Tais993 Hello 👋🏻, please assign this work to me this would be my first pr and first open source contribution.

I assigned you to this issue.
