### ISSUE TITLE
Make log path configurable, disable http logger if no target is set

### ISSUE THREAD

**Issue by I-Al-Istannen** [Together-Java/TJ-Bot#287]
**Is your feature request related to a problem? Please describe.**
Using one Logviewer instance for two bots currently isn't possible, as the log paths are the same and both bots would write to the same file. Additionally, only one bot can stream logs and the other one should be disabled gracefully.

**Describe the solution you'd like**
Make the log path configurable via an env var, fall back to `logs/app.log` if none is set. Disable the http appender if no log target is set via env var.

**Describe alternatives you've considered**
- Support multiple streams (more work and doesn't solve the name clash problem)
- Multiple logviewer instances (needs more resources)

**Comment by krankkkk** [comment]
I would advice splitting this into 2 different PR's.
1. Implements the Changes for the Async HTTP-Appender
2. Makes the Logviewer compatible for multiple sources
