### ISSUE TITLE
Create "dad joke" listener

### ISSUE THREAD

**Issue by illuminator3** [Together-Java/TJ-Bot#288]
**Is your feature request related to a problem? Please describe.**

The server is lacking dad jokes.

**Describe the solution you'd like**

Automatically respond with "Hi X I'm dad" to "I am X [...]" messages.

**Additional context**

Make TJ great again.

**Comment by Zabuzard** [comment]
Where should it get its data from, is there some sort of dad joke API?

**Comment by Zabuzard** [comment]
Are you saying this should listen to all messages (no slash command whatsoever) and respond to any message of the form "I am X ..." with "Hi X I'm dad"?

Sounds very disturbing and annoying as it might trigger often accidentally. For example when writing "I am not feeling well today" - "Hi not feeling well today I'm dad".

Voting to close unless you propose an actual meaningful design for this.

**Comment by illuminator3** [comment]
> fun fact, @illuminator3 made this comment shortly after cracking a dad joke himself. ![image](https://user-images.githubusercontent.com/85149944/144247810-389f3b03-53a4-4dbc-bb06-24227ef27b17.png)

I did not. This issue was opened 16 hours ago.

**Comment by java-coding-prodigy** [comment]
Well, I thought you made the issue then but then realized that it was made 16 hours ago, but the comment was made after your joke
