### ISSUE TITLE
VC Activity command crashes

### ISSUE THREAD

**Issue by illuminator3** [Together-Java/TJ-Bot#300]
**Describe the bug**
The vc activity command crashes when the max-age exceeds about 1 million.

**Screenshots**
![image](https://user-images.githubusercontent.com/48388251/144701917-2f0554c3-f501-4a4a-90bf-7053e2c76d52.png)

--- 

This could be fixed by, for example, implementing a max value for the max-age.

**Comment by Zabuzard** [comment]
Afaik JDA even supports max values in options with the newest version, no? @Tais993

**Comment by Tais993** [comment]
Correct.

And the error message Discord displays got drastically improved a few days ago, so they're worth using now.

**Comment by Zabuzard** [comment]
Nice, then we can just use that instead of doing our own limit check. Perfect. Design/approach for this issue should be clear then.

**Comment by RealYusufIsmail** [comment]
What should the limit be.

**Comment by Zabuzard** [comment]
> What should the limit be.

Whats its unit? Days, minutes, seconds? Something else? I think we are fine with max 1 month, maybe 1 year 🤷 But we definitely do not need more than that.

**Comment by RealYusufIsmail** [comment]
Its in days

**Comment by RealYusufIsmail** [comment]
So the max is 365 days

**Comment by Zabuzard** [comment]
> Its in days

Well then, roll with `365` I would say 👍

**Comment by Tais993** [comment]
Not sure where the 365 days came from.

But the correct answer is 7 days, see [discord docs](https://discord.com/developers/docs/resources/channel#channels-resource)

Didn't see a constant for it in JDA, will check again when I have access to my pc.


My fault for not checking this originally with the PR, luckily we've others to test things :p

**Comment by RealYusufIsmail** [comment]
I will change it to seven days

**Comment by RealYusufIsmail** [comment]
> Not sure where the 365 days came from.
> 
> But the correct answer is 7 days, see [discord docs](https://discord.com/developers/docs/resources/channel#channels-resource)
> 
> Didn't see a constant for it in JDA, will check again when I have access to my pc.
> 
> My fault for not checking this originally with the PR, luckily we've others to test things :p

why is the age in seconds

**Comment by Tais993** [comment]
This issue isn't the place for that, create a new issue for that

**Comment by RealYusufIsmail** [comment]
Anyways so what should the max be

**Comment by RealYusufIsmail** [comment]
604800 seconds since that is how many seconds there is in a week.

**Comment by Tais993** [comment]
Did you take a look at the Discord documentation I send?

It can be found there, that's what the limit should be.

**Comment by Zabuzard** [comment]
Its kinda bad UX to expose a second duration to the user. Thats not really nice to use.

I am not sure why you created it as seconds in the first place but honestly, change it to hours maybe. Or introduce a choice so that the unit and value can be picked as 2 separate inputs and then convert it in the code to the unit you actually need.

**Comment by RealYusufIsmail** [comment]
> Its kinda bad UX to expose a seconds duration to the user. Thats not really nice to use.
> 
> I am not sure why you created it as seconds in the first place but honestly, change it to hours maybe. Or introduce a choice so that the unit and value can be picked as 2 separate inputs and then convert it in the code to the unit you actually need.

https://github.com/Together-Java/TJ-Bot/issues/304

**Comment by RealYusufIsmail** [comment]
> Did you take a look at the Discord documentation I send?
> 
> It can be found there, that's what the limit should be.

I cant find it

**Comment by Tais993** [comment]
My bad, though it was a direct link.

See [here](https://discord.com/developers/docs/resources/channel#create-channel-invite)

**Comment by RealYusufIsmail** [comment]
> My bad, though it was a direct link.
> 
> See [here](https://discord.com/developers/docs/resources/channel#create-channel-invite)

Thank you

**Comment by Budbomber** [comment]
Is this issue currently open still? Tried to reproduce, however when inputting the same number as illuminator, Bot pops up and says activity has ended.
![image](https://user-images.githubusercontent.com/71235266/149257910-ce1b5f44-c16a-453c-a41d-7c31af2b2647.png)

**Comment by Zabuzard** [comment]
Sure thing, enjoy! :)

**Comment by Budbomber** [comment]
So as you can see, I'd added a pull request, (first one!) Is there a better way I could have fixed this issue?
