### ISSUE TITLE
Create an Audit Command

### ISSUE THREAD

**Issue by RealYusufIsmail** [Together-Java/TJ-Bot#301]
**Is your feature request related to a problem? Please describe.**
This will used to store informations such as bans, kicks and more. This will be useful since a mod can check why the user was banned or kicked for example

**Describe the solution you'd like**
This command will be done by doing `/audit @user` for example on which the bot will show there actions

**Comment by RealYusufIsmail** [comment]
Blocked by #298 and #249.

**Comment by Zabuzard** [comment]
The design you suggest is not what we actually intended to have. Not `/audit kick user` but just `/audit user` and it will show **all** actions in chronological order. We do not need a filter.

**Comment by Zabuzard** [comment]
> Blocked by #298 and #249.

This is **not blocked** by #249 but only by #298

**Comment by Zabuzard** [comment]
thing got implemented.

**Comment by RealYusufIsmail** [comment]
Will work on after the warm command. I only have 2 exams left

**Comment by Zabuzard** [comment]
> Will work on after the warm command. I only have 2 exams left

Sounds like it wont make the christmas cut. Ill unassign you then for now, so that someone else could take it. Its a "good first issue" after all.
