### ISSUE TITLE
Vc days is in seconds

### ISSUE THREAD

**Issue by RealYusufIsmail** [Together-Java/TJ-Bot#304]
**Describe the bug**
It should be in days, hours or  minutes instead of seconds to make it easer for the user.
**Expected behavior**
The user should input the number of days in days, hours or minutes instead of seconds
Why seconds it makes the users life harder.

**Comment by Zabuzard** [comment]
Why days? Why not hours or minutes? Or all of them with a choice menu?

**Comment by RealYusufIsmail** [comment]
> Why days? Why not hours or minutes? Or all of them with a choice menu?

Valid point.

**Comment by Tais993** [comment]
I find it weird that this is a bug report, this is in no way a bug.
It even clearly says that it's seconds, so weird but sure.

Furthermore, we can add a timeunit option, to specify the timeunit.
The default should be hours imo.

I think that's the best idea for UX
