### ISSUE TITLE
Create /modmail command

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#311]
The `/modmail` command is used to write a message to _a moderator_. The advantages over a simple DM are:

* the user does not need to know which users of a server are moderators
* the user does not need to befriend a moderator in case they have disabled non-friend DMs

The requirements for this are:

* the message must not be visible to other members
* the message is either visible to a single or all moderators

Optionally:

* the command should also be usable if not part of the guild anymore, for example after getting banned (needs careful design though to not be abused - rate limiting etc)

---

One cheap and low hanging possibility could be to write the message into the `#mod_audit_log` channel by using `ModAuditLogWriter` introduced in #296 . To make the message invisible, just use `ephemeral`.

**Comment by borgrel** [comment]
Making it not visible is easy, its an interaction so the bot reply just have to be epheral and poof, invisible command

However: there are plenty of people who will push and act badly UNTIL a mod is called and then they quickly backoff
there should be a visible and an invisible way to call mods?

(one to make a complaint and another to call for assistance)

**Comment by Zabuzard** [comment]
> there should be a visible and an invisible way to call mods?

The way I see it, if someone wants quick visible mod attention they just ping `@Moderator help, there is a scammer`, while `/modmail` is for when you want to contact a moderator privately, for example if you want to complain about the behavior of another user or if you have been banned unjustified.

**Comment by borgrel** [comment]
so the first global slash command use case we have

**Comment by talentedasian** [comment]
I'd like to work on this if no one has started working on this command. Also, would the command be allowed to used practically everywhere (within the guild)  and not just on a particular channel such as `bots`?

**Comment by Zabuzard** [comment]
> I'd like to work on this if no one has started working on this command. Also, would the command be allowed to be used practically everywhere (within the guild) and not just on a particular channel such as `bots`?

Yes, as all responses are **ephemeral**, it could be popped anywhere, no restrictions. But you do not have to do anything to control that, just a regular slash command handler would be enough, like any of the other slash commands we already have, `/ping` for example.

**Comment by Zabuzard** [comment]
@talentedasian Why did you add "blocked"? By what is this issue blocked?

**Comment by talentedasian** [comment]
The `ModAuditLogWriter` from #296 isn't merged yet

**Comment by marko-radosavljevic** [comment]
@Zabuzard

>One cheap and low hanging possibility could be to write the message into the #mod_audit_log channel by using ModAuditLogWriter introduced in #296 . To make the message invisible, just use ephemeral.

The issue with #mod_audit_log is that it is permanently muted by everyone, and we usually don't scroll and read everything, unless we have a need to do so.

I think this should go in a new channel, so we can give it a proper attention it deserves. What do you think? ^^

**Comment by Zabuzard** [comment]
> The issue with #mod_audit_log is that it is permanently muted by everyone

I did not think about that because I actually do not have it muted 😆

> I think this should go in a new channel, so we can give it a proper attention it deserves.

Sure, makes sense.

Can go through a similar flow/system. Maybe the class can offer both channels or its a second class or similar. Whatever is cleaner, I leave it up to who implements it.

**Comment by illuminator3** [comment]
add an option to stay anonymous when talking to modmail

**Comment by Tais993** [comment]
Can be taken over, when I have the time I'll finish my PR, but no promises on when this will happen
