### ISSUE TITLE
Update expired SSL certificate (VPS)

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#317]
The SSL certificate used by our VPS seems to be expired since 2 days. Causing the docker-publish action to fail.

As a consequence, both of our bots are running on old versions now (which contain a critical security vulnerability).

![](https://i.imgur.com/AMGSHkZ.png)

when visiting https://togetherjava.duckdns.org:5001/v2/

Also see the failing docker script: https://github.com/Together-Java/TJ-Bot/runs/4486370061?check_suite_focus=true

---

Ideally we should also put measures to prevent this from happening again (auto-update or at least an alert. either in Discord or at least by mail or similar).

**Comment by marko-radosavljevic** [comment]
Issue resolved by renewing certificates with the certbot. Turns out, certbot was blocked by the firewall. ^^

From now on, it should auto-renew without issues. Thanks @I-Al-Istannen
