### ISSUE TITLE
Remove /db-get and /db-put commands

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#320]
We intially introduced the `/db-get` and `/db-put` commands as showcases to get our programmers started.

Time has passed and now we have a lot of commands that showcase how to use the database, and we also have a dedicated Wiki page guiding through a database command:

https://github.com/Together-Java/TJ-Bot/wiki/Add-question-command

It is time to remove this fake-command to cleanup:
* the codebase
* the database
* the list of commands available to the end-user

---

So the work for this consists of three steps:
1. Delete `DatabaseCommand.java`
2. Fix its usages (probably just `Commands.java`)
3. Drop the database table that it used (with a **new migration script**, dont edit the original script that added it)

**Comment by Heatmanofurioso** [comment]
This change makes complete sense nowadays

**Comment by borgrel** [comment]
While the get and put definitely shouldn't be part of the deployed codebase

Should the basic functionality of the command remain (even if not 'actively' included in the deployed version)
to help beginner coders debug their db if they mess it up while trying to add tables or anything?

(or perhaps included as a unit test to confirm the db is A-OK?)

**Comment by Zabuzard** [comment]
> While the get and put definitely shouldn't be part of the deployed codebase
> 
> Should the basic functionality of the command remain (even if not 'actively' included in the deployed version) to help beginner coders debug their db if they mess it up while trying to add tables or anything?
> 
> (or perhaps included as a unit test to confirm the db is A-OK?)

The command demonstrates how to get started with databases but our tutorials in the Wiki cover that to a great extend now with 2 example commands that are coded step-by-step (but not included in the codebase). I think they make `/db get` and `/db put` obsolete.
