### ISSUE TITLE
Add a reminder command

### ISSUE THREAD

**Issue by RealYusufIsmail** [Together-Java/TJ-Bot#325]
**Is your feature request related to a problem? Please describe.**
Used to do remind people to do something in at a certain time or in a certain number of days, hour, etc 

Can be useful to stop people from forgetting things.

**Describe the solution you'd like**
The user will be able to type `/remindme time what to remind(optional)`

**Comment by Zabuzard** [comment]
I feel like this would benefit from a more general solution, since #267 will also need such a feature. Possible synergy with #235 .

**Comment by IslamSakrak** [comment]
Can I be assigned to this?

**Comment by Tais993** [comment]
You've been assigned! Good luck

**Comment by IslamSakrak** [comment]
Thank you

**Comment by IslamSakrak** [comment]
I hope it won't be a problem, but I can start working on this command on Sunday so if anyone else wanna work on it, feel free to do it.

**Comment by Zabuzard** [comment]
> I hope it won't be a problem, but I can start working on this command on Sunday so if anyone else wanna work on it, feel free to do it.

@IslamSakrak Are you still working on this? Otherwise, I might be willing to take this. (The persistence bit is a bit tricky to get right and #346 might be quite helpful as well)
