### ISSUE TITLE
Better wrapper over the current Slash Command API

### ISSUE THREAD

**Issue by Alathreon** [Together-Java/TJ-Bot#333]
**Is your feature request related to a problem? Please describe.**

The current slash command system has two problems :
- nullable everywhere, when the api could do check for us
- not enough datatypes : only a few datatypes are present
The feature request is to add a better wrapper on the SlashCommand system to make it easier to use.

**Describe the solution you'd like**

Those two problems can be fixed by adding a wrapper with more types and validations.
You can for example have a addInt() to check an int, and an overload, addInt(min, max) where validation will automatically be done to check against min and max.
Another example would be addMember() where validation will automatically be done to ensure to get a non null member.

In order to do that, there are two options :
- add a builder class which is used like the current addOption but with all the new methods ie
`addIntFrom("id", "An id", 1).addMember("member", "A member")...`
this solution has the disadvantage of the possibility of being less readable
- store the information in a file, like json file ie
```json
{
  "id": {
    "description": "An id",
    "type": "int",
    "min": 1
   },
  "member": {
    "description": "A member",
    "type": "member"
  }
}
```
this solution has the disadvantage of not being dynamic : we can't add a custom validater/mapper easily or for example do an equivalent of addEnum(MyEnum.class)

A problem will be the error handling : because we are one layer above jda, a command failing to match their INTEGER type is different from a command failing to match our int type, so we can add custom errors that are automatic but can be overriden by the option builder.
The overriding can start to cause problem with the builder because the code will start to be unreadable, but overriding with json will prevent to have a dynamic error, like "Expected X".

How will the type validator/mapper looks like :
```java
//Note that this class can be either a single concrete class with two fields like Optional, or an interface with two implementations
class Result<R, String> {
  public static <R> Result<R> of(R result);
  public static <R> Result<R> ofError(String message, Object... args);

  public R get(){...}
  public String error(){...}
  public boolean isPresent(){...}
}
//Or just Function interface : Function<T, Result<R>>
interface ArgumentMapper<T, R> {
  Result<R> parse(T arg);
  OptionType getOptionType();
}
```
Note that the whole api can be done with only String option type, let's see if using the other types make it easier or harder.

What about the onSlashCommand event ?
```java
void BetterOnSlashCommand(BetterJDA bjda, JDA jda, SlashCommandEvent event, Arguments args);
```
This method has `event` so if needed, we can use it, `jda` for easier access, `bjda` is just a wrapper over jda, it's just to show that if at some point a wrapper is born, it's compatible, and finally, `args`
There are two ways to make args : either you do `args.get("id").asInt()` or `args.getAsInt("id")`.
There will be a lot of methods, examples can be found in "Event commands" section in Additional context.
Also none of those methods will return null, every check are already done

There are other areas where impovement can be done with a wrapper like this, for example by using enums with subcommands instead of Strings :
```java
void onSubCommand(MyEnum myEnum, SlashCommandEvent event) {
  switch(myEnum) {
    case FOO -> onFoo(event);
    case BAR -> onFoo(event);
} //No need of default since every case are covered, java will ensure it !
```
**Describe alternatives you've considered**

No alternative seeing how it is causing problems.
**Additional context**

#### Integer
`addInt(String name, String description)`
`addIntFrom(String name, String description, int min)`
`addIntTo(String name, String description, int max)`
`addInt(String name, String description, int min, int max)`
Do the same same for long, and maybe double (?)
##### Event commands :
`int asInt()`
#### Boolean
`addBool(String name, String description)`
`addBool(String name, String description, String ifTrue, String ifFalse)` (somewhat like addSet/Enum, will use String type instead of Boolean)
##### Event commands :
`boolean asBool()`
#### String, Set and Enum
`addString(String name, String description)`
`addString(String name, String description, String regex)`
`addString(String name, String description, Pattern regex)`
`addSet(String name, String description, Set<String> possibleValues)`
`addSet(String name, String description, String... possibleValues)`
`addEnum(String name, String description, Class<? extends Enum> possibleValues)`
##### Event commands :
`String asString()` (interchangeable with String, Set, and Enum)
`<T> T asEnumConst(Class<T extends Enum> clazz)` (interchangeable with String, Set, and Enum)
#### Date and time
`addDate(String name, String description)`
`addDateFrom(String name, String description, LocalDate from)`
`addDateTo(String name, String description, LocalDate to)`
`addDate(String name, String description, LocalDate from, LocalDate to)`
Same with LocalTime
Same with LocalDateTime
##### Event commands :
`LocalDate asDate()`
Same with LocalTime
Same with LocalDateTime
#### Discord entities
`addId(String name, String description)`
`addMember(String name, String description)`
`addTextChannel(String name, String description)` (and other channels...)
`addUser(String name, String description)` (maybe ?)
`addEmoji(String name, String description)`
##### Event commands :
`long asId()`
`Member asMember()` (can also be used with addUser)
`TextChannel asTextChannel` 
etc.
#### Custom
`addCustomNumber(String name, String description, Function<Double, Result<?> mapper)`
`addCustomChannel(String name, String description, Function<GuildChannel, Result<?> mapper)`
Same for every slash command option type.
##### Event commands :
`<T> T as(Class<T> clazz)`

**Comment by Alathreon** [comment]
I can do it btw, I have already made a wrapper to allow things like that, but it was on regular commands.

**Comment by Tais993** [comment]
WRONG BUTTON

**Comment by Tais993** [comment]
> Those two problems can be fixed by adding a wrapper with more types and validations. You can for example have a addInt() to check an int, and an overload, addInt(min, max) where validation will automatically be done to check against min and max. Another example would be addMember() where validation will automatically be done to ensure to get a non null member.
> 
> In order to do that, there are two options :
> 
>     * add a builder class which is used like the current addOption but with all the new methods ie
>       `addIntFrom("id", "An id", 1).addMember("member", "A member")...`
>       this solution has the disadvantage of the possibility of being less readable
> 
>     * store the information in a file, like json file ie

Why do we need a JSON file?

Besides that, I do like some of these things that it'll allow.
It'll allow usage of certain non-existent option types a lot easier.

One of the examples you gave, was an int option.
Setting a min/max value, will give it good UX, and easy development.

But still, not everything will be nice, don't forget we're using slash-commands.


> A problem will be the error handling : because we are one layer above jda, a command failing to match their INTEGER type is different from a command failing to match our int type, so we can add custom errors that are automatic but can be overriden by the option builder. The overriding can start to cause problem with the builder because the code will start to be unreadable, but overriding with json will prevent to have a dynamic error, like "Expected X".


> How will the type validator/mapper looks like :
> ```java
> //Note that this class can be either a single concrete class with two fields like Optional, or an interface with two implementations
> class Result<R, String> {
>   public static <R> Result<R> of(R result);
>   public static <R> Result<R> ofError(String message, Object... args);
> 
>   public R get(){...}
>   public String error(){...}
>   public boolean isPresent(){...}
> }
> //Or just Function interface : Function<T, Result<R>>
> interface ArgumentMapper<T, R> {
>   Result<R> parse(T arg);
> }
> ```

I'm missing what the Result class is, what does it do?
It's a type validator / mapper, of what?
We use the Result class instead of OptionMapping?

> This method has `event` so if needed, we can use it, `jda` for easier access, `bjda` is just a wrapper over jda, it's just to show that if at some point a wrapper is born, it's compatible, and finally, `args` There are two ways to make args : either you do `args.get("id").asInt()` or `args.getAsInt("id")`. There will be a lot of methods, examples can be found in "Event commands" section in Additional context. Also none of those methods will return null, every check are already done

I'm not really into the idea of wrapping the whole JDA api, there isn't a lot of null in there.
So sounds like a mess to maintain too, who has the time for it?

> There are other areas where impovement can be done with a wrapper like this, for example by using enums with subcommands instead of Strings :

This is another good idea, but I'm not sure how we'll give the developer a good UX when doing this?
If we find something, I'm all for this.


 
> `addInt(String name, String description)` `addIntFrom(String name, String description, int min)` `addIntTo(String name, String description, int max)` `addInt(String name, String description, int min, int max)` Do the same same for long, and maybe double (?)

I'm for this, but, how're we going to handle users giving values with a decimal?
Will we just error? Or round it to an integer?

Max and min values are easy to handle, but decimals?
I'm not sure

Discord allows Integer and Number (from JS)

> `addBool(String name, String description)` `addBool(String name, String description, String ifTrue, String ifFalse)` (somewhat like addSet/Enum, will use String type instead of Boolean)

Sure, but this already exists

> `addString(String name, String description)` `addString(String name, String description, String regex)` `addString(String name, String description, Pattern regex)` `addSet(String name, String description, Set<String> possibleValues)` `addSet(String name, String description, String... possibleValues)` `addEnum(String name, String description, Class<? extends Enum> possibleValues)`

How will you handle this, error after the user send their command?
The addEnum can be easily done using Choices, so I'm all for that.


> `addDate(String name, String description)` `addDateFrom(String name, String description, LocalDate from)` `addDateTo(String name, String description, LocalDate to)` `addDate(String name, String description, LocalDate from, LocalDate to)` Same with LocalTime Same with LocalDateTime

This is a good one, but I'm not sure how you'll do this one too.
Discord themselves is also adding a date picker option.
When that is released, that should be used instead for sure.

> `addId(String name, String description)` `addMember(String name, String description)` `addTextChannel(String name, String description)` (and other channels...) `addUser(String name, String description)` (maybe ?) `addEmoji(String name, String description)`

Another one, how will we do this?
Discord allows ROLE, CHANNEL, USER and MENTIONABLE

Thus Member? How will we do that?
Emoji? I doubt that that falls under mentionable
And Id? Falls under mentionable I'd think?
 
> `addCustomNumber(String name, String description, Function<Double, Result<?> mapper)` `addCustomChannel(String name, String description, Function<GuildChannel, Result<?> mapper)` Same for every slash command option type.
> ##### Event commands :
How will we do this?

> `<T> T as(Class<T> clazz)`
How will we do this?

**Comment by Alathreon** [comment]
> Why do we need a JSON file?
Like as I explained, it's an alternative to the builder.
Because doing
```java
builder.addInt("Foo", "some foo that does foo", 5, 20)
           .addSet("Bar", "bar that does bar", "Foo", "Bar", "Baz")
          ...
         ...
```
Is far less readable than a json, also a json can easily be edited at runtime, if needed.

Also don't forget that this idea is to add a layer on the slash command system :
Currently : 
`SlashCommand -> SlashCommandAdapter -> command impls`
to
`SlashCommand - SlashCommandAdapter - BetterSlashCommandAdapter - command impls`
or
`SlashCommand - BetterSlashCommandAdapter - command impls`
Where SlashCommand is the base class from jda, SlashCommandAdapter is the one from together java, and BetterSlashCommandAdapter is the one that we are discussing here.

This means several things :
- First we don't need to rely on Option types, we can abstract them and create our own, so for example, I want to create a date type, then I will take the Option STRING type and parse it into a date and here is the new date type. A second example, we want Member type ? then just use Option USER and test if it is a member, we want an emoji type ? use a Option STRING type and test if it is an emoji, and parse it if it is. We want a TextChannel type ? use Option CHANNEL type and test if it is a TextChannel. Etc.
This is for every time you asked how to do X, we have a layer of abstraction, so we can use it, now the new types are unrelated to Option types. Same for the custom one.
- Second this means that we need to provide basic methods, like the basic addString, so we need to basically copy it. But that also means that we have more control, and now we can validate the string ie with the addString(regex) one or we can change the implementation and so the user who will do the command will no longer depends of the basic option but our own options.
- Third this means that we will have harder time to manage errors with option types, discord will directly prevent you from entering invalid things, but with custom types, a solution will be to automatically return an error message "The integer foo should be between 5 and 10, but was 15" for addInt(min, max) for example. And the on slash command event will only ever run if the what entered the user is valid, so here a correct number between 5 and 10.

I changed a bit interface ArgumentMapper :
```java
interface ArgumentMapper<T, R> {
  Result<R> parse(T arg);
  OptionType getOptionType();
}
```
Here an implementation of addInt(min, max) :
```java
//Will use option type INTEGER, so T must be Long, and then it will return a custom type of ours : int.
class IntRange implements ArgumentMapper<Long, Integer> {
  private final int min;
  private final int max;
  //constructor...

  @Override
  public Result<Integer> parse(long arg) {
    String errMsg = "argument %d is not between %d and %d".formatted(arg, min, max);
    if(arg > Integer.MAX_VALUE || arg < Integer.MIN_VALUE) return Result.ofError(errMsg); //May not be necessary
    if(arg < min || arg >= max) return Result.ofError(errMsg);
    return Result.of((int)arg);
  }

  @Override
  public OptionType getOptionType() {
    return OptionType.INTEGER;
  }
}
```
I think I talked about everything that you said, tell me if you still have doubts.

**Comment by Tais993** [comment]
Fyi, there's already min and max values of integer/number type options by Discord.

So that's not an issue.

The rest, sure.
But we should add the requirements in the description of the option.
Otherwise, people have to run the command till the get an error.

Which is, just bad UX.

**Comment by Alathreon** [comment]
> The rest, sure.
> But we should add the requirements in the description of the option.
> Otherwise, people have to run the command till the get an error.
> 
> Which is, just bad UX.
You mean, put in the description "The int can't be lower than 0" ?
Sure, but it's the dev who wrote a command which will do that, because if we do, the description of the message may not match what the dev wants and it may transform the description into a complex and long string, tho adding a feature like this can easily be done and should be able to turn it off and on.

**Comment by Tais993** [comment]
Yeah, that's indeed on the dev not the wrapper.
We'll take care of it during the reviews!

**Comment by Zabuzard** [comment]
The only problem I personally had so far with the API is the nullable bit on extracting the options. So `getOption(...).getAsXXX(...)` can return `null` but in some cases (if you made it **required**), you know it cant be null (and if its null, it should be considered a bug, i.e. crash). In which case I would like to have a method like `getOption(...).requireAsXXX(...)` which could come from a helper class or a wrapper (both have advantages and disadvantages).

I didnt have any other issue so far and I have trouble understanding the problems this proposal here is supposed to solve beyond the one I mentioned. That said, I am okay with everything that you guys think is useful 👍
