### ISSUE TITLE
Create /note command

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#349]
### Overview

The `/note` command would pretty much be a 1:1 copy of `/warn`, but without the "DM the user"-bit.

So UX-wise, we are talking about a command like `/note user:@John reason:Kinda toxic sometimes`.

Hence, it should also result in an entry in the DB and being shown in the `/audit` command.

Technically, this is a no-brainer. However, since its basically a 1:1 copy of `WarnCommand`, there is potential to do some refactoring and get rid of code duplication. Might be kinda tricky in practice though, maybe not worth it.

### Motivation

Sometimes mods handle a semi-critical situation informally in chat and dont want to issue a full warning that also notifies the user formally again via DM.

It is still useful to be able to just write down the incident to not forget about it in the future when judging about future situations - a note command could be useful for this.

**Comment by Zabuzard** [comment]
(@marko-radosavljevic for visibility)

**Comment by Budbomber** [comment]
Regarding this couldn't we just extend the warn command with an option  - no notice or something which will not dm the user but still adds?

**Comment by Zabuzard** [comment]
> Regarding this couldn't we just extend the warn command with an option - no notice or something which will not dm the user but still adds?

In theory yes but I think that would miss the point and rather confuse. I think it is better if it is separated everywhere, as separate command to the user and in particular also in the `/audit` UI.
We should design such things with the user in mind, from their perspective - not from the perspective of what would be the easiest solution to code (not assuming that was your intention).

**Comment by Budbomber** [comment]
>

**Comment by Budbomber** [comment]
I dont know why it closed.. But yeah makes sense, wasn't intention to make it simple more thought of it as an extension

**Comment by marko-radosavljevic** [comment]
Yup, really useful feature for moderation. There are few more use cases scenarios I can think of.

One of them is documenting something about a member/situation, without them knowing about it. Those can be a bit lengthy I imagine: links to the specific message that is being noted and commented on, time stamps, people involved, moderators that handled the action, link to the action that was taken by a moderator, reason and the backstory, thoughts on future plans about the member/situation, links to the mods discussions about it.. 

What I'm trying to demonstrate is, it's probably quite uncomfortable to write a well-structured and informative note in a tiny text-area, in the even tinier 'reason' slash command option, without even being able to add new lines to it. Just something to think about when implementing this, but I understand that we currently have limitations that we can't bypass easily.

**Comment by N1K-x** [comment]
I think we should brainstorm on what additional options might be beneficial for the `note` command (and probably the `warn` command as well). 

I could imagine that an option to add a link to a Discord message would be used quite often for example (though I do not moderate so I might be wrong), extracting this information as an option would allow to display it separately in the audit log, therefor making it more structured. 

An idea I have for assisting with writing a longer note would be to allow the command being send as an reply to a message. The message replied to would be taken as the notes. I am not sure if this is possible though nor about the resulting UX. 

Also something to think about: do we want multiple (immutable) notes or just one "big" note per user which can be edited and expanded at any time. I feel like multiple notes would be better but I wanted to share this thought nevertheless.

**Comment by Tais993** [comment]
I think we should separate this form the warn command.

If we make the note command only ask for the user (and maybe more info)

We can use modals (forms) that accept multi-line input for the full note. This allows multi-sentence notes and has easy UX.
Only issue would be that it means this'll be blocked till #364 and #368 are merged.

**Comment by N1K-x** [comment]
Forms would indeed be very nice. I was not aware that Discord supports such fancy features

> I think we should separate this from the warn command.

I am not so sure about this though, the idea was to have it be basically the same but without the "messages user" bit, so maybe we want to have them both work the same way - both as a form? I guess it depends on whether or not the moderators want to have greater editing capabilities for `warn` as well.

**Comment by Zabuzard** [comment]
I dont think we have to block on forms for now. Lets do it like existing commands (warn, ban, ...), so basically suffer from the multiline issue for today - but thats okay.

And then add forms later to all those commands, not just note, once they arrive.

**Comment by Zabuzard** [comment]
Decided that it might be worth to offer this command also to **Staff Assistants** :)
