### ISSUE TITLE
Not all of the VC activities work

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#362]
**Describe the bug**
When trying to play certain activities, an error will pop up saying how the server isn't whitelisted.

**Expected behavior**
The activity to start

**To Reproduce**
1. Run the vc activity command
2. Press the link to start the activity
3. See error

If your activity works, try another one.

**Screenshots**
![image](https://user-images.githubusercontent.com/49957334/152645048-345e21fb-dd61-4201-a352-3281f0c4b7a0.png)

# How to fix

A fix is rather simple.

You'll have to try each activity, if one doesn't work due to the error seen above, you write that activity down.
After you went through all activities, remove the ones that don't work.

**Comment by Zabuzard** [comment]
Is there a way on our side to actually make the activities work? I.e. to whitelist them?

**Comment by Tais993** [comment]
> Is there a way on our side to actually make the activities work? I.e. to whitelist them?

Unfortunately no, YouTube probably wants to wait till they implement ads or something,
We'll find out
