### ISSUE TITLE
Generation of logger inside methods

### ISSUE THREAD

**Issue by java-coding-prodigy** [Together-Java/TJ-Bot#365]
**Describe the bug**
`DatabaseProvider` generates new loggers inside its methods

**Expected behavior**
The logger should be put into a private static field called `logger`

**Additional context**
Occurences:
1) line 37
```java
catch (final SQLException e) {
            LoggerFactory.getLogger(DatabaseProvider.class)
                .error("Exception while creating Database.", e);
            throw new FatalBeanException("Could not create Database.", e);
        }
```
2) line 49
```java
catch (final IOException e) {
            LoggerFactory.getLogger(DatabaseProvider.class)
                .error("Exception while creating Database-Path.", e);
        }
```

**Comment by krankkkk** [comment]
That is not how loggers work, there is no need for the field

**Comment by Tais993** [comment]
It is the typical usage pattern, therefore I'd disagree

**Comment by java-coding-prodigy** [comment]
> there is no need for the field

I disagree with this too.

**Comment by krankkkk** [comment]
1. The loggers would only be created on a fatal exception, which means the application cannot continue. The change to an field would actually just create an unused logger.
2. Even if you would somehow end up calling those lines multiple times, you would **not**  create new loggers, they are cached in slf4j/log4j

**Comment by java-coding-prodigy** [comment]
I see your point, but to maintain the pattern with other classes and also making the code more readable, this change should be made.

**Comment by Tais993** [comment]
1, that's fine
2, I know

Why should we change it?

1, consistency

The typical usage pattern is to use a field, it's consistent around our codebase, and everyone's else's codebase. Changing it won't do any harm

**Comment by krankkkk** [comment]
Then this is still not a bug, mark it as improvement

**Comment by apwhitelaw** [comment]
Is this what you mean?

`private static Logger logger = LoggerFactory.getLogger(DatabaseProvider.class);`

at the top of the class, and then change where we call the error to instead use that field, like so:

`logger.error("Exception while creating Database.", e);`

**Comment by Tais993** [comment]
See #366, if you want you can create a new PR since this is such a small change.

The variable should be named `log` instead since it otherwise overrides a variable

**Comment by Zabuzard** [comment]
@apwhitelaw This issue is already being worked on and the associated PR is almost shipped (@java-coding-prodigy fix the last issue please).

![already worked on](https://i.imgur.com/j7Jcdw7.png)

So I would suggest that you coordinate with @java-coding-prodigy whether he wants to finish his PR himself or whether you can take it over (and do the last remaining mini change on it).

**Comment by java-coding-prodigy** [comment]
Sorry, I was just away for a while, I'm making the change right now.
