### ISSUE TITLE
Help channel locking

### ISSUE THREAD

**Issue by illuminator3** [Together-Java/TJ-Bot#369]
When a user asks in a help channel, they should be locked from sending a message in any other help channel. This is to prevent those who spam every help channel with their question.

**Comment by java-coding-prodigy** [comment]
What if a helper is helping users in >1 channel though?

**Comment by Zabuzard** [comment]
Sounds indeed fragile but I totally get the motivation. Maybe we can do some brainstorming and have better ideas or modifications. For example only block for 5 minutes. And only the person who posted after a `/free`, i.e. the person that the free-system identified as a person who wants help (this is not always true but most of the time).

**Comment by N1K-x** [comment]
The free-system does already reply to the message that caused the channel to be not free. It could just block the user who sent that specific message. 
Sometimes it happens that someone asks a question, marks the channel as free and then someone else gives additional information. This would block the wrong person then.

We could probably implement some checking to exclude a person in specific cases (for example, if the message in question is a reply to a message before `/free` was called).

In any case the free-system should unblock the person as soon as the channel is being marked as free again. So if someone answers something and gets blocked, they can just free the channel again.

**Comment by borgrel** [comment]
the problem will disappear once threads are implemented

there is no reason to 'fix' this

**Comment by Zabuzard** [comment]
Closed in favor of #444
