### ISSUE TITLE
Update VC activities command with new activities

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#378]
**Is your feature request related to a problem? Please describe.**
New activities have been added, we should update our command so the new ones can be played.

**Describe the solution you'd like**
Check for new activies, and add the ones we can play.

**Comment by Zabuzard** [comment]
What are the new acitivites? Where can we see them? Any link?

**Comment by Tais993** [comment]
Didn't assign "good first issue" for that reason.

Once I have the time to retrieve them I'll update this PR and someone else can try add them if they want ^^

**Comment by Tais993** [comment]
```
YOUTUBE_APPLICATION_ID = 755600276941176913

XBOX_ACTIVITY_APPLICATION_ID = 438122941302046720

WATCH_YOUTUBE_PROD_APP_ID = 880218394199220334

WATCH_YOUTUBE_DEV_APP_ID = 880218832743055411

PUTT_PARTY_APPLICATION_DEV_ID = 910224161476083792

CHESS_IN_THE_PARK_APP_ID = 832012774040141894

CHECKERS_IN_THE_PARK_APP_ID = 832013003968348200

BYS_TWOODLE_APP_ID = 902271654783242291
```

I doubt that some of these even *are* anything (XBOX_ACTIVITY_APPLICATION_ID a.e) 
It's just that I'm not sure, so to be safe I'd appreciate if someone tries all of them.

How to try them is a good question to ask.

- Create an invite for a VoiceChannel 
- setTargetApplication​ method
- print URL
- click on URL

If you receive an error as shown in #362 you may ignore the application.

**Comment by Tais993** [comment]
Update, [found a Gist](https://gist.github.com/GeneralSadaf/42d91a2b6a93a7db7a39208f2d8b53ad) with more activities.
Seems YouTube Together does work, but has a new ID

**Comment by Korwai** [comment]
Hellooo, may I try tackling this as a first issue?

**Comment by Zabuzard** [comment]
Hi @Korwai  :) Sure thing, thanks for considering. Its been some time this ticket was opened though, so I could imagine that the list of valid activities changed already. @Tais993 do you have an updated list maybe?

**Comment by Korwai** [comment]
I found this list (https://gist.github.com/GeneralSadaf/42d91a2b6a93a7db7a39208f2d8b53ad) when looking for IDs of VC activities and it seems updated but the one listed in the current documentation refers to this one (https://github.com/DV8FromTheWorld/JDA/pull/1628).

Any preference on which list I should refer to? ^^
