### ISSUE TITLE
Remove "/role-select all"

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#381]
Recently, we merged #351 and it is pretty cool. However, it has two subcommands:

* `/role-select all` - users can pick any of the existing roles on the server
* `/role-select choose` - users can only pick roles that the mod pre-selected

I do not see a valid use case for `/role-select all`. Why would you want people to give the possibility to choose from ALL roles (including staff assistant, moderator, ... and other dangerous roles).

In fact, it only takes a careless mod to accidentally run `/role-select all`, hit enter and oops people could already give themselves `Moderator`, `Staff Assistant` and other "protected" roles (and you wouldnt even notice).

I propose to remove `/role-select all` and lift `/role-select choose` to just `/role-select`.

**Comment by Zabuzard** [comment]
(@Tais993 for visibility)

**Comment by Tais993** [comment]
I agree, kept it since it was in the original implementation.
