### ISSUE TITLE
/tex should support inline TeX

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#386]
### Overview

The `/tex` command should support inline TeX, for example using the idiomatic $-notation:
```java
/tex latex: Hello, look at this $\frac{x}{2}$, nice stuff!
```
Right now, the command interprets the whole content as TeX and renders it accordingly:
![example](https://i.imgur.com/TMgYhPl.png)

It should instead be rendered as:
![desired](https://i.imgur.com/F07NARI.png)

### Implementation hint

This could be solved by identifying the `$...$` areas. If not present, simply use the existing flow. But if present, wrap the part to the left and right of it inside `\text{...}` blocks.

So `A$B$C` would be turned into `\text{A}B\text{C}`.

Be careful though, that there could be multiple `$`-sections.
* For example `See $\frac{x}{2}$ and also $\frac{y}{2}$`.
* Also the edge cases that it either starts with a section `$\frac{x}{2}$ nice`
* or ends with it `See $\frac{x}{2}$`.

The previous example `Hello, look at this $\frac{x}{2}$, nice stuff!` would then be turned into
```tex
\text{Hello, look at this }\frac{x}{2}\text{, nice stuff!}
```
and send like that to the TeX-engine.

**Comment by IslamSakrak** [comment]
Can I be assigned to this I want to give it a try?

**Comment by IslamSakrak** [comment]
Could you elaborate a bit on this?

`/tex latex: Hello, look at this $\frac{x}{2}$, nice stuff!`

the second image it looks like just that the /`tex `contains `$` it makes the whole /`tex `a regular text \`text{}`

While in the example 

`So A$B$C would be turned into \text{A}B\text{C}.`

it looks like it makes just specific parts into a text. 

So could you just clear it up for me please?

**Comment by Zabuzard** [comment]
Taking over
