### ISSUE TITLE
Block scam links 

### ISSUE THREAD

**Issue by marko-radosavljevic** [Together-Java/TJ-Bot#390]
**Is your feature request related to a problem? Please describe.**

There is too much scam links (nitro, steam, etc) posted on the discord, and it's taking a lot of moderation time, while annoying and harassing the whole server. Sadly, people still fall for these phishing attempts, so it's also a security issue we should address.

**Describe the solution you'd like**

Block the scam links with our bot, and possibly temporarily remove offending members. (if false-positives are rare enough)

**Describe alternatives you've considered**

To waste time indefinitely until discord does something about it.

**Additional context**

Phishing link can look like this (list will be edited):

```
https://disceord.gift/EF2Zx27xxxx
```

On the same IP, these domains can be found:

- dlscors.gift
- dlscorb.gift
- disczrd.gift
- discorcl-nitro-gift.com
- discoerd.gift
- discerd.gift
- disceord.gift
- disccord.gift

How it looks in chat:
![discord-nitro-scam-example](https://user-images.githubusercontent.com/30927961/154808519-7d8c7a56-7ff6-4424-83d7-abf805bec578.png)

Text phrases usually found in link previews:

`You've been gifted a subscription!`
`Discord has gifted you Nitro for 1 month`

I can host a full website example, or just html page if needed.

**Comment by Zabuzard** [comment]
Nitro scam from the last 6 months.

# DO NOT CLICK ANY OF THESE LINKS! (they will steal your discord account if you are logged in)
```
🤩bro steam gived nitro - https://nitro-ds.online/LfgUfMzqYw

@​everyone, Free subscription for 3 months DISCORD NITRO - https://e-giftpremium.com/

@​everyone
Discord Nitro distribution from STEAM.
Get 3 month of Discord Nitro. Offer ends January 28, 2022 at 11am EDT. Customize your profile, share your screen in HD, update your emoji and more!
https://dlscrod-game.ru/promotion

@​everyone
Gifts for the new year, nitro for 3 months: https://discofdapp.com/newyears

@​everyone yo , I got some nitro left over here https://steelsseriesnitros.com/billing/promotions/vh98rpaEJZnha5x37agpmOz2

@​everyone
:video_game: • Get Discord Nitro for Free from Steam Store
Free 3 months Discord Nitro
:clock630: • Personalize your profile, screen share in HD, upgrade your emojis, and more.
:gem: • Click to get Nitro: https://discoord-nittro.com/welcome
:Works only with prime go or rust or pubg

@​everyone, Check this lol, there nitro is handed out for free, take it until everything is sorted out https://dicsord-present.ru/airdrop

@​everyone
• Get Discord Nitro for Free from Steam Store
Free 3 months Discord Nitro
• The offer is valid until at 6:00PM on November 30, 2021. Personalize your profile, screen share in HD, upgrade your emojis, and more.
• Click to get Nitro: https://dliscord.shop/welcome

airdrop discord nitro by steam, take it https://bit.ly/30RzoKw

Steam is giving away free discord nitro, have time to pick up at my link https://bit.ly/3nlzmUi before the action is over.

@​everyone, take nitro faster, it's already running out
https://discordu.gift/u1CHEX2sjpDuR3T6
```

**Comment by Zabuzard** [comment]
Patterns I see is:
* `@everyone`
* keywords `nitro`, `discord`, `steam`, `free`, 
* a link whose host is similar to `discord`

**Comment by Tais993** [comment]
~~Owh my gosh, thanks for the Nitro @Zabuzard! I can't login into my account anymore though?~~

1 idea of the implementation.

Our bot deletes the message, mutes the author, and sends the content in a mod-log channel.
This message contains a ban + unmute button, this way we can never really ban the wrong person.

After banning/muting we can just disable the buttons so everyone knows it's already been handled.

This makes it nearly impossible, even when our bot fails, to ban the wrong people.

**Comment by Zabuzard** [comment]
Good idea.

I am still hoping to fix this proper with either Discord help or an actual proper scam-blocker-bot.

But a low hanging fruit seems to be to build some simple detection out of the above pattern and call it a day.

In particular a combination of an `@everyone`, `nitro` and a url is a dead giveaway.

**Comment by Zabuzard** [comment]
> Another probable pattern that is very consistent and predictable is phishing HTML they use.
Do you actually have to enter data first? I thought it steals the session directly, i.e. just clicking it is already too much.

If thats the case, it will be hard for us to analyze the websites 😆

**Comment by marko-radosavljevic** [comment]
> > Another probable pattern that is very consistent and predictable is phishing HTML they use.
> > Do you actually have to enter data first? I thought it steals the session directly, i.e. just clicking it is already too much.
> 
> If thats the case, it will be hard for us to analyze the websites laughing

I can do it safely, just find me a few recent links that are alive. ^^

I have the last one saved, can share the HTML, or host the whole website for analysis.

**Comment by marko-radosavljevic** [comment]
Full html of the last scam, unsanitized.

[discord-nitro-scam-phishing-website-default-theme-2 (copy).txt](https://github.com/Together-Java/TJ-Bot/files/8108733/discord-nitro-scam-phishing-website-default-theme-2.copy.txt)

**Comment by Tais993** [comment]
> > Another probable pattern that is very consistent and predictable is phishing HTML they use.
> 
> Do you actually have to enter data first? I thought it steals the session directly, i.e. just clicking it is already too much.
> 
> If thats the case, it will be hard for us to analyze the websites 😆

It can't, session is stored in the app / your browser.
And a website can't access your PC like that, that'd be an extreme danger, and would mean that every site can hack you.

there's 2 types of scams;

Nitro scams, you've to login on a website, they gain FULL access to your account, can't change account details.
App scams, you need to "try" their "game", gains them access to the token / session, can't change account details

**Comment by marko-radosavljevic** [comment]
I can write an HTML analyser/fingerprinter later on. I just need a few more scam links to establish a pattern, since this is the only data I have for now. :relaxed:

**Comment by Heatmanofurioso** [comment]
Why not try to make a pattern matching domains similar to Discord?
I know they're adding new domains all the time, but.. some sort of fuzzy search on domains similar to the real one "excluding it" would probably catch most of them easily. "domain containing the words 'https://disc', 'https://nitro' 'https://gg'

**Comment by Tais993** [comment]
And what's the issue with basing it off the message?
They keywords Zabuzard mentioned, a link that's almost the same, would be enough?

Do we really need a HTML analyzer?

**Comment by marko-radosavljevic** [comment]
Yup, that's the idea for now.

Use the link/text for detection, and later on we can improve it. HTML fingerprinting is a relatively easy next step we can take, if we are not satisfied with the results.

**Comment by marko-radosavljevic** [comment]
Yup, I believe HTML analyser would be the most accurate method, and valuable addition. It can also be made very extensible, where you can easily add new phishing sites. It can also be self-improving, expanding its fingerprint base and accuracy.

There are lots of papers with techniques on how to do this:

- https://www.zdziarski.com/blog/wp-content/uploads/2010/02/phishing.pdf
- https://people.clarkson.edu/~jmatthew/publications/SPIE_PhishingDetection_2012.pdf

There are services that do this, and provide an API we can use.

- https://phishtank.org/
- https://openphish.com/

But like you said, with `HttpClient` and basic `contains` or jsoup for parsing and finding elements we want, we can write a simple but effective tool. Create the fingerprint, and store it for future comparisons. Very fast, accurate and not resource intensive. 

* * *

> While ur discussing, I already created a matcher that I think works fine enough.

How do is perform against these @Zabuzard?

- https://raw.githubusercontent.com/BuildBot42/discord-scam-links/main/list.txt
- https://raw.githubusercontent.com/Dogino/Discord-Phishing-URLs/main/scam-urls.txt

**Comment by Zabuzard** [comment]
I really do not want to overcomplicate this. At least not for the first iteration. I believe that what I created now is good enough for our purpose.

config-wise it supports a host-blacklist, a host-whitelist and a list of suspicious words. if suspicious words appear in the host name (fuzzy matching), it is marked suspicious.

For example `check-out-disc0rd-nice.com` would be considered suspicious since its similar to `discord`. That, together with `@everyone` or a mention of `nitro` would result in an action by the bot.

**Comment by marko-radosavljevic** [comment]
I agree, It should be more than enough for 95% of cases, and it's pretty simple.

We can then wait and see what discord has to offer with their auto-mod, and improve the system further if there is need for that. :heart:

**Comment by Tais993** [comment]
You mean that `nitro @everyone` is enough to already get removed?
I'd disagree, it's nothing harmful, can easily be a joke.
And that means we can't do a nitro giveaway \:p

**Comment by marko-radosavljevic** [comment]
Eh, I would argue that the benefit is much greater than the potential harm in removing those. We already block all discord invite links.





---- On Mon, 21 Feb 2022 16:56:51 +0100 Tais993 ***@***.***> wrote ----





You mean that nitro @everyone is enough to already get removed?
 I'd disagree, it's nothing harmful, can easily be a joke.
 And that means we can't do a nitro giveaway :p

**Comment by Zabuzard** [comment]
> You mean that `nitro @everyone` is enough to already get removed? I'd disagree, it's nothing harmful, can easily be a joke. And that means we can't do a nitro giveaway :p

I said nitro + everyone + a url in the message

If thats a joke, its ur own fault. That said, im not voting for "ban" but for "put into quarantine" (a role like muted) instead.

Also, we would by default probably run in a semi automatic mode anyways. We will start with a more manual mode and see how well it works and then increase to a more automatic mode if it works well.
