### ISSUE TITLE
How should the Community Bot be named?

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#4]
We would like to collect ideas for the Community Bot, i.e. this repository.

Please propose some ideas.

So far, we have:

- **TJ-Bot**
- Yeppod
- Bottey
- Doopye
- Noppey
- AnxiousMixer
- Acarnania
- Roberto
- Fatima
- Achmed
- Nebula
- Franz
- Machmut

**Comment by d3vel0per** [comment]
Why not our favourite Duke 🤗
![image](https://user-images.githubusercontent.com/3216900/132142148-fd354a4f-4ac5-4a85-8844-bd166ff2b346.png)

**Comment by Zabuzard** [comment]
We will start with the name **TJ-Bot** until someone creates another poll or similar.
