### ISSUE TITLE
/role-select crashes if server has too many roles

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#400]
### Overview

Attempting to use the `/role-select` command (regardless of arguments) from a guild that has more than 25 roles, will crash the command with an exception (it can not create a selection dialog with all those roles):

![call](https://i.imgur.com/7Ew3ynT.png)

![log](https://i.imgur.com/bPrTClV.png)

Unfortunately, there is no workaround for this. The code has to be changed for the command to work in our server - hence the priority on this ticket.

**Comment by Zabuzard** [comment]
@Tais993 For visibility

**Comment by Tais993** [comment]
Solution I had in my head is to create multiple selection menus (till the limit), and include a "submit" button.
After submitted, the UX is the same

**Comment by Zabuzard** [comment]
> Solution I had in my head is to create multiple selection menus (till the limit), and include a "submit" button.

An alternative quick fix could be to offer some sort of manual string parsing. The user usually already knows the roles to use. So they could do sth like `/role-select title: ... description: ... roles: "foo, bar, baz"` without any menu.

**Comment by Tais993** [comment]
Hmmm, now you're saying, I've an even better solution.
`/role-select String:title String:description Role:role (Role:role) (Role:role) (Role:role) (Role:role) (Role:role) (Role:role) (Role:role)...`
