### ISSUE TITLE
/remind doesnt work in threads (NPE)

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#405]
## Overview

The `/remind` command can not send a reminder that was set off from within a Discord-Thread. Worse, it crashes with a NPE:

![log](https://i.imgur.com/qGN25Xn.png)

## Proposed action

First of all, it is important to get rid of the error.

Either, we find a way to make it work inside threads (maybe there are some sort of thread ids?), or we just actively try to detect whether it is inside a thread (e.g. the thing is null, as the error says) and respond with something like "sorry, can not remind you from within a thread".

**Comment by Tais993** [comment]
It is possible, but I've to look into specifics before I can explain.
So if anyone is interested in fixing this, either @ me or try it yourself \:p

We need to get the ID from the channel (which is possible iirc)
After this, if the channel isn't found when sending the reminder, we have to manually send a request (using JDA internals; Route)

**Comment by Tais993** [comment]
With #420 (funny number) being implemented, this shouldn't be an issue anymore.
Once released and tested this can be closed

**Comment by Zabuzard** [comment]
@Tais993 Is it autofixed, or do we have to do minor adjustments in the code still?

**Comment by Tais993** [comment]
Should be auto-fixed (but gotta verify that)

**Comment by Tais993** [comment]
Unfortunately it's not auto-fixed, should've looked at that when reviewing our code.
#422 changes the type from TextChannel to MessageChannel, this fixes that issue and after merge it'll be fixed.
