### ISSUE TITLE
Autoreact on suggestions doesnt handle blocked users gracefully

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#406]
## Overview

If someone blocks our TJ-Bot, it can not react on their suggestions. Right now, the code throws exceptions in that case:

![log](https://i.imgur.com/QCdPhuC.png)

## Proposed action

While we probably can not really work around that easily with the current system, we should at least handle this situation gracefully and not crash.

**Comment by Tais993** [comment]
There's no bypass, therefor we have to ignore this error.

**Comment by MaiTheLord** [comment]
I'll start working on that. do we just want to ignore it, or log it with the logger?

**Comment by Tais993** [comment]
I'd just ignore it

**Comment by Zabuzard** [comment]
Ignore is fine. Or debug log if you really want to.

**Comment by MaiTheLord** [comment]
I don't care, really. whatever you want.
