### ISSUE TITLE
Upgrading to alpha JDA v5 builds

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#407]
**Is your feature request related to a problem? Please describe.**
Currently, we're waiting for the "full" release of JDA v5.

While that makes sense, it means we've to wait a lot longer till we can try certain things.

**Describe the solution you'd like**
Usage of JDAv5 alpha builds.

**Describe alternatives you've considered**
Switching wrapper,
While this results in having more features, the "dev" branch (alpha builds) of JDA are still ahead from the competition according to [this site](https://libs.advaith.io/#java), this is open source and anyone can update their library on [the GitHub](https://github.com/advaith1/libs)

Creating our own wrapper
Takes immense amount of time and resources we don't have, and will limit possibilities of switching back to another library drastically.

**Additional context**
Some more info on what it means to update to the "alpha" builds.

The "alpha" builds aren't unstable, they are just stable releases. But after every upgrade, breaking changes might happen.
This isn't much of an issue, since they don't take a lot of time to fix, and @Tais993 will fix them for you within seconds. :p
Using these alpha builds can give us access to features which might not come for another month or 2/3.

See the website I linked above, the alpha builds have:
Thread, context, autocomplete and timeout support.

Modals and scheduled events are both finished but waiting for review, these will come soon too.

So I'm asking for your vote, upgrade to alpha, or wait a few more months so many issues stay blocked?

**Blocked issues**

#408 
#405 (unless you want to waste a lot of time adding support yourself)
#401
#367 
#306 

Ignoring all the minor improvements and the things that haven't received an issue yet

### 👎, no wait till full release

**Comment by Tais993** [comment]
> Together with the fact that its Alpha cause it might contain bugs still ...

I mentioned in my issue, that the alpha builds are just stable releases, nothing is different from a normal version upgrade.
Only difference is that changes can happen to JDA (easily fixable)

> Dunno. Its not like we are actually wasting time on implementing dead features right now. 

We more or less are, many fixes, fix an issue that doesn't exist in the future.

> But I also didnt really have the feeling that anyone feels like having nothing to do

See above, yeah there's plenty of enhancements and bug fixes to make, but I personally find it a waste of time knowing we can also just spent the same amount of time for actual suggestions that don't have that issue.

**Comment by Tais993** [comment]
Since I doubt anyone else will comment, can I make the call or will we wait?

**Comment by Zabuzard** [comment]
@Tais993 Go ahead.

**Comment by Tais993** [comment]
#420 (funny number) has implemented this
