### ISSUE TITLE
Remove code duplication on temp mod role revocation failure

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#414]
## Overview

Sonar correctly flags this as code duplication:

![sonar](https://i.imgur.com/IFCJVew.png)

We should unify this section. Maybe move it into `ModerationUtils` as a helper like "handle temporary moderation role revocation failure" or similar.

It is currently causing our quality gate to fail (since I made some adjustments on its strictness)

**Comment by Tais993** [comment]
I honestly disagree, just like you used to, see [here](https://github.com/Together-Java/TJ-Bot/pull/398#issuecomment-1049775154).

They aren't the same thing, and nothing is wrong with handling them differently.
I rather see a way to suppress them than "fix" them.

**Comment by MaiTheLord** [comment]
I looked a bit into it, and if we want to move the method into `ModerationUtils` we'll have to make `RevocableModerationAction` public. another alternative is to make the method a static method of `RevocableModerationAction`.

**Comment by Tais993** [comment]
> another alternative is to make the method a static method of RevocableModerationAction.

Doesn't sound like a good idea, it probably makes a lot more sense to become an utility emthod in ModerationUtils

**Comment by MaiTheLord** [comment]
I agree, it sounds a bit sketchy, I just wanted to point it out :) the thing is, this logic is (and will probably stay) exclusive to `RevocableModerationAction`'s implementations, as far as I can see.

**Comment by Zabuzard** [comment]
Should probably end up as utiltiy in the temp mod package thing.

**Comment by MaiTheLord** [comment]
In a completely new class?

**Comment by Zabuzard** [comment]
Sure, why not. Or just make it public in the moderation util. I dont really see a big issue here. Its a bit unfortunate that there is no concept of "subpackage visibility" but it is what it is. The ModUtils helper is only really meaningful for mod stuff anyways and there are already classes outside of the package using it, no? Doesnt really hurt if the subpackage `mod/temp` also starts using it, imo.

**Comment by MaiTheLord** [comment]
I'll look into it.
