### ISSUE TITLE
Switching to timeout for mute

### ISSUE THREAD

**Issue by hhuucckk588** [Together-Java/TJ-Bot#416]
I really recommend to switch from using a role for mute to the built-in feature timeout instead

- You don't need to check if someone needs to be unmuted you just set a time to the timeout (with bots you can also set an exact time not like the client)

- You don't need to make the bot give back the mute role if someone leave the server and return because timeout already does that

- You don't need to setup yourself all the possible errors you can just use the errors the library gives you

- You don't need to make sure the mute role doesn't have a permission to send messages. there won't be any mute role

- It's more clean in my perspective to give timeout compared to give a mute role

**Comment by Zabuzard** [comment]
Are you talking about Discords newly added timeout feature? Do we actually already have utility for that in JDA?

Note that even if we replace mute with discord timeouts, we wont get rid of the stuff ur mentioning. There are other role-based actions, such as `Quarantine` which will still need all of this logic, even if mute is gone.

**Comment by Zabuzard** [comment]
On that note, something small that people usually dont know: Our mute is not just a timeout, u can actually still write in the `#spam` channel. And you also get a little 👀 icon next to ur name.

**Comment by Zabuzard** [comment]
So its blocked by the alpha JDA update

**Comment by Zabuzard** [comment]
Blocked by #407

**Comment by hhuucckk588** [comment]
from what i know
timeout is supported by jda in the last builds of the 4 releases so it doesn't need to be the alpha but i can be wrong

**Comment by Tais993** [comment]
The last feature addition was 4.4, 26 November. Member time-outs have been added in alpha 4, which is 10 January.
Development on 4 has been stopped for some time now, so no that information is incorrect.
