### ISSUE TITLE
`commands` package should be named `features`

### ISSUE THREAD

**Issue by MaiTheLord** [Together-Java/TJ-Bot#418]
Right now, almost every feature is in the `commands` package, which makes its name misleading.
we should rename it to `features`, and delete packages like `routines`, and instead have their classes moved into `features`.

**Comment by Zabuzard** [comment]
The package split right now is a mess. It makes no sense (and is bad) to split on what type it is. We have to split on topic (see `moderation` for example). Majority of classes like routines are in their respective topic-package instead right now.

The commands package is misnamed (cause we didnt know better back then). It should be renamed to `features`.

**Comment by MaiTheLord** [comment]
I see. that makes a lot of sense, actually. should I close the issue?

**Comment by Zabuzard** [comment]
(now would be a good time to do this - @Taz03 if ur still interested)
