### ISSUE TITLE
Active and Very Active role

### ISSUE THREAD

**Issue by illuminator3** [Together-Java/TJ-Bot#437]
Roles that are automatically assigned to people who have N (for active) or sqrt(8)*N (for very active) amount of messages in N days.

**Comment by Zabuzard** [comment]
Anything related to those roles or just roles for the lulz?

Im okay with the roles.

**Comment by Zabuzard** [comment]
Closed due to no real design/motivation.

**Comment by illuminator3** [comment]
could be rewarding towards people that are active on our server, but don't really help (thus not giving them the top helper role)
