### ISSUE TITLE
Unit/Integration Tests

### ISSUE THREAD

**Issue by Nincodedo** [Together-Java/TJ-Bot#44]
**Describe the solution you'd like**
Implementing unit tests early in the project may show some benefits to keeping code quality high.

I leave it to the maintainers to pick frameworks, but my suggestion would be JUnit 5 for unit testing, and Mockito/Testcontainers for integration testing.

**Comment by RicardoMonteiroSimoes** [comment]
Agree on both, also because automating them with Actions is pretty easy

**Comment by Zabuzard** [comment]
I think for now we just need JUnit 5, which is already in the project. (Also, there is a simple "hello world" test `Assert.assertTrue(true);` to get started).

I think we hav eto wait for the command system now before we can talk about proper unit testing structures.

**Comment by Zabuzard** [comment]
Blocked by #59
