### ISSUE TITLE
Update wiki tutorial for local TJ-Bot setup

### ISSUE THREAD

**Issue by lpranjic** [Together-Java/TJ-Bot#442]
At the end of the _Setup project locally_ section, in the [Have fun](https://github.com/Together-Java/TJ-Bot/wiki/Setup-project-locally#have-fun) subsection, a short ping-pong demo is given to test that the bot has been successfully deployed. The most current version of the bot only offers interaction with users through slash commands, text commands are unsupported. The current ping-pong demo needs to be replaced with an equivalent demo using slash commands.

Furthermore, there is no mention in the said tutorial that the slash command `/reload` needs to be used when the bot joins a server for the first time. Also, once the bot has joined the server (assuming it was already running before it joined the guild) it needs to be restarted so that the `onReady` method in the class `BotCore` gets triggered so that the slash command `/reload` gets added to the guild.

**Comment by Zabuzard** [comment]
Good stuff. Thanks. The tutorial has been written before the bot core system has been developed 👌
