### ISSUE TITLE
Create thread-based help system

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#444]
## Overview

We want to introduce a new help system that is thread-based. The general idea is that we have a staging channel where people can use a slash command like:
```java
/ask title: Fix da NullPointerException plzzzz tags: java, framework
```
and it would then create a thread for this question under the staging channel.

The asker could then formulate their full question in the thread and helpers can help. Once the issue is solved, the thread would be closed/archived.

### Tags

Our existing tag-like channel system could be migrated into this new system by actually introducing tags which can be selected by the asker (or manipulated later by the community).

We could then introduce tag specific roles, like `Helper-Java`, `Helper-Framework` and the bot would auto-add them to threads with the corresponding tags.

### Staging channel

The staging channel would give an explanation of how to ask questions and give helpers an overview of all currently open/active threads (sorted by tags maybe)

### Auto-free

Threads could be auto-closed/archived after maybe 12h of inactivity. Maybe this can even be bumped, now that everyone has their own channels anyways.

### Top helpers

Help threads need to be tracked somehow. Its unclear if a database is needed for that, maybe it is already enough that they are threads under the staging channel. That way, we can identify message count in them and continue using our existing top helper system.

### Extra assistance for ~~stupid users~~

We suspect that people will likely not understand how to use `/ask` and just post messages directly into the chat instead. It might be better to offer a message listener and auto-convert any posted message into a thread instead and then delete it from there.

This might require some fine tuning though in case people multi-post quickly, like "hi", "i have a question", "here it is:", "...".

This is just an idea though, the problem can be bypassed by not granting users the permission to send messages but just use slash commands.

## Forms

The system should be created abstract enough that it could potentially easily be migrated from a thread-based to form-based model instead, once forms arrive.

**Comment by Tais993** [comment]
Does "forms" refer to "forum channels" or modals?

**Comment by Zabuzard** [comment]
@Tais993 Not quite sure. Afaik you showed some pics with dialogs where the user could also directly enter their question in a nice window.

The problem with slash-command `/ask title: huhu` is that we cant really also let them put their question in their (it would be way too long for a slash command).

So some sort of popup window where they can enter their question directly in a dialog would be neat.

**Comment by Tais993** [comment]
Alright modals, just wanted to be sure since forum channels have also appeared.

Main bottleneck is command system rework, no promises on when that'll be finished

**Comment by java-coding-prodigy** [comment]
We should allow the asker to reopen the thread for follow up questions.
For this, the bot can send a message with a button that can only be activated by the ask er and it reopens the thread.
