### ISSUE TITLE
Create algorithm to classify a post as question or not

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [Together-Java/TJ-Bot#461]
Coming from this suggestion here:
https://discord.com/channels/272761734820003841/987648024132063242

The idea behind it is that the bot automatically checks incoming messages and correctly classifies them as either a question or not. In the case that they are a question, it should delete them and notify the user of it.

**Describe the solution you'd like**
The best solution, known to me, would be using some form of NLP system trained on a good dataset.  This means that each message the bot receives would be passed to a trained algorithm and the resulting probability used to handle the message, _or not_. 

Problem arises at differentiating between the channels that have this function and which haven't. It is completely fine to ask a question during a normal discussion, but this would mean there are too many situations where it's not active, but still somewhat relevant. 

Context wise it's relatively hard to build something that can distinguish and use context of current conversations to evaluate if the post is a real question that needs answer or a contextual question.

In addition to this, it's hard to come up with a usable dataset. Specially considering it's programming related questions.

**Describe alternatives you've considered**

There aren't really any usable alternatives, except some made up algorithms that somewhat analyse a string, but still face the same concerns as stated above.

**Additional context**

I'd suggest not to go down this route, and to rather implement some form of locking new users to channels where they have to correctly submit some question as an example, which then is parsed and checked. If correct, they will be allowed to see the rest of the server.

**Comment by marko-radosavljevic** [comment]
> I'd suggest not to go down this route

Agree, seems highly improbable to create accurate classifier for a specific subset of programming questions. Especially with our resources, and very limited datasets that we have available.

> implement some form of locking new users to channels where they have to correctly submit some question as an example, which then is parsed and checked. If correct, they will be allowed to see the rest of the server.

I can imagine a system like that that's not terribly unfriendly and has a relatively low barrier to entry. And we could replace our current pop-ups in favor of it. Although, I envision it more as an interactive bot guidance than rule quizzing. Have to play a bit with the idea to see what kind of UX is achievable.

**Comment by Zabuzard** [comment]
The last part, with the "answer this quiz to enter" is actually a feature that is provided by Discord itself _soon TM_.

Dont know when, but I was hoping to just use it to get a build-in experience from Discord realizing exactly that. "Before you enter the server, please answer the following question: ..."

**Comment by RicardoMonteiroSimoes** [comment]
Well in that regard, that's excellent. So we will just have to wait and see, and in the meantime any similar suggestions can just point here :)
