### ISSUE TITLE
Auto creation of threads in suggestion channel

### ISSUE THREAD

**Issue by Tanish-Azad** [Together-Java/TJ-Bot#468]
Right now the bot adds up and down reaction on every message also on messages where someone created a thread. Ex:-
![image](https://user-images.githubusercontent.com/73871477/179608524-e884f65e-b85d-4d58-a38e-b367c4948c49.png)

**Describe the solution you'd like**
Let the bot create a thread for each suggestion and rest discussion will go inside it

**Describe alternatives you've considered**
Analyse the message if it is an thread created message then don't add reactions to it

**Comment by Zabuzard** [comment]
Related and almost duplicate: https://github.com/Together-Java/TJ-Bot/issues/401

**Comment by Zabuzard** [comment]
But sure, good suggestion.

**Comment by Tanish-Azad** [comment]
Hmm yes, so what should i do close this issue?

**Comment by Zabuzard** [comment]
No, they kinda talk about different ways to go about the issue. They are mutually exclusive though. So whichever is implemented first should close the other, I guess.

**Comment by Tanish-Azad** [comment]
What do u think will be a better solution for this problem?

**Comment by Tanish-Azad** [comment]
I can do the implementation

**Comment by Zabuzard** [comment]
Yes, I like the idea of auto-thread creation for this. Feel free to get started if you want. Would be nice :)

**Comment by Tanish-Azad** [comment]
can u assign me for this issue

**Comment by Tanish-Azad** [comment]
#469
