### ISSUE TITLE
What is the enum utility pattern?

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#470]
https://github.com/Together-Java/TJ-Bot/blob/9305cd08066678544973514ab827d07456c06684/application/src/main/java/org/togetherjava/tjbot/Application.java#L28

what is this for?

**Comment by Zabuzard** [comment]
To end the enum. This is an enum-utility-class pattern.
```java
enum UtilityClass {
  ;

  ... // code
}
```
It is essentially the same as
```java
class UtilityClass {
  private UtilityClass() {
    throw new UnsupportedOperationException("UtilityClass");
  }

  ... // code
}
```
just a tad "safer".

We kinda settled on picking this pattern in the beginning but it seems to confuse so many people that we would actually want to change it. But it should be changed everywhere in the code base then, in one refactoring.

**Comment by Tanish-Azad** [comment]
i feel like it should be like it is for now
