### ISSUE TITLE
Auto-pin first message in help threads

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#479]
The bot should automatically pin the first message in help threads, this is usually the OPs question, or directly next to it.

Makes it easier for people to navigate in a help thread if they can just jump all the way up.

Implementation-wise, this could be added directly into the flow of `AskCommand.java` and `ImplicitAskListener.java`, where it also creates the threads and posts the first automatic messages.

**Comment by GeRmAnImAl** [comment]
Can you please assign this to me?

**Comment by Taz03** [comment]
@GeRmAnImAl hey, whats the progress on this??

**Comment by GeRmAnImAl** [comment]
@Taz03 apologies, I've not been able to work on this as of yet due to University commitments. If this needs to be reassigned to someone else I totally understand.

**Comment by Zabuzard** [comment]
@GeRmAnImAl no worries. how about we unassign u and as soon as u have time again, u can be assigned again? :)
