### ISSUE TITLE
Which database framework to use?

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#48]
Our bot will need a database. Regardless of the actual database being used (SQLite, ...), we should decide for the actual user facing framework first.

Goals are to keep it simple for newcomers to work with, but also not too cumbersome and bloated at the same time.

Some proposals:

- JDBC
- Hibernate
- JPA
- jOOQ
- MyBatis
- Jdbi
- fluent-jdbc
- Spring JDBC
- Spring Data JPA

**Comment by Zabuzard** [comment]
I do **not** want to use:

- JDBC, its way too bloated and generally annoying
- Spring, Spring is cool but its too much black magic for beginners, I do not want to open pandoras box (Spring) unless needed

I do not know too much about the rest but I prefer something that still looks similar to basic SQL, since that might actually be beginner friendly due to less black magic.

So basically just JDBC but without the annoying cumbersome bloat would be my favorite.
**jOOQ** looked like a good fit to me at first glance.

**Comment by I-Al-Istannen** [comment]
I quite like jOOQ as it mostly gets out of the way and just provides a slightly more convenient - and typesafe! - interface over standard sql. It achieves this by generating a java model of a database at compile time and you can then code against that model.

jOOQ needs a database at compile time it can use to generate its java classes from. So we'd need to pair that up with Flyway (or something similar), which is probably a good idea anyways.

We would then write plain SQL migration scripts to bring up our database and incrementally migrate it to new versions as needed. During build we can bring up a database from scratch and run jOOQ on it to generate all necessary types.

This also ensures that if we introduce any breaking change in a migration we would get compile-time errors for them as the newly generated jOOQ code is no longer compatible.

**Comment by d3vel0per** [comment]
+1 for jOOQ and JDBC
jOOQ is great for typesafety
JDBC well you are as close to the database as you can get

Along with other tools as Istannen mentioned viz. flyway/liquibase, it really eases the developmental flows. Also I would want to bring to notice that jOOQ in terms of syntax is very close to ANSI SQL hence you need to be comfortable with it anyways. There isnt JPA like black magic.

NB: If you ever get into a project where you need to develop fluent API's, jOOQ is the best reference. Luke has done a great job with it!

**Comment by Zabuzard** [comment]
Then its settled. We will use Flyway + jOOQ. I am spawning a task to migrate the current JDBC+SQlite example commands to that tech stack.
