### ISSUE TITLE
Auto-close help thread if OP leaves server

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#480]
Sometimes question askers leave the server while their question is still active. This leads to helpers wasting time, not knowing that OP left already.

Hence, the bot should react to the event of people leaving the server and check if there are any question threads created by them. If so, close them (see how `/close` works).

Implementation-wise, challenges here are that we do not associate help-threads to authors yet. The person implementing this has to explore:
* can we easily automatically derive the thread author? (probably not?)
* otherwise, we should maybe setup a small database that associates thread channel IDs with author IDs (auto-evicted every week or so)

For latter, there are already similar setups for the top-helper system. Can copy pasta some stuff.

**Comment by mikerasch** [comment]
I intend on working on this. Hopefully will be done today :)

**Comment by Zabuzard** [comment]
> I intend on working on this. Hopefully will be done today :)

Awesome. Enjoy :)
