### ISSUE TITLE
Auto-post advice on empty help threads

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#481]
Sometimes new users create a help thread and then dont post any details in it.

In such a situation, the bot should (after some waiting time, maybe 5 minutes) post a message where it pings the author and asks them to post some details, shortly explaining how the system works.

This could be setup as scheduled task, scheduled by `ImplictAskListener.java` and `AskCommand.java` (via a separate helper class). Where we could schedule this "explain-job" in 5 minutes after creating the threads. The job would then check the thread history to see if there are any messages already (other than from the bot) - and if not, it would post this message.

Also, we would have to setup a small database to memorize help thread channel ID <-> author ID in order to be able to know who to ping.

**Comment by mikerasch** [comment]
We could potentially use the current database implemented where it removes the thread if a member leaves the guild.

**Comment by Zabuzard** [comment]
Yes, thats the plan. Hence the:

> Also, we would have to setup a small database to memorize help thread channel ID <-> author ID in order to be able to know who to ping.

🧠 👍

**Comment by java-coding-prodigy** [comment]
I think I will do this

**Comment by java-coding-prodigy** [comment]
I will make this functionality

**Comment by marko-radosavljevic** [comment]
Any progress on this feature @java-coding-prodigy? ^^

**Comment by java-coding-prodigy** [comment]
Oops I totally forgot about this!
I had worked  on this previously but I can conplete it now.
I was unsure whether I would have to use a ScheduledFuture or if the RestAction API provides the required functionality, could someone please clarify that bit?

**Comment by Tais993** [comment]
Just use a ScheduledExecutor, where you run it after 5 minutes, and in there you do the check whenever you've to post advice.

**Comment by Zabuzard** [comment]
we already have a similar feature that u can copy pasta. we auto-post advice on selecting a category for questions in `ImplicitAskListener`. it runs as a scheduled task, 5 minutes after creation.
