### ISSUE TITLE
Forbid posting exe files

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#484]
The bot should react to any message with attached media and check if it ends on a blacklisted file extension (such as `.exe`).

Such posts should then be deleted and the bot should inform the user that the file is not allowed for sharing.

For a good UX, we should DM the original message to the user after deleting it, so that it is not fully lost and they can copy-adjust-paste-again instead of having to fully type it out from memory.

Also, the bot should warn moderations about this and give them a copy of the message. This could be done using the `ModAuditLogHelper` or whatever the helper class was called.

**Comment by Mom0aut** [comment]
Hello Could you assign this to me ? 😄

**Comment by Zabuzard** [comment]
Sure thing, enjoy :)

**Comment by Mom0aut** [comment]
Is it rly useful to send the mods an suspicious exe attachment? I would inform the mods that the user sent an Media with blacklistedFileExtension, if you are oke with this?

**Comment by Zabuzard** [comment]
Definitely. I never intended receiving any actual attachments. It is enough to forward the message itself, without the media.

Both should receive a copy of the text-message (without media):
* the user via DM, so that their message is not lost to them, in case they want to rewrite it
* the mods, so that they 1. know what happened, 2. have a record of the message in case they need to do further actions (such as banning), 3. can identify false-positive alerts and adjust the bot
