### ISSUE TITLE
Only allow media-posts in #memes

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#485]
The `#memes` channel is supposed to only contain posts that include any media (pictures, videos, ... funny stuff).

As of today, moderators manually ensure that by just deleting all other messages. Not only does that generate annoying work for mods, but also does it not teach users about what they did wrong - to prevent it from happening again.

The solution would be a `MessageListener` (listening on messages in the meme channel, e.g. using `MessageListenerAdapter`) that checks whether a message has media attached. If not, it is deleted and the bot writes the user a DM, telling them what they did wrong.

**Comment by Mom0aut** [comment]
Hello could you assign this to me ?

**Comment by Zabuzard** [comment]
Sure thing, enjoy :)

**Comment by Mom0aut** [comment]
Ty, is it oke that the MessageLister allows Media attached and Embedded Message with Links (9.gag, youtube, etc) ?
Otherwise posted Links in Emebed Messages would be delted.

**Comment by Zabuzard** [comment]
> Ty, is it oke that the MessageLister allows Media attached and Embedded Messages with Links (9.gag, youtube, etc) ? Otherwise posted Links in Emebed Messages would be delted.

links are cool, yes. doesnt have to be a fancy detection, a simple `contains("http")` would technically be enough for our needs already, to be honest

**Comment by marko-radosavljevic** [comment]
We probably also want the same behaviour in #educational_media, message should contain either a link or a media.

Just something to keep in mind while designing this feature. Making it easily extensible to support other channels as well.

If we all agree, we can also add #educatonal_media right away, since it's a clear-cut contender in my opinion.
