### ISSUE TITLE
Which License to use?

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#5]
Which license should we pick for this repository?

What about:

1. [GPL 3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))
2. [MIT](https://tldrlegal.com/license/mit-license)
3. [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))

Other proposals are also welcome!

**Comment by Zabuzard** [comment]
I prefer **GPL 3** due to the copyleft aspect.

**Comment by Zabuzard** [comment]
From @illuminator3 :
> [Unlicense](https://unlicense.org/) so that there are basically no restrictions and anyone can use the source code like they want. This would make sense since we're already an open community, accepting everyone to contribute.

**Comment by d3vel0per** [comment]
+1 for copyleft licenses

**Comment by marko-radosavljevic** [comment]
> Unlicense so that there are basically no restrictions and anyone can use the source code like they want. This would make sense since we're already an open community, accepting everyone to contribute.

GPL v3 allows all the openness, it's a real open-source license. Everyone can contribute and use code however they want. The only restriction is changing the license to a private one.

The idea is to keep open-source projects open, so that every contribution or upgrade gets back to the community.

> The licenses were originally written by Richard Stallman, founder of the Free Software Foundation (FSF), for the GNU Project.

It can't be more free, libre and open-source than Richard Stallman libre. ^^

**Comment by LovinLifee** [comment]
I am all for inclusiveness, I think anybody should be able to download, modify, and use for commercial or non commercial applications but I don't think people should be able to sublicense. I'm leaning more towards GPL3, if not we just say 'F' it and use unlicense. Either very little restrictions or none at all IMO.

**Comment by Zabuzard** [comment]
We will start with **GPL v3** until the community has a strong preference to change.
