### ISSUE TITLE
Add Context-Menu support (JDA)

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#51]
Context menu's are released, just not in JDA officially.
The current PR is on freeze because it contains breaking changes, the PR will be merged in JDA-5
While the current context menu branch is fully up-to-date with JDA, and it's finished.

**Describe the solution you'd like**
Changing JDA to one of the latest commits of [this PR ](https://github.com/DV8FromTheWorld/JDA/pull/1769)/ [this branch](https://github.com/aasmart/JDA/tree/feature/context-menus)

**Describe alternatives you've considered**
Waiting, but waiting is boring.

**Additional context**
Context menus be kinda cute

**Comment by Zabuzard** [comment]
Does this mean we would switch to an "_unofficial_" version of JDA?

**Comment by Tais993** [comment]
Correct it's unofficial.
Regardless, it's stable and fully working.

Only reason it's on freeze is because JDA delays breaking changes to a bigger update, which will be JDA 5 (currently JDA 4.3.0)

Understandable if this won't happen.

**Comment by Zabuzard** [comment]
Fair. This issue has no priority as of now but might get relevant soon after reaching milestone **Initial Setup**.

**Comment by Tais993** [comment]
Context menus are commands, that's why I mentioned this since we're building a command system, which might receive some breaking changes when we will support context menus.

**Comment by d3vel0per** [comment]
Have the API's been frozen as well since we would be jumping on an unofficial version.

**Comment by Tais993** [comment]
What do you mean?
