### ISSUE TITLE
Disable the commands in unvalid channels

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#512]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just an enhancement. I saw many commands have usage in specific channel and it managed in the code that in which channel it is visible. Which makes the code longer and hard to understand and maintain.

**Describe the solution you'd like**
Use discord Integration settings to manage where the command can be used. This way we can make the code concise and won't loose any functionality.
This also comes with some benefits like right now the bot will send a message saying something along the lines of the commands can't be used here, but if a command is blocked from discord integration settings it won't be even visible in unnecessary channels

**Additional context**
https://github.com/Together-Java/TJ-Bot/blob/e7e98f068cf95aebd3135ac4445a48481e2a05c6/application/src/main/java/org/togetherjava/tjbot/commands/help/ChangeHelpCategoryCommand.java#L74-L76

Current Behaviour:-
![image](https://user-images.githubusercontent.com/73871477/184528203-1f5addc5-6c8c-4899-9225-797b60aa5eb0.png)

After disabling the command from integration settings:-
![image](https://user-images.githubusercontent.com/73871477/184528240-542bf29a-a468-4918-8083-fcb09f2cb8e9.png)

**Comment by Taz03** [comment]
![image](https://user-images.githubusercontent.com/73871477/184528346-6687edb2-085a-4fe4-840b-a1dec33a73e5.png)
![image](https://user-images.githubusercontent.com/73871477/184528398-56d08eb1-3693-4bde-ac1c-6a9aaec16087.png)

**Comment by Zabuzard** [comment]
The integration settings are already used for our commands in the server. I would still like to keep the code checks though.

**Comment by Zabuzard** [comment]
As you can see here for example:

![snap](https://i.imgur.com/t4DOcKd.png)

**Comment by Taz03** [comment]
> I would still like to keep the code checks though

any reasons for doing that?

**Comment by Taz03** [comment]
> I would still like to keep the code checks though

any reasons for doing that?

**Comment by Taz03** [comment]
> As you can see here for example:
> 
> ![snap](https://camo.githubusercontent.com/a18ac516710b6d4a20a8a38ebfaab8c268222dcf9bd2df6959e4bd3eecbc88f5/68747470733a2f2f692e696d6775722e636f6d2f7434444f634b642e706e67)

should do this for `/change-help-category`, `/change-help-title` and `/close` too

**Comment by Taz03** [comment]
> The integration settings are already used for our commands in the server. I would still like to keep the code checks though.

It makes the code verbose by checking for cases which are never true

**Comment by Zabuzard** [comment]
You can not do this for the help commands, since they are used in thread channels. I doubt it would work if you select the root channel there, would it?

Be aware that this Discord integration setup thing is a very recent thing and was not available when the code was written. And it was, until recently, still in BETA (and hence not available to all servers). That said, we can probably start removing some of the checks now.

**Comment by Taz03** [comment]
> I doubt it would work if you select the root channel there, would it?

yes
