### ISSUE TITLE
Unknown class referenced

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#513]
https://github.com/Together-Java/TJ-Bot/blob/5e71489845fd72cd9f5136c38826dc3c523b4866/application/src/main/java/org/togetherjava/tjbot/Application.java#L23

`net.dv8tion.jda.api.events.interaction.SlashCommandInteractionEvent` does not exist

**Comment by Zabuzard** [comment]
Yes. There was some renaming/refactoring and this part apparently broke (also elsewhere in the code). Should be fixed.
