### ISSUE TITLE
Upgrade JDA to alpha 18

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#536]
We are using JDA5-alpha 9 which is kind of old now and the JDA don't provide support for docs of old version of JDA so, it might be confusing for new contributors when they can't find the docs.

Also alpha 18 comes with 2 reworks:-
Emote rework
Message rework
    So, we'll need to do the necessary changes after upgrading the JDA version

In alpha 13 we got a new method `CommandData.setGuildOnly(boolean)` by which we can make a command guild only, and won't need to do it the way we are doing it rn(with `SlashCommandVisiblity`), this method is much more simpler and easy to understand. This can be done in a separate issue/pr

**Comment by Zabuzard** [comment]
> In alpha 13 we got a new method CommandData.setGuildOnly(boolean) by which we can make a command guild only, and won't need to do it the way we are doing it rn(with SlashCommandVisiblity)

I dont see why this justifies removal of `SlashCommandVisibility`. It still serves purpose, it is a required argument for slash commands and `SlashCommandAdapter` can take over the setup. So I would keep the enum but only remove the getter and the stuff in ReloadCommand for that. I.e.

```java
public SlashCommandAdapter(...visibility) {
  ...
  getData().setGuildOnly(visibility);
}

// Remove getVisibility(), not needed anymore
```

So for the actual slash commands that extend the adapter, nothing changes.

**Comment by Zabuzard** [comment]
Superseded by #586 586
