### ISSUE TITLE
Messages with linked media are blocked

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#543]
The recent PR #518 added functionality to disallow posts in `#memes` without media attached.

It works well, but there is an edge case it blocks, which it shouldnt. Namely if the message contains an URL (which Discord will then, later, transform into an attachment):

![message](https://i.imgur.com/HrxBScn.png)

The bot shouldnt block these. Its enough to check the message content for `http` and then allow it.

For reference, the affected classes are:
* `MediaOnlyChannelListener`
* `MediaOnlyChannelListenerTest`

**Comment by Zabuzard** [comment]
(for visibility: @Mom0aut )

**Comment by Mom0aut** [comment]
rly interesting in my local setup this worked fine, i will look into it
