### ISSUE TITLE
Add Question cooldown with command-advice

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#555]
## Problem

People frequently start creating multiple threads for the same question, because they do not understand the system (despite all the existing explanation).

For example, they do a typo in the title or forgot to post any message at all, or want to have a different category and so on. Instead of using the slash commands, they create a new thread.

## Solution

The bot should block such attempts (5 (?) minute cooldown) and additionally provide an explanation message how to use the slash-commands for adjusting the existing message.

A similar feature exists already for `ImplicitAskListener` which blocks attempts for a few seconds and links the user to their existing thread. This existing feature should just be improved, so that `AskCommand` also uses it, it lasts for 5 minutes instead of seconds, and it posts slash-command usage advice as well.

**Comment by Taz03** [comment]
y not just add a cooldown to the #ask_here channel

**Comment by Zabuzard** [comment]
> y not just add a cooldown to the #ask_here channel

You missed the most important point, the advice. Also see the suggestion thread in the server where I elaborated on this.
