### ISSUE TITLE
Use Guild#retrieveActiveThreads

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#560]
Seems Discord did some changes to threads and now JDA has to actually retrieve channels instead of just using the cache.

This causes some problems in our code, for example the active question list frequently gets out of date and misses some ghost threads.

We likely have to do the change also elsewhere in the code, we should check all places where we are working with channels. Unsure whether those methods are available in our current JDA version already, probably not. If thats the case, this feature is blocked until JDA is updated.

**Comment by Tais993** [comment]
I'm pretty sure that retrieving them once results in them being cached

**Comment by Zabuzard** [comment]
> 

The question is just what happens with threads created after the retrieve. How do those threads end up being ghosts in the first place? It seems its not safe to rely on the cache anymore, we probably have to do a retrieve on each usage, no?

**Comment by Tais993** [comment]
Can't you just do some research and check what caused it?

I'm giving you some info, but you're drawing conclusions way too fast, I don't like the "lets make it complicated" idea.

**Comment by Zabuzard** [comment]
I mostly created this GH issue to not forget about this topic. I was under the impression that its clear that this caused the problem, feel free to adjust it.

**Comment by Tais993** [comment]
Alright, I'll do research on it then and update once I know more

**Comment by Tais993** [comment]
Seems Discord was buggy, which also caused it people on phone couldn't see many threads.

It's been resolved since, so no need for this anymore
