### ISSUE TITLE
Closing archived threads doesnt work anymore

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#562]
This feature in the code (`CloseCommand`):

![feature](https://i.imgur.com/vgMFumn.png)

Doesnt work anymore. It triggers the following exception:

![issue](https://i.imgur.com/EUTS7Vq.png)

It seems that Discord allows using the slash command `/close` in a closed channel, but doesnt allow the bot to respond to it.

Not quite sure how to approach it yet though.

**Comment by Gyoo** [comment]
How do you reproduce this issue ? When I try to send `/close`to a closed thread, the thread automatically reopens itself before being closed again by the bot

**Comment by Zabuzard** [comment]
> How do you reproduce this issue ? When I try to send `/close`to a closed thread, the thread automatically reopens itself before being closed again by the bot

Regardless of exception, the behavior ur describing isnt really nice either. Anyways, its likely that some of the flakyness for this was just due to Discord bugs during their recent updates.

Maybe some of the issues are gone already or changed. Id suggest you have a quick investigate of the current UX for this situation and see if u can improve it. If not, we close the issue 🤷

**Comment by Gyoo** [comment]
In that specific case, when I want to close a thread manually, I also have an option to "close and lock thread" (not sure how it's labeled in english, I use Discord in french). If we can do something similar directly from the bot, then users shouldn't be able to `/close` again

**Comment by Zabuzard** [comment]
> In that specific case, when I want to close a thread manually, I also have an option to "close and lock thread" (not sure how it's labeled in english, I use Discord in french). If we can do something similar directly from the bot, then users shouldn't be able to `/close` again

But then users also cant reopen it anymore by simply typing something. Its really just about either preventing people from using `/close` when its archived, or at least having a proper experience when its done (no exceptions, no confusion, ...)

**Comment by Zabuzard** [comment]
retested. the command now opens the thread and then closes it again. discarding this issue
