### ISSUE TITLE
Add "how to link Sonarlint with Sonarcloud" to the wiki

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#566]
**Is your feature request related to a problem? Please describe.**
People have to push to see all warnings Sonarcloud will give, which results in notification spam in the Discord, and a horrible experience as a developer.

**Describe the solution you'd like**
Explanation of how to link your local Sonarlink to Sonarcloud in the Wiki

**Describe alternatives you've considered**
Manually setting ruleset, or taking a look at all warnings.

But this is in my personal opinion still a waste of time, when connecting Sonarcloud takes mere seconds, and provides the (a still limited) experience without any downsides.

**Additional context**

**Comment by marko-radosavljevic** [comment]
Added [Connect SonarLint extension to our SonarCloud](https://github.com/Together-Java/TJ-Bot/wiki/Connect-SonarLint-extension-to-our-SonarCloud) page to the wiki.

Feel free to suggest changes, or improve it further yourself :relaxed:
