### ISSUE TITLE
Bookmark question thread command

### ISSUE THREAD

**Issue by marko-radosavljevic** [Together-Java/TJ-Bot#570]
## Is your feature request related to a problem? Please describe.

Currently, there are no ways to 'follow' a question thread to track answers to the question or have an automated way of saving a link to the question thread discussion for later review.

## Describe the solution you'd like

A command such as `/bookmark` or `/save` so that the bot can DM the user with the thread link (which can be obtained from the thread ID and can be referred with `<#(the threadID)>`).

For saving some context about each bookmark, implementors may decide to include the first message sent by the thread author after thread creation (assumed as the main question). Issue is that question can be scattered trough 20 messages, with images etc. And since a question can often be poorly titled, having just a title is not enough.

So probably the best bet is to have an optional `tag` or `memo` option for the slash command, so users can organize their bookmark list with a personalized tag. It's searchable, and it can be used as a reminder what the question was about, thus correcting for poorly titled questions.

## Describe alternatives you've considered

Manually do it.

<sub>(Originally suggested by voidcorruptor)</sub>

**Comment by Taz03** [comment]
so a slash command `/bookmark` with db storing bookmarks of each user is the best idea?

`/bookmark add`
`/bookmark remove`
`/bookmark list`

**Comment by Zabuzard** [comment]
That wasnt part of the request in this issue @Taz03 . They only wanted to be able to memorize a thread in their DMs, possibly with the first message or similar directly in the DM as embed - as quick overview.

**Comment by Tais993** [comment]
Zabu, that's not good UX either.

The bot sends you more DMs -> you end up having to scroll for the message.

And how can you remove threads then? 

I'd imagine a proper implementation would be a lot more useful. @marko-radosavljevic just created this issue because someone suggested it. I don't think the suggestion was meant to be final.

**Comment by Zabuzard** [comment]
fair. im okay with having a list per user. so a DB table that memorizes user ID -> list of channel IDs and then a few commands to manage these (add, remove, list). UX wise, i guess users would mostly want to add threads from within the thread. while list and removal will most likely be used mostly from within DMs.

ideally all commands could be used everywhere (global) and maybe add/remove would optionally take a channel as argument, such that, if its not given, they attempt to use the current channel - or similar.

its important that all interactions with this stuff are fully **ephemeral**.

**Comment by Nxllpointer** [comment]
I like the idea of this. My take on this idea would be to have an command that can add bookmarks and one to view them. The command to view them would not display all the bookmarked threads in one message but rather paginating them in order of activity. You would then have buttons to switch between bookmarks and remove the bookmark. The Bookmarks would also expire after like 3 days  without manual intervention.

**Comment by Nxllpointer** [comment]
Ok so I have played around with the code base a bit and I get along well with it. I have already created a command that creates and saves bookmarks. Could i be assigned to this feature? Someone just hast to check up on my SQL stuff because i have never used SQL before.

**Comment by Nxllpointer** [comment]
Progress is looking good. I can add bookmarks and the viewer pagination is also pretty functional and i just have to round up things on that. After that im gonna add a routine to clear unneccesairy data. Should be done by monday

**Comment by Nxllpointer** [comment]
Created a PR: #634
