### ISSUE TITLE
Bot sends advice on closed uncategorized help threads

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#571]
Bot sends advice on uncategorized help threads, even after the thread gets closed. This makes it open again

![image](https://user-images.githubusercontent.com/73871477/189575579-2dcd4722-14f4-4377-a46d-12e664259c18.png)

**Comment by Zabuzard** [comment]
A simple check whether the thread is already closed should do a trick. If closed, it can simply skip the action and not send anything.
