### ISSUE TITLE
Ping on response

### ISSUE THREAD

**Issue by Arbee4ever** [Together-Java/TJ-Bot#573]
**Is your feature request related to a problem? Please describe.**
I tend to forget to check the queston thread if someone has answered.

**Describe the solution you'd like**
A command that toggles the thread to ping me anytime someone sends an answer

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Taz03** [comment]
![2022-09-15_224045-251x196_scrot](https://user-images.githubusercontent.com/73871477/190468008-426e3a34-0497-4236-9a37-d7c9bcf397e7.png)

y not just set all messages in the notification settings. I don't feel like adding a meaning less feature is the right way to solve this issue

**Comment by Arbee4ever** [comment]
Because that doesn't pong me and only plays a sound when Im not on my Computer

**Comment by Taz03** [comment]
> Because that doesn't ping me and only plays a sound, so I dont notice it when Im not on my Computer

fix ur notification settings then

**Comment by Taz03** [comment]
> My notification settings are set up correctly, but I want it to add that ping badge to the channel, so I see it later

y not see ur inbox then?

**Comment by Arbee4ever** [comment]
Does anyone really use that feature?

**Comment by Taz03** [comment]
> Does anyone really use that feature?

yes

**Comment by Taz03** [comment]
also it makes no sense to avoid what discord already provides and asking to mess up thread channels

**Comment by Zabuzard** [comment]
I kinda agree that this is something that should be handled by Discord notification system. We can think about adding a subscription feature though, that lets you subscribe to any thread and then the bot will simply forward you copies via DM maybe. Not sure abour privacy though.
