### ISSUE TITLE
Wiki: use server template instaad of manually creating a server 

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#589]
**Is your feature request related to a problem? Please describe.**
The wiki explains to the user to create a server, while we have a template, which people can use to save time creating a server with channels themselves.

**Describe the solution you'd like**
Tell the users to use the template linked at: https://discord.new/WhtXEUZeFdTg

**Describe alternatives you've considered**
Pain.

**Comment by Tais993** [comment]
[Create Discord server and bot Wiki article ](https://github.com/Together-Java/TJ-Bot/wiki/Create-Discord-server-and-bot#discord-server)

Has been adjusted, any issues or?

**Comment by Zabuzard** [comment]
i fixed two minor things. all good, thanks 👍

**Comment by Zabuzard** [comment]
can be closed
