### ISSUE TITLE
[FEATURE] Create Command system

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#59]
In #10 we discussed options how to create a command system, that is the actual architecture for the code that gives possibility to create commands easily.

It is now time to actually create a system, propose it and then iterate on the design.

**Comment by Tais993** [comment]
https://lucid.app/lucidchart/invitations/accept/inv_69aac488-6a29-45da-91a5-88304e7739c9

The design

**Comment by Zabuzard** [comment]
> 
> 
> https://lucid.app/lucidchart/invitations/accept/inv_69aac488-6a29-45da-91a5-88304e7739c9
> 
> The design

The link requires login.

**Comment by Tais993** [comment]
Hopefully this image is enough

![image](https://user-images.githubusercontent.com/49957334/132770222-dcabebdd-eadd-46ef-bce2-0203c3f9c708.png)
