### ISSUE TITLE
Add auto-completion to /tag

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#594]
Slashcommands now have autocompletion support.

`/tag` is the perfect candidate for this and should support it.

Therefore, simply implement `onAutoComplete` which is already avaialble to `SlashCommandAdapter` and incorperate existing tags into it.

**Comment by Taz03** [comment]
same as #367

**Comment by Zabuzard** [comment]
Right. closing that in favor of this.

**Comment by Taz03** [comment]
> Right. closing that in favor of this.

i'd do this the other way around
