### ISSUE TITLE
Convert /tag-manage create-with-message & edit-with-message into message-context commands

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#595]
## Overview

The two slash commands:

* `/tag-manage create-with-message`
* `/tag-manage edit-with-message`

would benefit extremely from being transformed into message-context commands instead.

Their old slash-command counterpart can be deleted alltogether.

## Duplication

It is up to the implementor to decide how to tackle code duplication best when extracting the commands into new classes. Its possible that some of the existing logic in `TagManageCommand` has to be moved around for better reusage.

**Comment by Taz03** [comment]
y not use modals instead?

**Comment by Zabuzard** [comment]
no idea about modals. how would that look like?

@Tais993 what do u think?

**Comment by Taz03** [comment]
https://discord.com/developers/docs/interactions/message-components#text-inputs

first run the command then a modal will pop up write the tag id and content in it and submit and u r done

**Comment by Zabuzard** [comment]
does it show code formatted? how would it be JDA-wise? do we need to create support for that first? in particular for the routing?

**Comment by Taz03** [comment]
> do we need to create support for that first?

yes

**Comment by Taz03** [comment]
> does it show code formatted / preview-wise?

i dont think so, wait 5 mins i can check real quick

**Comment by Taz03** [comment]
yes it does not
![2022-10-04_141616-416x197_scrot](https://user-images.githubusercontent.com/73871477/193776855-4c87a085-cd72-449b-b09c-9baf1fcc4827.png)

**Comment by Zabuzard** [comment]
> yes it does not ![2022-10-04_141616-416x197_scrot](https://user-images.githubusercontent.com/73871477/193776855-4c87a085-cd72-449b-b09c-9baf1fcc4827.png)

it does not? where is the final preview. its all raw and unformatted.

**Comment by Taz03** [comment]
what about we make create-with-message a message context command and keep edit-with-message as slash command

but make edit with message use modals so my idea is instead of edit-with-message we make it edit and it'll take a option id of the tag we want to edit, after that we give a modal which have the previous text already and we can just edit that

**Comment by Taz03** [comment]
just realized we have edit and edit-with-message so we can have a single command edit and it'll have another option `clear` so if its true the modal will be empty and the user can paste new text
