### ISSUE TITLE
Which Discord framework to use?

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#6]
We have to decide on our main tech stack. Most importantly, which Discord Java framework should we pick?

Some options:

1. JDA (🚀)
2. Discord4J (👀)
3. Javacord (🎉)

![Overview](https://user-images.githubusercontent.com/13614011/132140506-adca4251-95a1-4b55-b6a3-368dda0864ec.png)

React with the corresponding emoji to vote!

**Comment by Tais993** [comment]
[https://libs.advaith.io/](https://libs.advaith.io/)

Only look at the Java section, those are the Java libraries you can use.

D4J is known for their spring integration.
JDA doesn't have anything special afaik, it's just a good library.

From what I know, JDA is more broadly used. 

Both libraries don't support threads yet, so I think that we should focus on slash commands instead.
Those work on threads and allow for a cleaner chat by making usage of emphemeral messages

While I can't comment on D4J's docs, I can say that JDA has excellent docs and a couple of tutorials in their [wiki](https://github.com/DV8FromTheWorld/JDA/wiki).
Including one for buttons (selection menu's work in the same way as buttons) and slash commands, so starting is easy.

**Comment by d3vel0per** [comment]
May be I will put in the unpopular opinion but D4J especially since it is based on reactor look a lot cleaner to me. Reactive libraries have much better control flows than async ones.
Additionally reactor being akin to stream API's fit in the same model which I again believe is easier to start with for any new contributor. Spring friendliness as @Tais993 mentioned is another plus.

But of course maintainability takes more priority. So it would be the teams call.

**Comment by Tais993** [comment]
```
private static final int MAX_COUNT = 1000;
 public void updateCount(MessageChannel channel, String messageId, int count) {
     channel.retrieveMessageById(messageId) // retrieve message for check
         .map(Message::getContentRaw) // get content of the message
         .map(Integer::parseInt) // convert it to an int
         .flatMap(
             (currentCount) -> currentCount + count <= MAX_COUNT, // Only edit if new count does not exceed maximum
             (currentCount) -> channel.editMessageById(messageId, String.valueOf(currentCount + count)) // edit message
         )
         .map(Message::getContentRaw) // get content of the message
         .map(Integer::parseInt) // convert it to an int
         .queue((newCount) -> System.out.println("Updated count to " + newCount));
```

This is a example of RestActions.
Most of the times they're really simple
a.e

```
        channel.sendMessage(content).queue();
```

So regarding "clean" I'd actually argue otherwise.
I think that RestActions are more clean, and simpler.
RestActions also support CompletableFutures (RestAction#submit)
Also check the wiki of RestActions [here](https://github.com/DV8FromTheWorld/JDA/wiki/7%29-Using-RestAction)

So for the people that need them (I've never heard of anyone using them, but still) can use those.

Regarding the Spring argument, I don't know whenever this project will use Spring.
I myself see no interest in Spring yet.

**Comment by d3vel0per** [comment]
As you already highlighted in the example. The sample's return type is `void` and the methos body is probably async hence you already split the control flow into two. Thats exactly the bane of async frameworks vs reactive ones.

**Comment by Tais993** [comment]
> 
> 
> As you already highlighted in the example. The sample's return type is `void` and the methos body is probably async hence you already split the control flow into two. Thats exactly the bane of async frameworks vs reactive ones.

I don't exactly understand the issue with the examples I provided.
Probably misunderstanding what you mean with reactive/async?

Correct, the queue method returns void, it's intended as last call.
flatmap/map don't, compare those to Stream#map

**Comment by d3vel0per** [comment]
I don't know anything about JDA API's by going by the name my assumption is `queue` enqueues a task for execution asynchronously which means the current thread gets a void(flow1) and some random thread picks up the enqueued task(flow2) both aren't tied to each other anywhere.
Whereas in reactor you would probably return a Mono<Void> which can emit back the results or errors if any. It's more of a pipeline.

**Comment by Tais993** [comment]
> I don't know anything about JDA API's by going by the name my assumption is `queue` enqueues a task for execution asynchronously which means the current thread gets a void(flow1) and some random thread picks up the enqueued task(flow2) both aren't tied to each other anywhere.

And correct it's not reactive/concurrent, an executor service handles the threads in the background.


> Whereas in reactor you would probably return a Mono<Void> which can emit back the results or errors if any. It's more of a pipeline.


RestActions allow CompletableFutures.
Furthermore,

`queue(Consumer<? super T> onSuccess, Consumer<? super Throwable);`

`queue(Consumer<? super T> onSuccess);`

`queue();`

Extremely simple, no confusing methods, not a hundred methods.

RestAction also allows enhanced error handling by making usage of the [ErrorHandler](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/exceptions/ErrorHandler.html)
 
From what you're saying, D4J sounds only *more* complicated, and less beginner friendly.
JDA's restaction require knowledge of Consumers, and that's it for 90% of the use-case.
This one exception where you use the ErrorHandler is honestly still mainly consumers.

**Comment by d3vel0per** [comment]
I wouldn't really comment on what's complicated or better than the other. I think both are easy enough to get started with.

From the explanations given above how I see this is a lot of callbacks. From a design perspective the control flows are random.
To elaborate, lets take a simple example:

With reactor its a stright pipeline eg. using *nix philosophy:
`command1 | command2 | command3 | ... | commandN`

while a callback led pipeline would look like:
`command1 | tee namepipe1 | command2 | tee namedpipe2 | ... | commandN | tee namedpipeN`

and then having listeners on each of the files or namedpipes each doing some processing independently.
Also, CompletableFutures are still eager while reactor pipelines are lazy.

**But anyways maintainability comes first, if JDA is well maintained and has better documentation, I would rather go with it or whichever has it.** We wouldnt want to build on top of a library that stops development after a few years.

NB: Spring integration also has massive benefits. You can literally build on top of well know enterprise integration patterns with realtive ease.

**Comment by d3vel0per** [comment]
Also just noticed.
https://libs.advaith.io/ is wrong D4J already has a PR merged for context menus.

https://github.com/Discord4J/Discord4J/issues/983

**Comment by d3vel0per** [comment]
Also noticed we already have majority votes for JDA. So let's just go with it 👯

**Comment by Tais993** [comment]
> From the explanations given above how I see this is a lot of callbacks. From a design perspective the control flows are random.

After looking at the D4J spring tutorial by Baeldung the so called callback hell looks equally bad.

Furthermore, I don't understand anything of all the pipelines things and how they matter, so can't comment on that anymore.

**Comment by Tais993** [comment]
> Also just noticed.
> https://libs.advaith.io/ is wrong D4J already has a PR merged for context menus.
> 
> [Discord4J/Discord4J#983](https://github.com/Discord4J/Discord4J/issues/983)

Will PR this to the site

**Comment by d3vel0per** [comment]
> After looking at the D4J spring tutorial by Baeldung the so called callback hell looks equally bad.
There aren't callbacks with reactor afaik 🤷‍♂️
It's a different philosophy altogether

**Comment by Tais993** [comment]
> > After looking at the D4J spring tutorial by Baeldung the so called callback hell looks equally bad.
> 
> There aren't callbacks with reactor afaik 🤷‍♂️
> It's a different philosophy altogether

Or you're talking about blocking, but their reactive API is many consumers

**Comment by Tais993** [comment]
While JDA technically doesn't support context menus yet.
There's an fully finished PR on freeze waiting for JDA 5.
This PR is constantly being updated so it follows JDA's version.
So context menus are ready for usage on JDA.

See this [branch](https://github.com/aasmart/JDA/tree/feature/context-menus)

**Comment by Zabuzard** [comment]
We will use **JDA** until the community decides otherwise.
