### ISSUE TITLE
TopHelpersCommand message is too long

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#603]
## Issue

The `TopHelpersCommand` message is too long and crashes:

![crash](https://i.imgur.com/pDhG8FI.png)

Stacktrace:

![stacktrace](https://i.imgur.com/idVz1jn.png)

Gotta make it a bit smaller.

## Fix

We can just reduce the amount of people it lists from `20` to, lets say, `18`:

https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java#L43

To reproduce the issue locally and test whether that did the trick, one would have to fake the result returned by the DB call here:

https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/commands/tophelper/TopHelpersCommand.java#L71

Or directly put some fake data into the database in order to hit the limit of 20 people. Also, they should have a message count of around `10000` each. All of this contributes to the size of the message.

**Comment by Tais993** [comment]
If possible, can you give screenshots on how the command should look?

**Comment by Zabuzard** [comment]
it just posts a code formatted message with a table generated by a framework. its just text.

![message](https://i.imgur.com/I0H9Smd.png)

**Comment by Tais993** [comment]
That's indeed really error prone, solution will be to either implement pagination support, or create multiple messages

**Comment by Zabuzard** [comment]
for now, its enough to just reduce the amount of users it displays. its like limitted to 30 or so. can just reduce that to 25 or sth like that.

**Comment by Gyoo** [comment]
Issue looks similar to #533, but I don't think we can fit all cases in a single solution. Each output should have their own way of dividing messages, or finding workarounds like Zabu mentioned

**Comment by Zabuzard** [comment]
Yeah. Its just the message being too long and we have to shrink it. Should have been thought of when creating this feature in the first place, but was forgotten. Remove a few people from the table and all good. Should be simple enough.

**Comment by Taz03** [comment]
what about instead we give the output in a text file?? then we won't have to compromise on the number of top helpers we can fetch

**Comment by Zabuzard** [comment]
possible, but its really not that big of a deal. just edit the constant i linked in the issue and done. this fix costs 30 seconds and is totally fine.
