### ISSUE TITLE
OnGuildLeaveCloseThreadListener warnings on unknown threads

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#619]
Sometimes the `OnGuildLeaveCloseThreadListener` logs a warning that it can not find certain threads:

![stacktrace](https://i.imgur.com/bez1a68.png)

How is this possible? Were the threads deleted, by whom? Are they just closed/archived and JDA doesnt find them anymore? Why does this happen so often?

This is not supposed to happen, the reason should be found and then either fixed or this log has to be adjusted to debug level, if this is an expected event.

**Comment by Zabuzard** [comment]
this issue is still there btw. happens frequently. probably an issue with archived threads that have to be retrieved first and are not in cache anymore or sth

**Comment by Taz03** [comment]
it is happening because rn it uses cache to get the threads

**Comment by Taz03** [comment]
fix is easy just use [Guild#retrieveActiveThreads](https://javadoc.io/doc/net.dv8tion/JDA/latest/net/dv8tion/jda/api/entities/Guild.html#retrieveActiveThreads()) method to retrieve all active threads and then use [ThreadChannel#getOwnerId](https://javadoc.io/doc/net.dv8tion/JDA/latest/net/dv8tion/jda/api/entities/channel/concrete/ThreadChannel.html#getOwnerId()) method to get the creator id and match it with the user id from the member remove event.

This wasn't possible before the forums channel update coz back then all threads were created by the bot and we needed a db to store who actually created the thread. But, it is not the case anymore so we can get rid of the db stuff in this command, and iirc the db was created for this specific feature so if it is not being used anywhere else we can get rid of that entire table.
