### ISSUE TITLE
Improve formatting on user facing moderation messages

### ISSUE THREAD

**Issue by marko-radosavljevic** [Together-Java/TJ-Bot#620]
We have almost no formatting on user facing moderation messages, which hurts readability. I would like 'reason' part to stick out more.

Currently, it looks like this on 1920x1080:

![image](https://user-images.githubusercontent.com/30927961/194729860-b15cf9fa-eaaa-4b27-9395-caedb710e9f8.png)

And on my phone:

![image](https://user-images.githubusercontent.com/30927961/194729997-e0802e33-7c70-46bc-a4cb-70b68ae4c433.png)

Maybe some embed magic, bold on 'reason', or just an empty line to create some space. My eyes have to jump around to find where the important part starts, since reasoning completely blended in with surrounding text.

**Comment by Tais993** [comment]
The formatting is broken with the title, but this is a proposal for how it could look.

![image](https://user-images.githubusercontent.com/49957334/194911974-a0fb5848-5df9-4918-bfe0-f68f99cbd516.png)
