### ISSUE TITLE
Migrate ban/warn system

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#63]
We have to migrate the ban and warning moderation system. The details are up to be decided by the community.

For reference, this is how it works as of today:

### Ban and warning system by Dyno

The commands `?ban` and `?warn` can be used for moderation.

#### Banning
The available command is

- `?ban <user> <time> <message>`

with

- `<user>` - mandatory - either being the name of the user, like `@Zabuzard` or his Discord account ID like `157994153806921728`
- `<time>` - optional - empty for a permanent ban, otherwise a period like `1h` or `1d`
- `<message>` - optional - a ban message/reason which is also written to the user in a DM by Dyno

Banning an user also deletes all of his recent messages.

#### Warning
The available command is

- `?warn <user> <message>`

with

- `<user>` - mandatory - either being the name of the user, like `@Zabuzard` or his Discord account ID like `157994153806921728`
- `<message>` - mandatory - the warning message/reason which is also written to the user in a DM by Dyno

Also, there is

- `?warnings <user>` - which will display an overview of all warnings an user received already

**Comment by Zabuzard** [comment]
Naturally blocked by #59

**Comment by java-coding-prodigy** [comment]
We could have a similar system with some changes:

- Change the prefix.
- Change the order of queries.
- Have an automatic message displayed by the bot telling the user why they were warned/muted/banned, depending on the message provided.
- We could also remove the `?tag interrupt` and display the message in the warning message mentioned above.

**Comment by illuminator3** [comment]
> * Have an automatic message displayed by the bot telling the user why they were warned/muted/banned, depending on the message provided.
it already private messages the user

**Comment by RealYusufIsmail** [comment]
I will be adding the warn command in a future pr.

**Comment by Zabuzard** [comment]
As soon as #267 has been merged, this can be closed :)

**Comment by Zabuzard** [comment]
Has been implemented and merged 🎉
