### ISSUE TITLE
Weird warning since JOOQ plugin version 7.1.1

### ISSUE THREAD

**Issue by Nxllpointer** [Together-Java/TJ-Bot#639]
**Describe the bug**
After the merge of #635 i get two weird JOOQ warnings when application:generateJooq is run:
https://paste.gg/p/anonymous/b7a3745102084111ad7a1b0acfecf599
https://paste.gg/p/anonymous/9b93f379917e439c880c06f331ca8270

The application still runs with the two warnings but they are incredibly annoying because IntelliJ interprets them as errors so every time you start your application you have to switch away from the error message tab.

**Expected behavior**
Have no warnings

**To Reproduce**
1. Checkout commit f2d9ff3597368eb92d7a2ae4a4b855d5e0ca448d
2. Run application:run

**Screenshots**
![image](https://user-images.githubusercontent.com/54677650/196153587-b31af1a6-bd58-4e13-80a9-4921416a37d7.png)

**Comment by Zabuzard** [comment]
can u share the full error message? (click away from the tab, then u see the full log)

**Comment by Zabuzard** [comment]
nvm, u did.

quick google says that it somehow seems to use an old XSD schema, not up2date with the current version of jooq. and there is a fix that tells it to use the right version:

https://stackoverflow.com/questions/72600484/jooq-codegen-fails-because-of-invalid-content-visibilitymodifier-and-includ

**Comment by Nxllpointer** [comment]
Think i fixed it already. PR is on the way

**Comment by Nxllpointer** [comment]
Fixed with #640

**Comment by Zabuzard** [comment]
(its not closed until the PR is merged)

**Comment by Nxllpointer** [comment]
oh ok i see
