### ISSUE TITLE
Migrate other moderation commands

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#64]
Next to the main moderation system (#63 ) we also have to migrate other important moderation commands, such as the mute, whois and modlogs system.

For reference, this is how it works as of today:

* `?whois <user>` by Dyno can be used to get an overview of a specific user. For example when he joined and registered.
* ~~`?modlogs <user>`  by Dyno shows all moderation actions that have been taken against an user.~~ (implemented)
* ~~`>mute <user>` and `>unmute <user>` by Inori Chan to mute or unmute an user.~~ (implemented)
* ~~`?mute <user> <time> <message>` by Dyno to mute an user. `<time>` and `<message>` are optional.~~ (implemented)

**Comment by Zabuzard** [comment]
Naturally blocked by #59

**Comment by Zabuzard** [comment]
Only `whois` is missing still, need to elaborate on the design and use case though

**Comment by Tais993** [comment]
We'll have to discuss whenever we still want the mute command.

[Discord just released time-outs](https://support.discord.com/hc/en-us/articles/4413305239191)
This is our equivalent of the mute command, difference is that Discord's version as a better UX and UI for both moderators and the people muted.

Only issue is, UI allows upto 1 week.
Bots can set upto 1 month, so we might still want a command to set it to a month.

**Comment by Tais993** [comment]
> Only `whois` is missing still, need to elaborate on the design and use case though

Will make a prototype of the whois command ^^
