### ISSUE TITLE
/modmail modal support

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#645]
## Overview

Right now, our `/modmail` command is a simple slash-command. Messages are entered within the command as argument:

![example](https://i.imgur.com/hiRxuQn.png)

This works well, but is suboptimal. A better UX would be achieved by using **modal**s. Similar to this:

![modal](https://i.imgur.com/Yc2DqsE.png)

One would simply use the command `/modmail`, without arguments, and it would popup a modal with options to input all the 3 arguments:
* the message to forward
* which server to contact
* anonymous yes/no

(unsure whether one can add the latter two to a modal. if not, then simply keep them in the slashcommand and have the modal only have the message)

To get started with modals, see our tutorial https://github.com/Together-Java/TJ-Bot/wiki/Create-and-use-modals
The example command created there should be very similar to what we want for `/modmail`.

**Comment by Taz03** [comment]
what about the stay-anonymous option tho? will the user write true or false in an modal text??

what about the server option? how u gonna show options

**Comment by kavink98** [comment]
@Zabuzard I can pick this up

**Comment by marko-radosavljevic** [comment]
@kavink98 awesome!

Welcome to the project by the way :relaxed: :heart:

**Comment by hamzanaciri99** [comment]
Can I work on this one?

**Comment by Taz03** [comment]
sure enjoy
