### ISSUE TITLE
React on ?foo !foo .foo to educate about slash commands

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#654]
Sometimes people with experience from other bots attempt to use message-commands, such as `?foo`, `!foo` or `.foo`.

We should create a small message listener that reacts to that and educates the user about the fact that we only use slash commands and also how a slash command can be used, little tutorial with a picture maybe.

(to include pictures, see `HelpSystemHelper#108` which includes `CODE_SYNTAX_EXAMPLE_PATH` as picture in an embed).

**Comment by Nxllpointer** [comment]
I would suggest this should only apply to .help !help... It would only annoy people if someone accidentally started a message with a dot.

**Comment by Zabuzard** [comment]
> 

why would u do that? nobody starts a message with `?hello please help` or `.what a nice day`. or `!i like that idea`.

im not talking about `message.startsWith(...)`, but asserting that the message consists of maybe a single line, starting with `.?!`, not followed by a space, with some text after it.

so like `[\\.!?]\\W+` or similar

**Comment by Nxllpointer** [comment]
But before running random commands people probably run a help command first

**Comment by Zabuzard** [comment]
from my experience, they attempt to use common other bot commands. such as `!run` or `.format`. ive seen this lately a few times.

do u fear false-positives or why do u want to limit the scope?

**Comment by surajkumar** [comment]
@Zabuzard I don't think this would be a good idea. 2 reasons:

1. As a programming oriented server, it's not unusual for a message to be `? thisIfTrue : this if false` or for somebody to say `!= obj`, uncommon as it may be, can happen.
2. It could result in spam from people doing !?. for the sake of it. 

unless, you're able to make it empherial.

**Comment by Nxllpointer** [comment]
@surajkumar ephemeral messages can only be created with interactions

**Comment by Zabuzard** [comment]
> As a programming oriented server, it's not unusual for a message to be ? thisIfTrue : this if false or for somebody to say != obj, uncommon as it may be, can happen.

such a message has never been send in our discord history the last 5 years, i just checked.

> It could result in spam from people doing !?. for the sake of it.
we block spam automatically already. u cant send messages too fast. and there are plenty of other possibilities to stress the bot.

**Comment by Taz03** [comment]
do we really need this?

**Comment by Tais993** [comment]
![image](https://user-images.githubusercontent.com/49957334/210020053-ee260afe-177b-4299-8b6c-c95819a56b8e.png)
To some extent this already exists, but this takes a little to load (too long IMO)

So no we don't need it, but it's still certainly a nice to have

**Comment by Zabuzard** [comment]
Bumping this. I keep seeing people attempt to write `.close` or `!close` every second day now...
