### ISSUE TITLE
Migrate code formatting system

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#66]
We have to migrate the code formatting system (TogetherJava bot aka "_illus bot_") and its other commands.

For reference, this is how it works as of today:

### TogetherJava bot commands

- `^help` or `^h` - displays all commands from the bot
- `^process` or `^p`
- `^upload` or `^u` - reply to a message and it will upload it to hastebin
- `^format` or `^f` - reply to a message and it will format/prettify the code
- `^lines` or `^l` - reply to a message and it will annotate it with line numbers
- `^taglist` or `^tags` - displays all tags available (a copy from Dynos tag system)
- `^syntax` or `^s` - reply to a message and it checks if the code is valid Java, i.e. if it would compile
- `^tag` or `^t` or `^?` - basically a copy of the tag system from Dyno

**Comment by Zabuzard** [comment]
Naturally blocked by #59

**Comment by illuminator3** [comment]
Blocked by #41
