### ISSUE TITLE
Uniform color palette

### ISSUE THREAD

**Issue by Nxllpointer** [Together-Java/TJ-Bot#662]
I have noticed that when coloring embeds for example, [everyone just uses whatever color he likes most.](https://github.com/Together-Java/TJ-Bot/search?l=Java&q=Color)

This is not very pretty and consistent so I suggest we introduce a color palette to use for things like embeds.

We should discuss our favorite color palettes and then maybe have the users vote on the best one.

**Comment by Taz03** [comment]
onedark
![image](https://user-images.githubusercontent.com/73871477/198105990-c403a3b9-8109-4372-b05a-04501d103953.png)

**Comment by Nxllpointer** [comment]
I like [catppuccin](https://github.com/catppuccin/catppuccin)
![](https://raw.githubusercontent.com/catppuccin/catppuccin/main/assets/palette/macchiato.png)
![](https://github.com/catppuccin/catppuccin/blob/main/assets/palette/morning.png?raw=true)

**Comment by Zabuzard** [comment]
How would we use the palettes though? Right now, we have **one color per feature**. For example, everything mod related is purple. Tags are red-ish. Reminders are yellow... and so on.

Or do you just want to align those existing colors with the palette, not changing how they are used? Also fine by me, just want some clarification.

**Comment by Nxllpointer** [comment]
The one color per feature can still stay. I would suggest however to reserve red orange and green for error, warning and success messages

**Comment by Taz03** [comment]
i'd say make a java file with all these colors and the programmer can use what ever color they want, according to them

like as of now many commands use yellow and purple as ambient colors so instead of making it again and again we can have a file with these colors and then use that

**Comment by Zabuzard** [comment]
We can vote here:

* catppuccin 🎉
* onedark 🚀

in the meantime, someone can already start implementing, I guess

**Comment by Tais993** [comment]
> We can vote here:
> 
>     * catppuccin 🎉
> 
>     * onedark 🚀
> 
> 
> in the meantime, someone can already start implementing, I guess

This vote excludes the "1 colour per feature" though, and you keep talking about this.
And I don't want to have the vote, just to then get a "actually I don't want this"
So was this done intentionally or what?

**Comment by Zabuzard** [comment]
@Tais993 

it doesnt exclude it. regardless of how we want to apply the colors (one per feature or one per emotion or ...), we want to decide on which color palette to choose our colors from.

so that, regardless how we use the colors, they are from the same color-family.

**Comment by Tais993** [comment]
Okay, than I have a suggestions.

We use a limitation of OneDark.

Errors = red
Warnings = yellow
Moderation actions = blue (the you got muted/banned DM etc)
Success = Green

For other cases we can use black or grey


That way colours have a meaning, and people understand the meaning.
I doubt anyone would see a colour and notice "ah this is for the code format command", which is why I rather give them an universal meaning.

**Comment by Zabuzard** [comment]
i agree. but i personally prefer having more light / pastel colors, hence why i vote for catppuccin, but would use it in the same way u suggested

**Comment by Nxllpointer** [comment]
I don't like the idea of black/gray embeds. I would rather go with a color like blue

**Comment by Taz03** [comment]
votes are draw now then y implement one of them? ig we should fix some time and wait by then for more ppl to vote, i'd say end of this month

**Comment by Tais993** [comment]
> i agree. but i personally prefer having more light / pastel colors, hence why i vote for catppuccin, but would use it in the same way u suggested

Okay, is there a possibility anyone creates a couple of actual use-case examples, so by modifying the existing embeds?

> Errors = red
Warnings = yellow
Moderation actions = blue (the you got muted/banned DM etc)
Success = Green

> For other cases we can use black or grey

And are there any opinions against this? Or does anyone think a different colour would look better?

**Comment by Taz03** [comment]
black or grey for all the embeds won't look as good

**Comment by Tais993** [comment]
What colour do you suggest then?

> black or grey for all the embeds won't look as good

Besides the fact I never said this, many many cases fall in a "success, warning or error" case.
If you submit a question, you'd get green, cause you successfully submitted the question.

**Comment by Nxllpointer** [comment]
No one said that every color has to be used lol
