### ISSUE TITLE
Remove pending reminders

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#674]
Right now a user can only create a reminder by using `/reminder create` but can't remove it.

Add the feature to remove pending reminders. Make a subcommand `/reminder remove` or `/reminder delete`.

**Comment by Zabuzard** [comment]
naming suggestion: `/reminder cancel`, since its about cancelling a pending reminder.

the issue is totally valid, but i see it more as a low prio. people barely use reminders and they also dont hurt anyone. so people do not really have a need to "clean them up". but sure.

**Comment by Taz03** [comment]
how should this work, im thinking of canceling the last created reminder, is that ok or it should have the ability to cancel any specific reminder?

**Comment by Zabuzard** [comment]
the only way i see this being useful is by having a way to list them all and then cancel a specific reminder.

can go in tandem with `/reminder list`, which has been added recently. for inspiration, one can look into the `/bookmark` system.
