### ISSUE TITLE
/modmail and /report should ping mods

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#681]
When someone uses `/modmail` or `/report`, mods should be pinged to raise awareness.

Right now it looks like this:
![modmail](https://i.imgur.com/GkIpwgR.png)

But we want this message to `@Moderator`s. Note that the ping has to be outside of the embed, in the actual message. I.e. `setContent(moderatorRole.getAsMention())` or similar. Otherwise it is not an actual ping (pings inside embeds dont do anything).

~~`/report` isnt done yet (#653), but will soon be~~ (it is done by now). The feature should be applied to both commands.

With the ping, it would look similar to what `/tag id:... reply-to:...` does:

![tag](https://i.imgur.com/BV3p5aM.png)

This class can also act as a reference of how to do it, `TagCommand`.

**Comment by isvora** [comment]
Hi, I'd like to pick this up!

**Comment by Zabuzard** [comment]
Sure thing, enjoy and welcome to the project! @isvora

**Comment by isvora** [comment]
I've added a PR for it :)

**Comment by Taz03** [comment]
implemented :+1:
