### ISSUE TITLE
Remove share-hint in help threads

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#710]
https://github.com/Together-Java/TJ-Bot/blob/0587d3e9da5e35d40faf40ab51a5c38f6c90ed1c/application/src/main/java/org/togetherjava/tjbot/commands/help/HelpSystemHelper.java#L120-L123

 maybe remove this coz now our bot can make gist of entire file

**Comment by Zabuzard** [comment]
Or better, adjust it to explain that this is a thing. I.e. it should tell people to post the files and that the bot will then upload them as gist.

But I agree.

**Comment by Taz03** [comment]
ig removing will be a better option, coz ppl tend to read smaller text more. So even if thats not there ppl will just send the file and it'll get converted to gist automatically
