### ISSUE TITLE
/remind should retry and log after failure

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#722]
## Problem

Our reminder system (`/reminder create ...`) sometimes fails to send the reminder. This is totally normal and can happen due to Discord/JDA hicups and whatever.

But, when it happens, we completely lose the message and it does not retry. That is a problem.

## Fix

Instead, the system should just retry failed reminders (maybe 3 times), by putting them into the DB again with an `Instant` that is maybe set 1 minute into the future. If it ultimately failed, the log message should log the actual reminder-text and the target user, so that the reminder can be rerouted manually by an admin at least.

## Details

For the failure count (~3 times), we likely need to add an additional column in the reminder DB table. Reminders are send from `RemindRoutine.java`, the table was initially created in `V8__Add_Pending_Reminders.sql`, the migration script `V10__Alter_Top_Helper_Message_Length.sql` shows how one can add a new column to an existing table.

**Comment by Paru-paru** [comment]
Hi, I would like to work on this issue.

**Comment by Taz03** [comment]
@Paru-paru sure, enjoy :smiley:

**Comment by Taz03** [comment]
whats the progress on this one? @Paru-paru

**Comment by Paru-paru** [comment]
Sorry about the absence, Ill get this done by this Friday and let you know if I can figure this one out.

**Comment by Zabuzard** [comment]
No worries. Thanks and good luck :)

**Comment by Paru-paru** [comment]
Couldnt figure it out, got busy with classes starting. If anyone wants to solve it thats fine with me, I just got classwork to focus for now.

**Comment by Zabuzard** [comment]
Alrighty, thanks for trying though :)

**Comment by ankitsmt211** [comment]
I'd like to be assigned to this issue please.

**Comment by ankitsmt211** [comment]
>it ultimately failed, the log message should log the actual reminder-text and the target user
Do you mean just use the logger's `log.warn(content + user)` just like that text?

**Comment by Zabuzard** [comment]
> Do you mean just use the logger's log.warn(content + user) just like that text?

Essentially, the warning it has right now should be kept - but only be shown once it failed ultimately. However, it should additionally also show the actual reminder content and user, yes.

**Comment by ankitsmt211** [comment]
what about `authorId`, would that be alright? or we need to pull actual user somehow

**Comment by Zabuzard** [comment]
ID would be enough

**Comment by ankitsmt211** [comment]
Had one more question, incase of null value returned by `OptionalReminderFailureCounter`, a `RuntimeException` should be thrown or is there anything else you suggest.

**Comment by Zabuzard** [comment]
what is that? a counter can never be null. its 0, 1, 2, 3

**Comment by ankitsmt211** [comment]
Oh it's just value returned from DB is Optional to avoid `NullPointerException`

**Comment by Zabuzard** [comment]
it shouldnt be optional. u made it `default 0`, so every entry has a retry counter. maybe bc u forgot `NOT NULL` (see code review)
