### ISSUE TITLE
ScamBlocker DM failure shouldnt result in an error

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#747]
The `ScamBlocker` sends DMs to the authors of a message to inform them about the action. Thats totally fine and expected, but failure to DM a user (for example if they blocked DMs), it should not yield to an exception being thrown in the logs:

> ```java
> net.dv8tion.jda.api.requests.RestAction
> ERROR
> RestAction queue returned failure: [ErrorResponseException] 50007: Cannot send messages to this user
> net.dv8tion.jda.api.exceptions.ContextException
> at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
> at net.dv8tion.jda.internal.requests.restaction.operator.RestActionOperator.contextWrap(RestActionOperator.java:123)
> at net.dv8tion.jda.internal.requests.restaction.operator.FlatMapRestAction.queue(FlatMapRestAction.java:50)
> at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
> at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.dmUser(ScamBlocker.java:256)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.dmUser(ScamBlocker.java:252)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.takeActionAutoDeleteAndQuarantine(ScamBlocker.java:189)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.takeAction(ScamBl...
> 01/03/2023 5:52 PM
> ```

The actual DM sending should probably use `mapToResults()` and then maybe send a DEBUG level log message:

![code](https://i.imgur.com/NVez0Cq.png)

**Comment by java-coding-prodigy** [comment]
Am I wrong or can this be easily solved just by adding a `RestAction#onFailure` call to the chain before queuing?

**Comment by AthithyaIthayan** [comment]
can it be simply handled by 
`queue(any->{},err-{logger.debug(err.toString())})`
@Zabuzard

**Comment by Zabuzard** [comment]
not quite, but sth along those lines, yes

**Comment by AthithyaIthayan** [comment]
I didn't get what do u mean by "sth" ??

**Comment by Zabuzard** [comment]
sth = something

**Comment by AthithyaIthayan** [comment]
Is the approach I mentioned a efficient approach then I would like to work on it

**Comment by Zabuzard** [comment]
as said, the general approach is fine. but the details are incorrect. we can get it sorted out during CR, i suppose.

**Comment by AthithyaIthayan** [comment]
Then I would like to take it up after website is made responsive I guess

**Comment by Taz03** [comment]
@AthithyaIthayan should i assign u this now?

**Comment by Taz03** [comment]
Just add the log statement on queue error consumer. U don't need no testing

**Comment by AthithyaIthayan** [comment]
Le me try then
