### ISSUE TITLE
MediaOnlyChannelListener DM failure shouldnt result in an error

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#748]
The `MediaOnlyChannelListener` sends DMs to the authors of a message to inform them about the action. Thats totally fine and expected, but failure to DM a user (for example if they blocked DMs), it should not yield to an exception being thrown in the logs:

> ```java
> RestAction queue returned failure: [ErrorResponseException] 50007: Cannot send messages to this user
> net.dv8tion.jda.api.exceptions.ContextException
> at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
> at net.dv8tion.jda.internal.requests.restaction.operator.RestActionOperator.contextWrap(RestActionOperator.java:123)
> at net.dv8tion.jda.internal.requests.restaction.operator.FlatMapRestAction.queue(FlatMapRestAction.java:50)
> at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572)
> at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538)
> at org.togetherjava.tjbot.commands.mediaonly.MediaOnlyChannelListener.onMessageReceived(MediaOnlyChannelListener.java:48)
> at org.togetherjava.tjbot.commands.system.BotCore.lambda$onMessageReceived$9(BotCore.java:205)
> at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
> at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java...
> ```

The actual DM sending should probably use `mapToResults()` and then maybe send a DEBUG level log message:

![code](https://i.imgur.com/KRhq8ts.png)

Even better would be to send a message in the channel that pings the user instead and then delete that message after a minute again. But its also okay to go without that for now.

**Comment by java-coding-prodigy** [comment]
Am I wrong or can this be easily solved just by adding a RestAction#onFailure call to the chain before queuing?

**Comment by Zabuzard** [comment]
Yeah. It can be simple: _on failure -> send debug log_

The problem here would be that the user has no idea what they did wrong. So we could think about sending a message with a ping and deleting that message again in 1-2 minutes.

But Im okay if we just solve the bug for now and do the other thing later 🤷

**Comment by java-coding-prodigy** [comment]
> Yeah. It can be simple: _on failure -> send debug log_
> 
> The problem here would be that the user has no idea what they did wrong. So we could think about sending a message with a ping and deleting that message again in 1-2 minutes.
> 
> But Im okay if we just solve the bug for now and do the other thing later 🤷

We could do the ping in channel thing if the DMs are blocked, but that might be counter-intuitive as we could anyway do that by default.

**Comment by AthithyaIthayan** [comment]
I want to work over this issue.
