### ISSUE TITLE
ScamBlocker crashes if given empty list of actions

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#749]
The `ScamBlocker` can display a number of actions (buttons) on its message. In a few of its flows, it uses `List.of()` (empty list) as list-of-buttons, when it does not want to show any buttons.

However, this leads to the code using `.setActionRow(confirmDialog)` (where latter is the empty list), running into a check of JDA that throws:

> One of the EventListeners had an uncaught exception
> ```java
> java.lang.IllegalArgumentException: Cannot have empty row!
> at net.dv8tion.jda.internal.utils.Checks.check(Checks.java:61)
> at net.dv8tion.jda.api.interactions.components.ActionRow.of(ActionRow.java:119)
> at net.dv8tion.jda.api.interactions.components.ActionRow.of(ActionRow.java:100)
> at net.dv8tion.jda.api.utils.messages.MessageRequest.setActionRow(MessageRequest.java:291)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.reportScamMessage(ScamBlocker.java:246)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.takeActionAutoDeleteAndQuarantine(ScamBlocker.java:190)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.takeAction(ScamBlocker.java:161)
> at org.togetherjava.tjbot.commands.moderation.scam.ScamBlocker.onMessageReceived(ScamBlocker.java:140)
> at org.togetherjava.tjbot.commands.system.BotCore.lambda$onMessageReceived$9(BotCore.java:205)
> at java.base/java.util.stream.ForEac...
> ```

The fix is simple. If the list is empty, it must not use `.setActionRow`, but simply skip that part of the code.

**Comment by Tanisha01-small** [comment]
I want to work on this code

**Comment by marko-radosavljevic** [comment]
Sure, welcome to the project! :relaxed: :heart:

**Comment by Taz03** [comment]
@Tanisha01-small r u still working on it?

**Comment by abhishekanuj26** [comment]
there has been no contribution on this. Can I raise a PR for this?

**Comment by Taz03** [comment]
sure, i don't think they gonna do this anyways
