### ISSUE TITLE
[BUG] Spotless not working in submodules

### ISSUE THREAD

**Issue by illuminator3** [Together-Java/TJ-Bot#76]
**Describe the bug**
Spotless doesn't "automatically" also work in submodules. Doing `gradle spotlessApply` only does it for the top module, doing e.g. `gradle application:spotlessApply` gives you an error that a) the plugin isn't added for that module and b) the meta/formatting/<formatting config>.xml doesn't exist.

**Comment by marko-radosavljevic** [comment]
Thanks, working on it.

**Comment by marko-radosavljevic** [comment]
Now it doesn't auto-format on build.. :(

Will check it tomorrow, had limited time today. @illuminator3
