### ISSUE TITLE
Add onboarding guide for other IDEs (Eclipse, VSC) to Wiki

### ISSUE THREAD

**Issue by AthithyaIthayan** [Together-Java/TJ-Bot#777]
Our current onboarding guides in the Wiki only cover the setup for IntelliJ. Ideally, we should also add guides for the other common IDEs, e.g. Eclipse or VSC.

**Comment by Taz03** [comment]
yes fair, id say instead remove intellij instead, it is impossible to have all the editors and ides tutorials. And its always a valid argument to add one more

**Comment by Taz03** [comment]
just keep the git clone command

**Comment by AthithyaIthayan** [comment]
I think its fair Its just a 2 to 3 step process so ..

**Comment by Taz03** [comment]
2-3 step process for 10 different things is a lot as well. Also its not like jetbrains sponsors this project so we'll have a reason to keep the intellij stuff only

**Comment by Taz03** [comment]
id say remove all intellij specific stuff

**Comment by AthithyaIthayan** [comment]
At least a Editor would help so better keep one

**Comment by Taz03** [comment]
wdym? also y u closed this issue? do u want me to create another issue for "removing intellij stuff", i was just waiting for mod to approve that

**Comment by AthithyaIthayan** [comment]
I thought intellij at least as a editor will be better for starter so I did close the issue smoothly

**Comment by Zabuzard** [comment]
> Add vcs guidelines to wiki In Eclipse

what did u do? which pages did u add? which did u modify? please be more detailed with ur descriptions. its hard to understand u otherwise

**Comment by Zabuzard** [comment]
In an ideal world, we would have the setup-tutorial for all major IDEs. So IntelliJ, Eclipse, VSC and maybe even Netbeans.

I am not holding anyone back who wants to write such a guide if they want. The issue is valid.

**Comment by AthithyaIthayan** [comment]
Let me try I have some ss to go with
