### ISSUE TITLE
Oof-"starboard"

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#781]
If users react with a specific emoji, for example `:oof:`, the bot should post the message in a specific extra channel, for example `#oofs`.

This is essentially whats otherwise known as **starboard**.

Challenges here are:
* the bot must ignore messages from "secret" channels (mod channel for example) - maybe try to check if `@everyone` has `View Message` permission
* emoji should be configurable
* multiple emojis should be supported
* ignore messages from the oof-channel itself (and bot messages)

**Comment by java-coding-prodigy** [comment]
I'll do this.

**Comment by java-coding-prodigy** [comment]
Open
