### ISSUE TITLE
Use text to remove ambiguity of buttons.

### ISSUE THREAD

**Issue by Benlewis9000** [Together-Java/TJ-Bot#787]
**Is your feature request related to a problem? Please describe.**
The delete tool button is ambiguous. I was unsure whether it meant do delete the bots message, my message, the code snippet or otherwise. I had to ask someone else, which means it's bad UI design. Aesthetic should not compromise usability.
![image](https://user-images.githubusercontent.com/4404290/221418090-35ab03c6-d01f-4811-829e-34c9af3a8034.png)

**Describe the solution you'd like**
Simply replace the bin emoji with "delete this message" or similar.

**Describe alternatives you've considered**
n/a

**Additional context**
See screenshot.

Are there any additional places emojis are being used in favor of text to represent an action that could be ambiguous?

**Comment by swashb0ckler** [comment]
Hi, I just joined the community on discord:) Can I try this as my first OSS contribution?

**Comment by Zabuzard** [comment]
Of course! Awesome 🙂 Just ask if you need any assistance ❤️

**Comment by swashb0ckler** [comment]
What do you think about this? 
![image](https://user-images.githubusercontent.com/62488841/222180617-57be3fd5-22b5-471d-ac04-046d93f7a4ae.png)

**Comment by Taz03** [comment]
@swashb0ckler great, now make a pull request
