### ISSUE TITLE
AutoPruneHelperRoutine crashes on DM when DMs closed

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#797]
The `AutoPruneHelperRoutine` class crashes when attempting to send a DM to someone who does not accept DMs.

![stacktrace](https://i.imgur.com/jyJSset.png)

Instead, it should just log the issue on debug level. Therefore, simply add a failure handler `.queue(() -> {}, failure -> logger.debug(..., failure))`.

![here](https://i.imgur.com/fxNhCuj.png)

**Comment by dfdx2** [comment]
I would like to work on this

**Comment by Taz03** [comment]
@dfdx2 u got any progress on this?

**Comment by dfdx2** [comment]
@Taz03 I did the update in codespaces and thought I had committed.  I never used codespaces before.  I  heard from a question I asked in discord doing the change in a proper IDE might be better.  Will try that sorry for taking so long.
