### ISSUE TITLE
SlashCommandEducator should ignore method calls

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#804]
Sometimes people write messages like

> .toString()

Currently, `SlashCommandEducator` picks that up and thinks it is a command, for example `.close`. In this case, it is obviously a false positive.

To prevent this, we should additionally check whether the message ends with `)`. If so, we can just ignore it. Just adding the check here in `SlashCommandEducator.java`:

![code](https://i.imgur.com/tbzjLMi.png)

And additionally adding `".toString()"` to the tests in `SlashCommandEducatorTest.java` here:

![test](https://i.imgur.com/SjxCgfL.png)

**Comment by Taz03** [comment]
i write method calls without the braces :skull:

**Comment by marko-radosavljevic** [comment]
How often do people even try to `.close` or something similar? Instructions how to close are already in every thread.
I assume there are probably more people trying to `.toString()` or `!= 0` than people trying to write commands?

I agree with the original intent, to educate people on slash command usage, but not if we annoy more people than we help. ^^

**Comment by Zabuzard** [comment]
We help more than we annoy. I see a legit hint every 2 days and an incorrect hint every 2 weeks only.

**Comment by tmcdonnell2** [comment]
Hello, would I be able to take this task?
