### ISSUE TITLE
Misspelled chatgpt package

### ISSUE THREAD

**Issue by SquidXTV** [Together-Java/TJ-Bot#816]
# About
There is a spelling error in the name of the package `org.togetherjava.tjbot.features.chaptgpt` which should be `org.togetherjava.tjbot.features.chatgpt` for correct naming.

![image](https://user-images.githubusercontent.com/88111627/229291110-56be5934-d538-4596-9a71-75ea20f01aca.png)

**Comment by Zabuzard** [comment]
lol rip. lets wait until all open chatgpt PRs are through to avoid nasty merge conflicts

**Comment by tmcdonnell2** [comment]
I could also do with in the chatgpt PRs but I think this is a nice and easy first time issue.
