### ISSUE TITLE
Enforce full Javadoc

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#82]
We would like to configure our code quality plugins (Spotless, SonarCloud) to enforce a full Javadoc on the whole codebase.

This also requires Javadoc'ing the current code base first.

**Comment by Tais993** [comment]
Full Javadoc, you mean that every method requires Javadoc?

**Comment by illuminator3** [comment]
> Full Javadoc, you mean that every method requires Javadoc?

I suppose every method, field and class

**Comment by Tais993** [comment]
Sounds extremely overkill, I'm against this idea.
Decent variable, method and class naming can make everything clear a lot of times.

**Comment by java-coding-prodigy** [comment]
Why do we need Javadoc in the first place?

**Comment by Tais993** [comment]
> At least API-like stuff should have nice javadocs
Yes
> Every class and method should have generated javadocs, just so it exists.
What does it add to have an empty javadoc?
Besides adding more pointless lines, nothing really?

**Comment by marko-radosavljevic** [comment]
Not empty, just generated `@params`, `@throws`, etc. It's better than nothing, I guess.

Also, just things with public visibility should require javadocs.

**Comment by Zabuzard** [comment]
Personally, I want to force JavaDoc for everything except the trivial things such as getter/setter/logger/... but I am not sure if we can configure it that fine-tuned.

Maybe we can though, plugins are very advanced nowadays.

One restriction we already lifted was: no doc required for `private` things.

Anyways, the current code base has full Javadoc now, so next up we explore what we can configure in the plugins.

**Comment by Zabuzard** [comment]
Where do we stand with this? @marko-radosavljevic are you still planning to do this?

**Comment by marko-radosavljevic** [comment]
Ah, didn't know you expected me to do it.

Added a new rule `Public types, methods and fields (API) should be documented with Javadoc` as a critical issue on sonarcloud, and changed the gate to fail on any critical issues.

Will leave this issue open for comments on the changes, and will close it after it's confirmed to work as intended.

**Comment by Zabuzard** [comment]
It works as intended. Closing
