### ISSUE TITLE
Deprecation of discriminator

### ISSUE THREAD

**Issue by Tais993** [Together-Java/TJ-Bot#831]
**Describe the bug**
Users are going to be unique, the discriminator will eventually pass away. (How long this'll fully take is a question, either way changing should happen as fast as possible)

The discriminator wills

**The consequences**
As far as I'm aware, identification happens using user ID's, not using their tag.
Therefor nothing mayor should happen, most things will be styling / messages.

Many commands show the user by their tag, so this will have to change to their name, (maybe also ID? is useful or staff commands, but others not really)

the /whois command will also have to be modified for this, but that should be everything.

I'll do a check whenever Guild#getUserByTag is being used anywhere, if so we'll have to wait for a Guild#getUserByUniqueName / Guild#getUserByName.

**Comment by Tais993** [comment]
I'll take care of this tonight, should be minute work

**Comment by Tais993** [comment]
I did some thinking, and there is a deprecation period.

We can wait for Discord to add some kind of a flag, or a way to know whenever someone has an unique username already?
We then use a util method, which checks that and returns either the username or the tag.

That'd be the nicest solution I feel like, so this'll then be on hold till Discord releases all changes.

**Comment by Zabuzard** [comment]
It depends on the use case in the code. In most situations we either want the ID or the display name. I dont really see why/when we should be using the actual username or discriminators.

**Comment by Tais993** [comment]
Discriminator is simply a nice to have, as it's a "user friendly" way to tell people apart.
In moderation cases, ID is always shown already, and in non moderation cases, think ID/mention is still shown most of the time.

But well, nobody knows each others ID out of their head, so that's the human part.
There aren't many non-unique names in our Discord, and even if there are multiple people with the same name, can tell them apart from pfp, so honestly don't need the discriminator in our everyday use.

So I guess we can just fully remove the discriminator, I have already changed it, just didn't commit it yet.
I'll do a second check or I missed anything, and create PR tonight.

**Comment by Tais993** [comment]
i forgor
