### ISSUE TITLE
Recommend replacing '4.19.0' with '4.19' for Eclipse JDT

### ISSUE THREAD

**Issue by surajkumar** [Together-Java/TJ-Bot#832]
Downloaded main and while `gradle build` was running, the following logs in the console. 

![image](https://github.com/Together-Java/TJ-Bot/assets/76599223/99c967b0-5e65-42be-9808-e94a36600045)

**Comment by marko-radosavljevic** [comment]
This is a transitive dependency from spotless, we can ignore it :relaxed:
