### ISSUE TITLE
chatgpt command limit response length

### ISSUE THREAD

**Issue by marko-radosavljevic** [Together-Java/TJ-Bot#840]
Chatgpt command will crash if the response is over 2000 characters. To prevent that, we have to limit the response.

Just limiting the max tokens is a bad solution, because it would cut the answer short. Getting a guide or a code solution that is 90% there is not very helpful.

The solution is to add 'Answer in 1500 characters or less.' to the user question. And if chatgpt still goes over the limit, we can hard limit to prevent it from crashing.

**Comment by tmcdonnell2** [comment]
When you say 'hard limit', do you mean do cut the response off if too long? Or attempt to get another response from chatGPT? Can we cut it in "half" and send the rest as a separate message?

**Comment by marko-radosavljevic** [comment]
Sending the rest as a separate message is probably the best solution, because getting another response would likely be too slow?

**Comment by r4huldeveloper** [comment]
I want to work on this bug , can you please tell me is it about gpt 3.5 or gpt4?

**Comment by Zabuzard** [comment]
gpt 3.5

**Comment by r4huldeveloper** [comment]
public static String truncate(String text, int limit) {
        if (text.length() <= limit) {
            return text;
        } else {
            return text.substring(0, limit);
        }
    }
After getting the response from the API, we can implement a method to truncate it if it exceeds the desired character limit.

**Comment by Zabuzard** [comment]
or we post multiple embeds, as originally intended.

**Comment by Zabuzard** [comment]
@tmcdonnell2 are u still on it, or can @r4huldeveloper take over?

**Comment by r4huldeveloper** [comment]
@Zabuzard Sir we just need to half the response given by gpt , right?

**Comment by tmcdonnell2** [comment]
> @tmcdonnell2 are u still on it, or can @r4huldeveloper take over? do u perhaps have some unmerged changes ready?

I have some changes I pushed recently on my branch of the project. It breaks up the response instead of just trimming down the original.

I don't have a PR open but it might be "good enough" to pull and allow for testing in the dev server. It would be best if this time we get a lot of manual/user testing done on it to see where it breaks and get more test cases. I can open a PR later.
