### ISSUE TITLE
HelpThreadCreatedListener#sendHelperHeadsUp only pings a single category role

### ISSUE THREAD

**Issue by Nxllpointer** [Together-Java/TJ-Bot#854]
This bug was probably introduced while switching over from the thread-based help system to the forum, as the threads could only be assigned a single category. The forum posts however can have multiple tags and so all category roles should be pinged accordingly, not just one, as you might not get added to a forum post which you subscribed to.

Responsible code in [HelpThreadCreatedListener#sendHelperHeadsUp](https://github.com/Together-Java/TJ-Bot/blob/d2d648711cf88951f14f0b505b52caaba912018e/application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java#L98):
https://github.com/Together-Java/TJ-Bot/blob/d2d648711cf88951f14f0b505b52caaba912018e/application/src/main/java/org/togetherjava/tjbot/features/help/HelpThreadCreatedListener.java#L100-L113

This would need to be changed to support multiple category roles and a new method in [HelpSystemHelper](https://github.com/Together-Java/TJ-Bot/blob/d2d648711cf88951f14f0b505b52caaba912018e/application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java#L44) must be added to get all categories of the post.

**Comment by Zabuzard** [comment]
its not a bug, its intentional. it pings the most specific role. users are not really meant to assign multiple categories. the most specific category (least users) is designated the main category and will be the one pinged
