### ISSUE TITLE
Logging - Make title linkable to github file

### ISSUE THREAD

**Issue by SquidXTV** [Together-Java/TJ-Bot#856]
# About
Currently the logging looks like this:

![image](https://github.com/Together-Java/TJ-Bot/assets/88111627/a137cf58-a285-43c1-aad1-691f9d9e8963)
![image](https://github.com/Together-Java/TJ-Bot/assets/88111627/b263619d-ddb3-44db-8f8a-8cf293d01454)

## Idea
The title is always the name of the file which logged this message. 
So my idea is to make it link to our github if the logged message/warning comes from one of our files.
Sometimes the logged message comes from an error and that links to other files like `net.dv8tion.jda.internal.requests.WebSocketClient`. In that case I would just ignore it and use the old logging without linking.

In the shown example for like `org.togetherjava.tjbot.features.utils.LinkPreviews` it would simply link to this page:
https://github.com/Together-Java/TJ-Bot/blob/master/application/src/main/java/org/togetherjava/tjbot/features/utils/LinkPreviews.java

**Comment by SquidXTV** [comment]
Making titles like these clickable is possible right?

**Comment by Nxllpointer** [comment]
Great idea. Also yes you can specify an URL 
![image](https://github.com/Together-Java/TJ-Bot/assets/54677650/b27218ad-3008-4239-a542-66293f9ae4f5)
