### ISSUE TITLE
Make /tags entries clickable

### ISSUE THREAD

**Issue by SquidXTV** [Together-Java/TJ-Bot#866]
# About
## Preview
It's possible to make commands clickable in order to put them in the message box, question thread example:
![image](https://github.com/Together-Java/TJ-Bot/assets/88111627/056131b1-68b0-4dd5-b450-c039456147af)

## Improvement
**My idea is now to add this to the `/tags` command:**
![image](https://github.com/Together-Java/TJ-Bot/assets/88111627/75b0294e-6ad9-4de9-9666-9af8894193d4)

**Comment by Zabuzard** [comment]
definitely low prio, but sure. why not 👍

**Comment by Zabuzard** [comment]
we have a `mentionSlashCommand` utility method in the code somewhere. this should be used here

**Comment by Zabuzard** [comment]
`MessageUtils.java#107`

```java
private static RestAction<String> mentionSlashCommand(
            RestAction<? extends List<Command>> availableCommands, Supplier<String> notFoundMessage,
            String commandName, String... subCommands) {
```

**Comment by RubberDuck2307** [comment]
I would like to do it.

**Comment by SquidXTV** [comment]
It's not possible to reference commands with parameters as of now:
https://discord.com/channels/272761734820003841/1151865319913168948

Closing this for now

**Comment by SquidXTV** [comment]
It's not possible to reference commands with parameters as of now:
https://discord.com/channels/272761734820003841/1151865319913168948

Closing this for now
