### ISSUE TITLE
Wrong discriminator shown for users with new username system

### ISSUE THREAD

**Issue by KoblizekXD** [Together-Java/TJ-Bot#867]
**Describe the bug**
Invalid discriminator(`#0000`) shown for users with new username system in uploaded gist by TJ-Bot

**Expected behavior**
I'd suggest to remove the discriminator for users with new username system(and possibly add `@` before their name), this would result in this:  
`Uploaded by (@)koblizekxd`  
instead of this:  
`Uploaded by koblizekxd#0000`

**To Reproduce**
1. Upload any attachment
2. Wait for TJ-Bot to provide link to the gist
3. Open the gist

**Screenshots**
![file1](https://github.com/Together-Java/TJ-Bot/assets/71057761/1dc29681-1d1b-4146-9197-0620b3e197dd)
![file2](https://github.com/Together-Java/TJ-Bot/assets/71057761/94952c49-3c48-45c1-ab26-aa10db6272d9)

**Additional context**
Example link: https://gist.github.com/Together-Java-Bot/64e3ffc7bf6dbc3c562021f44a6a1294

**Comment by Tais993** [comment]
In reference to this, #831, did most of it locally but never got to the PR, probs outdated by now.

**Comment by dosh-good** [comment]
Is this still open? I am new to open source and would like to give this a shot.

**Comment by marko-radosavljevic** [comment]
Welcome! :relaxed: :heart: 

Yup, it's still open, I will assign it to you. Feel free to ask any questions here, or in our discord server. ^^

**Comment by marko-radosavljevic** [comment]
Also, make sure to read our [Wiki](https://github.com/Together-Java/TJ-Bot/wiki), to help you get started. Especially [Contributing](https://github.com/Together-Java/TJ-Bot/wiki/Contributing) since you are new to open-source. It has a lot of useful guides for the first time contributors. @goodieDo ^^

**Comment by goodieDo** [comment]
Thank you @marko-radosavljevic

**Comment by goodieDo** [comment]
@marko-radosavljevic I created my own bot and discord server (yay!), but I'm trying to recreate the issue with my bot / server. Where am I supposed to upload a document as directed by [KoblizekXD] ?

**Comment by ankitsmt211** [comment]
@goodieDo Hi, you need to create a forum channel called `questions`, create a new post inside that and then upload your file.
Given you already have your personal access token setup in `config.json`

**Comment by doshgo** [comment]
@ankitsmt211  thank you. I was not aware there were extra steps to make the server a Community Server. After some additional implementations, it works.

**Comment by vishv843** [comment]
Hey, I am new to this project. I wanna work on this. Can you assign me the PR?

**Comment by SquidXTV** [comment]
> Hey, I am new to this project. I wanna work on this. Can you assign me the PR?

Welcome to the project :D

Someone already worked on this issue, but the PR is kinda inactive.
You should be able to continue there if you want:
#1002

You would need to write a comment or interact with the PR if someone should assign you to it.

**Comment by vishv843** [comment]
thanks
