### ISSUE TITLE
Transfer question Context Command

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#868]
## Motivation

New users frequently post questions in `#chit_chat` and it is impossible to educate them all. On top, when told to post in `#questions`, users often just dont post anything at all anymore.

## Feature

To ease above, we should add a message context command that allows staff to transfer a wrongly posted question into the right channel. The bot then does all the heavy lifting and educates the user via DM.

I.e. staff right clicks a wrongly posted message and selects a new action `transfer-question`

![transfer](https://i.imgur.com/BDs0leS.png)

The bot then opens a modal window where the staff can select a title, the message and tags for the post. The bot can prefill the message with the users original message and the title can be prefilled with a guess (see existing logic for `/suggestion`, which has that as well). The tag can be prefilled with just `Java` - a dropdown for the tags would be totally fine.

The staff then clicks `OK` to submit the modal. The bot creates the post in `#questions` as embed (setting the original user as author of the embed). The bot deletes the original message and DMs the original user about what happened. Sth along the lines of:

> Hey there, unfortunately you have asked your question in the wrong channel (see `#welcome` for details). Your question was automatically transferred to `#link_to_the_post`. Please continue there, thanks 👍

If the DM fails, the bot sends the message in the original channel (`#chit_chat`) instead.

## Details

It is of course totally okay to add the feature piece by piece and just start with a quick draft first, instead of doing all features.

**Comment by ankitsmt211** [comment]
@Zabuzard Hi, i'd like to get started on this. Could you please assign it to me?

**Comment by ankitsmt211** [comment]
Not sure if i need to open PR again? these are the latest changes. Feature seems to work but it's not consistent throughtout, sometimes i assume user is not fetched and that causes some problems. It could also be due to passing "User" as an object in one of the methods instead of retrieving when required.
