### ISSUE TITLE
Java Mail RSS Forwarder

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#882]
Read the RSS Feed of Java Mails:
https://wiki.openjdk.org/spaces/listrssfeeds.action?key=JDKUpdates

Perhaps there are even more and better feeds.

Forward them to `#java_news_and_changes` (or a new channel).

**Comment by MarekT0v** [comment]
Hello, can I work on this issue?

**Comment by nateweisz** [comment]
I would like to take this on!!
