### ISSUE TITLE
Fix deprecated Log4J package scanning

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#887]
Running TJ-Bot gives the warning:

> WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release

It refers to the now deprecated use of `package` in our `log4j2.xml` files:

![config](https://i.imgur.com/DrkVAcM.png)

Has to be fixed before we eventually update and suddenly its gone.

**Comment by SquidXTV** [comment]
Will be removed in Log4j 3.0:

https://issues.apache.org/jira/browse/LOG4J2-3644

Is it possible to just remove the packages attribute at all?

**Comment by Zabuzard** [comment]
> Is it possible to just remove the packages attribute at all?

No Idea. But Id assume it has some meaning. Testing required.

**Comment by SquidXTV** [comment]
I looked up online and they said that for most people just removing the attribute is working fine.
It probably automatically scans for the `@Plugin` annotation.
I tried it out and it seems to be working fine without the attribute.

**Comment by SquidXTV** [comment]
> In Log4j 2 a plugin is declared by adding a [@Plugin](https://logging.apache.org/log4j/2.x/log4j-core/apidocs/org/apache/logging/log4j/core/config/plugins/Plugin.html) annotation to the class declaration. During initialization the [Configuration](https://logging.apache.org/log4j/2.x/log4j-core/apidocs/org/apache/logging/log4j/core/config/Configuration.html) will invoke the [PluginManager](https://logging.apache.org/log4j/2.x/log4j-core/apidocs/org/apache/logging/log4j/core/config/plugins/util/PluginManager.html) to load the built-in Log4j plugins **as well as any custom plugins.**

https://logging.apache.org/log4j/2.x/manual/plugins.html
