### ISSUE TITLE
Help Thread pins wrong message

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#892]
In help threads, the original message (from the author) is supposed to be pinned.

However, it seems that (for some reason) the bot currently pins his role-mention message instead.

![demo](https://i.imgur.com/GkvrrDi.png)

**Comment by Zabuzard** [comment]
Valid, but perhaps a necessary evil. If we pin the users message and the user eventually deletes the message, the pin is entirely gone as well. That way, we prevent it.

**Comment by SquidXTV** [comment]
I would take care of this
