### ISSUE TITLE
Dismiss Button for ChatGPT answer

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#897]
Sometimes ChatGPTs automatic-answer-attempt is not helpful.

We should add a button attached to the end of his message(s) that allows certain people to `Dismiss` it (delete the message).
The message is created somewhere around [HelpSystemHelper.java#L163C25-L193](https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/features/help/HelpSystemHelper.java#L163C25-L193)

Code-wise, the challenge is that ChatGPT can post multiple messages. To delete all of them, we can simply remember all those message IDs within the buttons argument-list. See the existing GIST Dismiss button for details (`FileSharingMessageListener.java`).

People allows to click dismiss would include:
- OP
- anyone with the `"tagManageRolePattern": "Moderator|Community Ambassador|Top Helpers .+",` role

**Comment by SquidXTV** [comment]
Could implement it today quickly

**Comment by SquidXTV** [comment]
Should I put the button on the last message, or should it be in an extra message?

**Comment by Taz03** [comment]
> Should I put the button on the last message, or should it be in an extra message?

last message will be fine

**Comment by SquidXTV** [comment]
So it should just delete the answer messages right?
Should it also delete this message?
```java
        RestAction<Message> message =
                mentionGuildSlashCommand(threadChannel.getGuild(), ChatGptCommand.COMMAND_NAME)
                    .map("""
                            Here is an AI assisted attempt to answer your question 🤖. Maybe it helps! \
                            In any case, a human is on the way 👍. To continue talking to the AI, you can use \
                            %s.
                            """::formatted)
                    .flatMap(threadChannel::sendMessage);
```
