### ISSUE TITLE
Disabled Features should be logged

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#898]
Our feature-blacklist, which is used to disable certain features (if needed), should emit an `INFO` level logging message for each disabled feature.

Features are disabled in [Features.java#162](https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/features/Features.java#L162).

So we can simply add a log for each feature that does not pass the filter there.

**Comment by adiChoudhary** [comment]
Hi @Zabuzard ,

Can help if issue still open, am new to this project but experienced in Java Development.

**Comment by Taz03** [comment]
@adiChoudhary assigned u

**Comment by adiChoudhary** [comment]
Thanks, buddy learning how bots work in discord, can we connect in discord on how the overall project works that would be awesome

**Comment by Taz03** [comment]
sure, we have a public discord server, u can find the invite link on our website

**Comment by adiChoudhary** [comment]
Joined, working on understanding how discord and Java code interact with each other
