### ISSUE TITLE
ChatGPT Auto-answer should be in an embed

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#917]
Its necessary for better UX that ChatGPT answers are posted in embeds with a proper author and icon that clearly marks the content as AI answer.

Right now, its too confusing for users since it looks like a regular message.

The disadvantage is that code snippets are typically harder to read in embeds. We will try it out and see how bad it is. Its likely that we can live with it.

Also, when posting embeds, the text limit is boosted from 2k to 4k characters (? check embed max size). So that would reduce the amount of messages that need to be posted, which is good.

**Comment by Zabuzard** [comment]
Would also fix #928 if done properly

**Comment by SquidXTV** [comment]
going to wait for other PRs to get merged first
