### ISSUE TITLE
ChatGPT Auto-Answer should not be posted when image

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#918]
ChatGPT should not post an auto-answer attempt when the question contains an image or link.

Since it has no access to reading that, it can only post bad quality answers, which we do not want to post in the first place.

**Comment by SquidXTV** [comment]
Going to work on that

**Comment by SquidXTV** [comment]
do you really think it shouldnt answer when the message contains a link?
I understand if its a github link because the bot is going to miss context
but what if its not?

**Comment by Zabuzard** [comment]
when there's a link, there's a high chance it contains text relevant to the question. without the context, its likely. that something crucial is missed.
rather have a few auto answers too less than posting nonsense or confusing stuff.

btw, we have a link detector already for the linkpreview feature. somewhere aroubd LinkPreviews

**Comment by SquidXTV** [comment]
ok thanks for letting me know

**Comment by SquidXTV** [comment]
sorry, currently can't really find time for this

**Comment by SquidXTV** [comment]
how can I add a boolean check to a `flatMap` in a `RestAction<Message>`?
like I want to check if the message contains an image and if so it should ignore the `flatMap`.

```java
private RestAction<Message> createAIResponse(ThreadChannel threadChannel) {
    RestAction<Message> originalQuestion =
            threadChannel.retrieveMessageById(threadChannel.getIdLong());
    return originalQuestion.flatMap(message -> helper.constructChatGptAttempt(threadChannel,
            getMessageContent(message), componentIdInteractor));
}
```

is there anything nice provided by RestAction to check smth like that?
or do I need to do this:
```java
private RestAction<Message> createAIResponse(ThreadChannel threadChannel) {
    RestAction<Message> originalQuestion =
            threadChannel.retrieveMessageById(threadChannel.getIdLong());
    return originalQuestion.flatMap(message -> {
        if (/* check*/) {
            return null; // smth to return an empty RestAction?
        }
        
        return helper.constructChatGptAttempt(threadChannel,
                getMessageContent(message), componentIdInteractor);
    });
}
```

**Comment by Tais993** [comment]
There is a flatmap method that takes a condition as first argument. A simple flatMap(Predicate, Function), should work iirc

**Comment by SquidXTV** [comment]
> There is a flatmap method that takes a condition as first argument. A simple flatMap(Predicate, Function), should work iirc

ah thanks <3

**Comment by SquidXTV** [comment]
Ok it works for images but the link preview check is broken somehow:

```java
message -> !MessageUtils.containsImage(message) && LinkPreviews.extractLinks(message.getContentRaw()).isEmpty()
```

![image](https://github.com/Together-Java/TJ-Bot/assets/88111627/650b67e7-4825-4cd6-b318-a37ff92d24fb)

**Comment by SquidXTV** [comment]
I found the problem:
I send the message with the link like this:
```
<https://www.baeldung.com/java-interfaces>
```
which doesn't get detected, but this gets detected:
```
https://www.baeldung.com/java-interfaces
```
the wrapping with `<`, >` is used to automatically remove the website embed, this works:

![image](https://github.com/Together-Java/TJ-Bot/assets/88111627/3d502adc-5e69-45a3-a0b0-6296f635718b)

**Comment by SquidXTV** [comment]
what should I do about it?
