### ISSUE TITLE
ChatGPT Auto-Answer should be more compact and use Java

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#920]
We have to adjust the preface-info that we send to ChatGPT on each question to:

* make responses more compact to prevent the need for posting multiple messages
* it should use Java for default code snippets when no other context has been provided

**Comment by ankitsmt211** [comment]
I don't think the character limit in preface affects the responses, tried with 500, 1000 and 1500 each giving same response for exactly similiar post.

**Comment by Zabuzard** [comment]
can u try putting it explicitly into the question itself rather than the preface only?
