### ISSUE TITLE
Delete the pinned-message in help threads

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#921]
We have a feature that auto-pins the first message in each help-thread.

However, we should delete the message that indicates that event in discord, as it creates unecessary noise:

![pin](https://i.imgur.com/AaVHBp4.png)

**Comment by SquidXTV** [comment]
so you dont want to remove the pin itself but just the indication of a pin.
Is there an easy way in JDA to get that indication message?

**Comment by Zabuzard** [comment]
> so you dont want to remove the pin itself but just the indication of a pin.

yes

>  Is there an easy way in JDA to get that indication message?

no idea. but its ofc possible to just create a listener that sits on every help thread and deletes any pinned message. u can identify it with its type. its not a "regular message" but something like an event message or webhook message or sth. dunno the name.

like, i wouldnt mind creating a feature that deletes any "Foo pinned a message to this channel" from help threads.
