### ISSUE TITLE
Remove some hints in help-threads

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#922]
When creating a new help-thread, we post several hints. Two of them are obsolete for now and should be deleted entirely to reduce noise:

* How to post code (we have automatic code detection and code-actions as alternative)
* How to close (we auto-close anyways)

![hints](https://i.imgur.com/ckSd4sw.png)

**Comment by AdityaM2205** [comment]
Hey,would love to help on the issue,could you please assign it to me
