### ISSUE TITLE
Auto-detect inactivty and send hint for help-threads

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#923]
When creating a help-thread, we send a few hints.

One of them is how to act when no one responds. Our entry point for this hint is bad. It would be better if we post this message when the moment of inactivity has come.

![hint](https://i.imgur.com/b2VDqlx.png)

So we should detect when a thread is inactive (no one except OP responded since 5 hours) and then let the bot automatically post this message. This will also lead to an "auto-bump", which may cause more helper attention.

**Comment by ankitsmt211** [comment]
Couple of questions, in no particular order.
* Should this be triggered once per thread or multiple times based on inactivity?
* Would it be wise to use already existing `HelpThreadCreatedListener` class or too much context in one file?
* We already have a DB table storing help meta data, thoughts about using that or maybe a caffiene? 
* `help` package is also brimmed with a lot of `HelpThreadxxxxx` classes, perhaps a sub package?


On a side note, i think it would be less resource/work intensive with a simpler command that just sends this text on demand. So if a thread is inactive for too long, someone can make the judgement and trigger it. In that case, we might not even need a command for this. We already have  a `/tag tagHere`, much simpler.

**Comment by Zabuzard** [comment]
Perhaps we can start by moving the dialog into the existing "closed bc of inactivity" text.
as in "yo, it got closed and heres what u can do to prevent that instead: ..."

**Comment by ankitsmt211** [comment]
It does mention a hint about improving question, maybe refactor this to emphasize the last bit.

![image](https://github.com/Together-Java/TJ-Bot/assets/61616007/beb3559d-b5e3-49e9-8ef6-c19b71d712cd)

**Comment by Zabuzard** [comment]
yeah. i would just bloat up this section significantly. this is the right moment to educate an user about how to improve their question. this is the moment where we have their attention. we should post a few extra sentences here.
