### ISSUE TITLE
Transfer crashes on short messages

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#926]
When triggering the transfer command on a short message whose auto-title would be short, it runs into an exception without falling back to `Untitled`:

![message](https://i.imgur.com/gqBnk8F.png)

![stacktrace](https://i.imgur.com/Onlafhm.png)

**Comment by Zabuzard** [comment]
( @ankitsmt211 for visibility)

**Comment by ankitsmt211** [comment]
Are you suggesting it should give back "untitled" as title for messages shorter than 4 character length?

**Comment by ankitsmt211** [comment]
This will be a problem in case of both title and description field in modal menu, i think it would be better to throw exception incase of invalid inputs below `minlength`

**Comment by Zabuzard** [comment]
> This will be a problem in case of both title and description field in modal menu, i think it would be better to throw exception incase of invalid inputs below `minlength` otherwise might need to lower the `minLength`

I think you are not understanding what im saying.

When the user right clicks a short message and wants to transfer it, nothing visually happens. The user doesnt get an error message, no modal opens, nothing. The user never gets a chance to enter any title or message or anything.

Because our code instantly crashes before opening the modal and doesnt tell the user anything about it.

It is **not** that the user input sth bad into the modal and hit "submit", no. The modal never opened to begin with.

**Comment by ankitsmt211** [comment]
> > This will be a problem in case of both title and description field in modal menu, i think it would be better to throw exception incase of invalid inputs below `minlength` otherwise might need to lower the `minLength`
> 
> I think you are not understanding what im saying.
> 
> When the user right clicks a short message and wants to transfer it, nothing visually happens. The user doesnt get an error message, no modal opens, nothing. The user never gets a chance to enter any title or message or anything.
> 
> Because our code instantly crashes before opening the modal and doesnt tell the user anything about it.
> 
> It is **not** that the user input sth bad into the modal and hit "submit", no. The modal never opened to begin with.

No i do understand, i tried to temp fix by putting a check on "title function" which would give back `Untitled` incase of small input which worked. But same problem repeated with if text was 1 character in length. What im trying to say is if i change the `minLength` requirement to "1" on both content and title field inside modal menu we could avoid this or other way would be to throw the exception. So what do you suggest?

**Comment by Zabuzard** [comment]
We are in full control of what we feed to the discord modal. If the message content doesnt fit, we will provide a better default that fits.

There is no need to hack around, since we have full control of what exactly we set. If the auto-content doesnt meet the criteria, we replace it with `Untitled` or similar. There is no point in throwing exceptions here at all.

**Comment by ankitsmt211** [comment]
> We are in full control of what we feed to the discord modal. If the message content doesnt fit, we will provide a better default that fits.

I'm not sure if i understand this correctly, let's say the user text is "a". What do you suggest should happen? such a small text shouldn't be transferred in the first place but if someone is not familiar and does it i think it's wise to inform them perhaps and kill the chain of action (similar stuff like we did with bot message transfers).

**Comment by Zabuzard** [comment]
open the modal and let the user fill in some content to meet the minimum criteria.

theres no reason why we should forbid that. would only be annoyance if a helper wants to use it on a short message for whatever reason.

perhaps a possible scenario:
someone posts "can u help me learn arrays please?"
and then edits it shortly after with "nvm"

a helper might want to transfer "nvm" and fill in the old content manually into the modal.

**Comment by ankitsmt211** [comment]
> open the modal and let the user fill in some content to meet the minimum criteria.

The only way to allow that is by setting MIN_LENGTH to 1, but then i'd have to interfere with `onModalSubmit` to check if message isn't too short.

**Comment by Zabuzard** [comment]
No, its not. You literally just have to adjust your code to not feed the modal with an invalid starting value.
The crash happens bc of `modal.setTitle(...)` and `modal.setMessage(...)` or whatever its called.

Its our code and we are in full control of what we put in there. If the message is too small, then just dont call that method and discord will display the default "hint" and the user must fill in data.

**Comment by ankitsmt211** [comment]
is this what you're expecting incase of shorter messages?
![image](https://github.com/Together-Java/TJ-Bot/assets/61616007/18ff2545-7b6e-4862-a89b-0cf594a94134)

**Comment by Zabuzard** [comment]
yes, thanks
