### ISSUE TITLE
Transfer crashes when used on bot-message

### ISSUE THREAD

**Issue by Zabuzard** [Together-Java/TJ-Bot#927]
The transfer-command should have a fail-safe when triggered on a bot-message.

Right now it crashes because it can not DM bots. Especially when used on itself:

![dm bot](https://i.imgur.com/T6Wcw33.png)

**Comment by ankitsmt211** [comment]
perhaps an ephermal message to inform the user and kill the chain of action?

**Comment by Zabuzard** [comment]
Sure

**Comment by aayush010** [comment]
Hey @ankitsmt211 ,
I tried to work on this issue but I am unable to get the helper-forum while trying to transfer a question.
I guess something need to be change on config. 
Could you please help

**Comment by ankitsmt211** [comment]
> Hey @ankitsmt211 ,
> I tried to work on this issue but I am unable to get the helper-forum while trying to transfer a question.
> I guess something need to be change on config. 
> Could you please help

Hi, I already linked the Pull request to fix this bug😅. Apart from this, you need to have the forum created on your server with same name as our helper forum. You can either create it manually or use server template to make a copy of TJ server(it's prolly mentioned in wiki).
