### ISSUE TITLE
Make prompt of chatgpt visible

### ISSUE THREAD

**Issue by Taz03** [Together-Java/TJ-Bot#935]
Right now if we use chatgpt command it only gives us the answer, and we have no way to see what we prompted.

It'd be nice to have the option to see the prompt, and as a public server, everyone should be able to see everyones prompt.

My Implementation idea would be to have a button on each answer which when clicked sends a model with the prompt, and when the model is submitted it works as a normal chatgpt command, to allow quick edits as well.

**Comment by Zabuzard** [comment]
What about posting 2 embeds?
the original question, with the author picture and then the chatgpt answer as embed, also with a author picture.
That way it will look like a discord-native conversation.

Note that the slash command (was) just for internal dev-testing. Hence the "bad" UX.

**Comment by Taz03** [comment]
Embeds have 2 big problems
1. This is how code looks like
![image](https://github.com/Together-Java/TJ-Bot/assets/73871477/3a676b88-0042-4fda-8de6-f266e990dd04)

2. No image and link embeds

**Comment by Zabuzard** [comment]
1. im aware, the benefits outweight the disadvantages though. we will also introduce it for chatgpts auto-answers soon
2. we have `LinkPreview` which automatically adds images and links.

**Comment by ankitsmt211** [comment]
this issue no longer persists after gpt response are done via embed, closing this issue feel free to re open if anyone feels otherwise.
