### ISSUE TITLE
get role back message is wrong

### ISSUE THREAD

**Issue by Galliad93** [Together-Java/TJ-Bot#946]
when you are inactive for a while you get your helper role removerd. he then says to go to #⁠questions to get it again, but you need to go to #⁠select-your-roles. The text needs to be changed.

**Comment by Nxllpointer** [comment]
Responsible piece of Code: https://github.com/Together-Java/TJ-Bot/blob/develop/application/src/main/java/org/togetherjava/tjbot/features/help/AutoPruneHelperRoutine.java#L155-L161

**Comment by Zabuzard** [comment]
The `#select_your_role` channel isnt tracked by the system yet. So it has to be added to `Config.java` (and `config.json.template`) first, and then referenced in the linked code.
